import { useCallback, useEffect, useState } from "react";
import { BookOpenCheck, Loader2, Save } from "lucide-react";
import { Link } from "react-router-dom";
import { supabase } from "@/lib/supabase";
import { ErrorBanner, PageHeader } from "@/components/ui";

export default function OrderBookSettings(){
 const [enabled,setEnabled]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);const{data,error}=await supabase.from("company_settings").select("order_book_enabled").maybeSingle();if(error)setError(error.message);else setEnabled(Boolean(data?.order_book_enabled));setLoading(false)},[]);
 useEffect(()=>{void load()},[load]);
 const save=async()=>{setSaving(true);setSaved(false);setError(null);try{const{data:companyId,error:cidErr}=await supabase.rpc("current_company_id");if(cidErr)throw cidErr;if(!companyId)throw new Error("No active company selected.");const{error}=await supabase.from("company_settings").update({order_book_enabled:enabled,updated_at:new Date().toISOString()}).eq("company_id",String(companyId));if(error)throw error;setSaved(true)}catch(e:any){setError(e?.message||"Failed to save Order Book setting.")}finally{setSaving(false)}};
 if(loading)return <div className="flex min-h-[280px] items-center justify-center"><Loader2 className="mr-2 h-5 w-5 animate-spin"/>Loading...</div>;
 return <div className="space-y-4"><PageHeader title="Order Book & Rate Commitments / آرڈر بک اور ریٹ معاہدے" subtitle="Company-wise optional service for Sales and Purchase quantity/rate commitments"/>{error&&<ErrorBanner message={error}/>} {saved&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm font-bold text-emerald-700">Saved successfully / کامیابی سے محفوظ ہوگیا۔</div>}
 <section className="max-w-4xl rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div className="max-w-2xl"><div className="flex items-center gap-2 text-lg font-black"><BookOpenCheck className="h-5 w-5"/>Sales + Purchase Order Book / سیلز + پرچیز آرڈر بک</div><p className="mt-2 text-sm leading-6 text-slate-600">When inactive, NAVILO keeps the existing direct-invoice workflow unchanged. When active, Order Book screens maintain agreed/pending rates, effective dates, spot quantities, rate revisions, fulfilled quantity and remaining quantity. Order records themselves do not post GL, VAT or stock.</p><p className="mt-2 text-sm leading-6 text-slate-600">غیر فعال ہونے پر موجودہ ڈائریکٹ انوائس طریقہ بالکل پہلے جیسا رہے گا۔ فعال ہونے پر آرڈر بک طے شدہ/زیر التوا ریٹ، مؤثر تاریخ، موقع پر اضافی مقدار، ریٹ تبدیلی، مکمل اور بقایا مقدار محفوظ کرے گی۔ آرڈر بنانے سے خود اکاؤنٹنگ، وی اے ٹی یا اسٹاک پوسٹ نہیں ہوگا۔</p></div><button type="button" onClick={()=>setEnabled(v=>!v)} className={`min-w-[150px] rounded-xl border px-4 py-3 text-sm font-black ${enabled?"border-emerald-300 bg-emerald-50 text-emerald-800":"border-slate-300 bg-slate-50 text-slate-700"}`}>{enabled?"ACTIVE / فعال":"INACTIVE / غیر فعال"}</button></div>
 <div className="mt-5 grid gap-3 md:grid-cols-2"><Link to="/sales/order-book" className="rounded-xl border border-blue-200 bg-blue-50 p-4 font-bold text-blue-800">Open Sales Order Book / سیلز آرڈر بک کھولیں</Link><Link to="/purchase/order-book" className="rounded-xl border border-violet-200 bg-violet-50 p-4 font-bold text-violet-800">Open Purchase Order Book / پرچیز آرڈر بک کھولیں</Link></div>
 <div className="mt-5 flex justify-end border-t pt-4"><button className="btn btn-primary" disabled={saving} onClick={()=>void save()}>{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Save Service Setting / سروس سیٹنگ محفوظ کریں</button></div></section></div>
}
