import { useCallback, useEffect, useState } from "react";
import { Plus, Save } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { ErrorBanner } from "@/components/ui";

type Tax = { id?: string; name: string; rate: string; applies_to: "sales"|"purchase"|"both"; is_fixed: boolean; is_active: boolean };
type Charge = { id?: string; charge_key: string; charge_label: string; rate: string; unit: string; applies_to: "sales"|"purchase"|"both"; is_fixed: boolean; is_active: boolean };

export default function TaxSettings(){
 const [taxes,setTaxes]=useState<Tax[]>([]); const [charges,setCharges]=useState<Charge[]>([]); const [error,setError]=useState<string|null>(null); const [saved,setSaved]=useState(false);
 const load=useCallback(async()=>{ const [t,c]=await Promise.all([supabase.from("tax_rates").select("*").order("name"),supabase.from("charge_rate_settings").select("*").order("charge_label")]); if(t.error||c.error)setError((t.error||c.error)?.message||null); setTaxes((t.data||[]).map((x:any)=>({...x,rate:String(x.rate)}))); setCharges((c.data||[]).map((x:any)=>({...x,rate:String(x.rate)}))); },[]);
 useEffect(()=>{void load()},[load]);
 const save=async()=>{setError(null); try{ for(const t of taxes){const payload={...t,rate:Number(t.rate)||0}; delete (payload as any).id; if(t.id) { const {error:e}=await supabase.from("tax_rates").update(payload).eq("id",t.id); if(e) throw e; } else { const {error:e}=await supabase.from("tax_rates").insert(payload); if(e) throw e; }} for(const c of charges){const payload={...c,rate:Number(c.rate)||0}; delete (payload as any).id; if(c.id) { const {error:e}=await supabase.from("charge_rate_settings").update(payload).eq("id",c.id); if(e) throw e; } else { const {error:e}=await supabase.from("charge_rate_settings").insert(payload); if(e) throw e; }} setSaved(true); setTimeout(()=>setSaved(false),2500); await load(); }catch(e:any){setError(e.message||"Save failed.")}};
 return <div className="space-y-4"><div className="rounded-xl border bg-white p-5"><h1 className="text-xl font-bold">Tax & Charge Settings / ٹیکس اور چارج سیٹنگز</h1><p className="mt-1 text-xs text-slate-500">Configure fixed or changeable rates for Sales and Purchase. / فروخت اور خریداری کیلئے مقررہ یا قابلِ تبدیلی شرحیں ترتیب دیں۔</p></div>{error&&<ErrorBanner message={error}/>} {saved&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-xs text-emerald-700">Saved successfully / کامیابی سے محفوظ ہوگیا۔</div>}
 <section className="rounded-lg border bg-white p-4"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-semibold">Tax Rates / ٹیکس ریٹس</h2><p className="text-[12px] text-slate-400">Fixed = default rate; Changeable = authorized user can override.</p></div><button className="btn-secondary" onClick={()=>setTaxes([...taxes,{name:"New Tax",rate:"0",applies_to:"both",is_fixed:false,is_active:true}])}><Plus className="h-3.5 w-3.5"/>Add / شامل کریں</button></div><div className="space-y-2">{taxes.map((t,i)=><div key={t.id||i} className="grid grid-cols-1 gap-2 rounded border p-3 md:grid-cols-5"><input className="input" value={t.name} onChange={e=>{const x=[...taxes];x[i]={...t,name:e.target.value};setTaxes(x)}}/><input className="input" type="number" step="0.01" value={t.rate} onChange={e=>{const x=[...taxes];x[i]={...t,rate:e.target.value};setTaxes(x)}}/><select className="input" value={t.applies_to} onChange={e=>{const x=[...taxes];x[i]={...t,applies_to:e.target.value as any};setTaxes(x)}}><option value="sales">Sales / فروخت</option><option value="purchase">Purchase / خریداری</option><option value="both">Both / دونوں</option></select><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={t.is_fixed} onChange={e=>{const x=[...taxes];x[i]={...t,is_fixed:e.target.checked};setTaxes(x)}}/> Fixed / مقررہ</label><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={t.is_active} onChange={e=>{const x=[...taxes];x[i]={...t,is_active:e.target.checked};setTaxes(x)}}/> Active / فعال</label></div>)}</div></section>
 <section className="rounded-lg border bg-white p-4"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-semibold">Charge Rates / چارج ریٹس</h2><p className="text-[12px] text-slate-400">Loading, Cutting, Transport, Labour, Handling and other charges. / لوڈنگ، کٹنگ، ٹرانسپورٹ، مزدوری، ہینڈلنگ اور دیگر چارجز۔</p></div><button className="btn-secondary" onClick={()=>setCharges([...charges,{charge_key:`custom_${Date.now()}`,charge_label:"New Charge",rate:"0",unit:"fixed",applies_to:"both",is_fixed:false,is_active:true}])}><Plus className="h-3.5 w-3.5"/>Add / شامل کریں</button></div><div className="space-y-2">{charges.map((c,i)=><div key={c.id||i} className="grid grid-cols-1 gap-2 rounded border p-3 md:grid-cols-6"><input className="input" value={c.charge_label} onChange={e=>{const x=[...charges];x[i]={...c,charge_label:e.target.value};setCharges(x)}}/><input className="input" type="number" step="0.01" value={c.rate} onChange={e=>{const x=[...charges];x[i]={...c,rate:e.target.value};setCharges(x)}}/><input className="input" value={c.unit} onChange={e=>{const x=[...charges];x[i]={...c,unit:e.target.value};setCharges(x)}}/><select className="input" value={c.applies_to} onChange={e=>{const x=[...charges];x[i]={...c,applies_to:e.target.value as any};setCharges(x)}}><option value="sales">Sales / فروخت</option><option value="purchase">Purchase / خریداری</option><option value="both">Both / دونوں</option></select><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={c.is_fixed} onChange={e=>{const x=[...charges];x[i]={...c,is_fixed:e.target.checked};setCharges(x)}}/>Fixed / مقررہ</label><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={c.is_active} onChange={e=>{const x=[...charges];x[i]={...c,is_active:e.target.checked};setCharges(x)}}/>Active / فعال</label></div>)}</div></section>
 <div className="flex justify-end"><button className="btn-primary" onClick={save}><Save className="h-3.5 w-3.5"/> Save Settings / محفوظ کریں</button></div></div>
}
