import { useCallback,useEffect,useMemo,useState } from "react";
import { useLocation } from "react-router-dom";
import { BarChart3,RefreshCw,RotateCcw } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { ErrorBanner,formatCurrency,formatDate } from "@/components/ui";

type Kind="money"|"date"|"number"|"percent";
type Col={key:string;label:string;kind?:Kind};
type Def={title:string;view?:string;rpc?:string;period?:boolean;cols:Col[];dateKey?:string;partyKey?:string;itemKey?:string;statusKey?:string;order?:string;note?:string};
const n=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
const C=(...x:Col[])=>x;
const defs:Record<string,Def>={
 "/reports":{title:"Sales & Margin",view:"sales_margin_report",dateKey:"invoice_date",partyKey:"customer_name",order:"invoice_date",cols:C({key:"invoice_no",label:"Invoice"},{key:"invoice_date",label:"Date",kind:"date"},{key:"customer_name",label:"Customer"},{key:"sales_person",label:"Salesperson"},{key:"net_sales_amount",label:"Net Sales",kind:"money"},{key:"cost_amount",label:"Actual COGS",kind:"money"},{key:"gross_profit",label:"Gross Profit",kind:"money"},{key:"margin_percent",label:"Margin %",kind:"percent"})},
 "/reports/sales-margin":{title:"Sales & Margin",view:"sales_margin_report",dateKey:"invoice_date",partyKey:"customer_name",order:"invoice_date",cols:C({key:"invoice_no",label:"Invoice"},{key:"invoice_date",label:"Date",kind:"date"},{key:"customer_name",label:"Customer"},{key:"sales_person",label:"Salesperson"},{key:"net_sales_amount",label:"Net Sales",kind:"money"},{key:"cost_amount",label:"Actual COGS",kind:"money"},{key:"gross_profit",label:"Gross Profit",kind:"money"},{key:"margin_percent",label:"Margin %",kind:"percent"})},
 "/reports/sales-register":{title:"Sales Register",view:"sales_register_report",dateKey:"order_date",partyKey:"customer_name",statusKey:"payment_status",order:"order_date",cols:C({key:"order_no",label:"Invoice"},{key:"order_date",label:"Date",kind:"date"},{key:"customer_name",label:"Customer"},{key:"invoice_type",label:"Type"},{key:"sales_person",label:"Salesperson"},{key:"total",label:"Total",kind:"money"},{key:"paid_amount",label:"Received",kind:"money"},{key:"outstanding_amount",label:"Outstanding",kind:"money"},{key:"payment_status",label:"Status"},{key:"due_date",label:"Due",kind:"date"})},
 "/reports/purchase-register":{title:"Purchase Register",view:"purchase_register_report",dateKey:"order_date",partyKey:"supplier_name",statusKey:"payment_status",order:"order_date",cols:C({key:"order_no",label:"Purchase Invoice"},{key:"order_date",label:"Date",kind:"date"},{key:"supplier_name",label:"Supplier"},{key:"supplier_invoice_no",label:"Supplier Ref"},{key:"total",label:"Total",kind:"money"},{key:"paid_amount",label:"Paid",kind:"money"},{key:"outstanding_amount",label:"Outstanding",kind:"money"},{key:"payment_status",label:"Status"},{key:"due_date",label:"Due",kind:"date"})},
 "/reports/customer-aging":{title:"Customer Aging",view:"customer_invoice_aging",dateKey:"invoice_date",partyKey:"customer_name",statusKey:"aging_bucket",order:"invoice_date",cols:C({key:"invoice_no",label:"Invoice"},{key:"invoice_date",label:"Date",kind:"date"},{key:"customer_name",label:"Customer"},{key:"invoice_amount",label:"Invoice",kind:"money"},{key:"paid_amount",label:"Received",kind:"money"},{key:"outstanding_amount",label:"Outstanding",kind:"money"},{key:"due_date",label:"Due",kind:"date"},{key:"overdue_days",label:"Overdue Days",kind:"number"},{key:"aging_bucket",label:"Bucket"})},
 "/reports/supplier-aging":{title:"Supplier Aging",view:"supplier_invoice_aging",dateKey:"invoice_date",partyKey:"supplier_name",statusKey:"aging_bucket",order:"invoice_date",cols:C({key:"invoice_no",label:"Invoice"},{key:"invoice_date",label:"Date",kind:"date"},{key:"supplier_name",label:"Supplier"},{key:"invoice_amount",label:"Invoice",kind:"money"},{key:"paid_amount",label:"Paid",kind:"money"},{key:"outstanding_amount",label:"Outstanding",kind:"money"},{key:"due_date",label:"Due",kind:"date"},{key:"overdue_days",label:"Overdue Days",kind:"number"},{key:"aging_bucket",label:"Bucket"})},
 "/reports/customer-item-history":{title:"Customer Item History",view:"customer_item_history_report",dateKey:"order_date",partyKey:"customer_name",itemKey:"item_name",order:"order_date",cols:C({key:"order_no",label:"Invoice"},{key:"order_date",label:"Date",kind:"date"},{key:"customer_name",label:"Customer"},{key:"item_name",label:"Item"},{key:"size",label:"Size"},{key:"qty",label:"Qty",kind:"number"},{key:"rate",label:"Sale Rate",kind:"money"},{key:"line_total",label:"Sale Value",kind:"money"},{key:"cost_total",label:"Actual Cost",kind:"money"})},
 "/reports/supplier-item-history":{title:"Supplier Item History",view:"supplier_item_history_report",dateKey:"order_date",partyKey:"supplier_name",itemKey:"item_name",order:"order_date",cols:C({key:"order_no",label:"Purchase Invoice"},{key:"order_date",label:"Date",kind:"date"},{key:"supplier_name",label:"Supplier"},{key:"item_name",label:"Item"},{key:"size",label:"Size"},{key:"qty",label:"Qty",kind:"number"},{key:"rate",label:"Rate",kind:"money"},{key:"line_total",label:"Purchase Value",kind:"money"})},
 "/reports/stock-valuation":{title:"Stock Valuation",view:"stock_godown_report",itemKey:"item_name",cols:C({key:"item_name",label:"Item"},{key:"grade",label:"Grade"},{key:"size",label:"Size"},{key:"unit",label:"UOM"},{key:"godown",label:"Godown"},{key:"quantity",label:"Qty",kind:"number"},{key:"avg_cost",label:"Avg Cost",kind:"money"},{key:"stock_value",label:"Stock Value",kind:"money"})},
 "/reports/returns-register":{title:"Returns Register",view:"returns_register_report",dateKey:"note_date",partyKey:"party_name",order:"note_date",cols:C({key:"note_no",label:"Note No"},{key:"note_date",label:"Date",kind:"date"},{key:"note_type",label:"Type"},{key:"party_name",label:"Party"},{key:"reason",label:"Reason"},{key:"subtotal",label:"Subtotal",kind:"money"},{key:"tax_total",label:"Tax",kind:"money"},{key:"total",label:"Total",kind:"money"},{key:"cost_total",label:"Cost",kind:"money"})},
 "/reports/ar-ap-reconciliation":{title:"AR / AP Reconciliation",view:"accounting_control_reconciliation",cols:C({key:"ar_gl_balance",label:"AR GL",kind:"money"},{key:"customer_subledger_balance",label:"Customer Subledger",kind:"money"},{key:"ar_difference",label:"AR Difference",kind:"money"},{key:"ap_gl_balance",label:"AP GL",kind:"money"},{key:"supplier_subledger_balance",label:"Supplier Subledger",kind:"money"},{key:"ap_difference",label:"AP Difference",kind:"money"})},
 "/reports/exceptions":{title:"Accounting Exceptions",view:"accounting_exceptions",dateKey:"created_at",statusKey:"status",order:"created_at",cols:C({key:"created_at",label:"Created",kind:"date"},{key:"exception_type",label:"Exception"},{key:"severity",label:"Severity"},{key:"source_module",label:"Module"},{key:"source_type",label:"Source"},{key:"message",label:"Message"},{key:"status",label:"Status"})},
 "/reports/service-charges":{title:"Service Charges",view:"service_party_balance_report",partyKey:"name",cols:C({key:"name",label:"Party"},{key:"party_type",label:"Party Type"},{key:"charges_total",label:"Charges Total",kind:"money"})},
 "/reports/gate-pass":{title:"Gate Pass Report",view:"gate_passes",dateKey:"pass_date",partyKey:"customer_name",statusKey:"status",order:"pass_date",cols:C({key:"pass_no",label:"GP No"},{key:"pass_date",label:"Date",kind:"date"},{key:"customer_name",label:"Customer"},{key:"vehicle_no",label:"Vehicle"},{key:"driver_name",label:"Driver"},{key:"type",label:"Type"},{key:"godown",label:"Location"},{key:"net_weight",label:"Net Kg",kind:"number"},{key:"status",label:"Status"})},
 "/reports/customer-profitability":{title:"Customer Profitability",rpc:"report_customer_profitability",period:true,partyKey:"customer_name",cols:C({key:"customer_name",label:"Customer"},{key:"invoices",label:"Invoices",kind:"number"},{key:"net_sales",label:"Net Sales",kind:"money"},{key:"actual_cogs",label:"Actual COGS",kind:"money"},{key:"gross_profit",label:"Gross Profit",kind:"money"},{key:"margin_percent",label:"Margin %",kind:"percent"})},
 "/reports/item-profitability":{title:"Item Profitability",rpc:"report_item_profitability",period:true,itemKey:"item_name",cols:C({key:"item_name",label:"Item"},{key:"size",label:"Size"},{key:"unit",label:"UOM"},{key:"qty_sold",label:"Qty Sold",kind:"number"},{key:"avg_sale_rate",label:"Avg Sale Rate",kind:"money"},{key:"sales_value",label:"Sales Value",kind:"money"},{key:"actual_cost",label:"Actual Cost",kind:"money"},{key:"gross_profit",label:"Gross Profit",kind:"money"},{key:"margin_percent",label:"Margin %",kind:"percent"})},
 "/reports/salesperson-profitability":{title:"Salesperson Profitability",rpc:"report_salesperson_profitability",period:true,partyKey:"sales_person",cols:C({key:"sales_person",label:"Salesperson"},{key:"invoices",label:"Invoices",kind:"number"},{key:"net_sales",label:"Net Sales",kind:"money"},{key:"actual_cogs",label:"Actual COGS",kind:"money"},{key:"gross_profit",label:"Gross Profit",kind:"money"},{key:"margin_percent",label:"Margin %",kind:"percent"})},
 "/reports/customer-collections":{title:"Customer Collection Performance",rpc:"report_customer_collection_performance",period:true,partyKey:"customer_name",note:"Period selects the invoice cohort; received/outstanding values are current against those invoices.",cols:C({key:"customer_name",label:"Customer"},{key:"invoices",label:"Invoices",kind:"number"},{key:"invoiced",label:"Invoiced",kind:"money"},{key:"received",label:"Received",kind:"money"},{key:"outstanding",label:"Outstanding",kind:"money"},{key:"overdue_amount",label:"Overdue",kind:"money"},{key:"avg_days_outstanding",label:"Avg Days",kind:"number"},{key:"overdue_percent",label:"Overdue %",kind:"percent"})},
 "/reports/supplier-performance":{title:"Supplier Performance",rpc:"report_supplier_performance",period:true,partyKey:"supplier_name",note:"Purchase metrics follow the selected period; outstanding and overdue are current balances.",cols:C({key:"supplier_name",label:"Supplier"},{key:"purchase_invoices",label:"Invoices",kind:"number"},{key:"qty_purchased",label:"Qty Purchased",kind:"number"},{key:"purchase_value",label:"Purchase Value",kind:"money"},{key:"avg_rate",label:"Avg Rate",kind:"money"},{key:"current_outstanding",label:"Current Outstanding",kind:"money"},{key:"current_overdue",label:"Current Overdue",kind:"money"})},
 "/reports/purchase-price-variance":{title:"Purchase Price Variance",rpc:"report_purchase_price_variance",period:true,partyKey:"supplier_name",itemKey:"item_name",cols:C({key:"supplier_name",label:"Supplier"},{key:"item_name",label:"Item"},{key:"size",label:"Size"},{key:"purchases",label:"Purchases",kind:"number"},{key:"qty_purchased",label:"Qty",kind:"number"},{key:"avg_purchase_rate",label:"Avg Rate",kind:"money"},{key:"min_rate",label:"Min Rate",kind:"money"},{key:"max_rate",label:"Max Rate",kind:"money"},{key:"rate_spread",label:"Rate Spread",kind:"money"},{key:"purchase_value",label:"Purchase Value",kind:"money"})},
 "/reports/inventory-aging":{title:"Inventory Aging / Slow Moving",view:"inventory_aging_report",itemKey:"item_name",statusKey:"aging_bucket",cols:C({key:"item_name",label:"Item"},{key:"size",label:"Size"},{key:"godown",label:"Godown"},{key:"quantity",label:"Qty",kind:"number"},{key:"stock_value",label:"Stock Value",kind:"money"},{key:"last_movement_date",label:"Last Movement",kind:"date"},{key:"days_since_movement",label:"Days Idle",kind:"number"},{key:"aging_bucket",label:"Aging Bucket"})},
 "/reports/inventory-turnover":{title:"Inventory Turnover",rpc:"report_inventory_turnover",period:true,itemKey:"item_name",note:"Turnover is a period COGS / current stock-value basis because historical inventory valuation snapshots are not available.",cols:C({key:"item_name",label:"Item"},{key:"size",label:"Size"},{key:"current_qty",label:"Current Qty",kind:"number"},{key:"current_stock_value",label:"Current Stock Value",kind:"money"},{key:"qty_sold",label:"Qty Sold",kind:"number"},{key:"cogs",label:"Period COGS",kind:"money"},{key:"turnover_current_stock_basis",label:"Turnover (Current Basis)",kind:"number"})},
 "/reports/stock-exceptions":{title:"Stock Exceptions",view:"stock_exception_report",itemKey:"item_name",statusKey:"exception_type",cols:C({key:"item_name",label:"Item"},{key:"size",label:"Size"},{key:"godown",label:"Godown"},{key:"quantity",label:"Qty",kind:"number"},{key:"avg_cost",label:"Avg Cost",kind:"money"},{key:"stock_value",label:"Stock Value",kind:"money"},{key:"last_movement_resulting_qty",label:"Last Movement Qty",kind:"number"},{key:"exception_type",label:"Exception"})},
 "/reports/business-unit-performance":{title:"Business Unit Performance",view:"business_unit_performance_report",cols:C({key:"business_unit_id",label:"Business Unit"},{key:"net_sales",label:"Net Sales",kind:"money"},{key:"gross_profit",label:"Gross Profit",kind:"money"},{key:"purchases",label:"Purchases",kind:"money"},{key:"receivables",label:"Receivables",kind:"money"},{key:"payables",label:"Payables",kind:"money"},{key:"inventory_value",label:"Inventory Value",kind:"money"})},
 "/reports/monthly-mis":{title:"Monthly Business Performance / MIS",view:"monthly_business_performance_report",dateKey:"month_start",order:"month_start",note:"AR, AP and inventory are current-state balances shown only on the current month; historical snapshots are not fabricated.",cols:C({key:"month_start",label:"Month",kind:"date"},{key:"net_sales",label:"Net Sales",kind:"money"},{key:"purchases",label:"Purchases",kind:"money"},{key:"gross_profit",label:"Gross Profit",kind:"money"},{key:"expenses",label:"Expenses",kind:"money"},{key:"net_profit",label:"Net Profit",kind:"money"},{key:"collections",label:"Collections",kind:"money"},{key:"previous_net_sales",label:"Previous Sales",kind:"money"},{key:"sales_change_percent",label:"Sales Change %",kind:"percent"},{key:"previous_gross_profit",label:"Previous GP",kind:"money"},{key:"previous_net_profit",label:"Previous Net Profit",kind:"money"},{key:"current_ar",label:"Current AR",kind:"money"},{key:"current_ap",label:"Current AP",kind:"money"},{key:"current_inventory_value",label:"Current Inventory",kind:"money"})},
};
function unique(rows:any[],key?:string){return key?Array.from(new Set(rows.map(r=>String(r[key]??"")).filter(Boolean))).sort():[]}
function show(v:any,k?:Kind){if(v===null||v===undefined||v==="")return"—";if(k==="money")return formatCurrency(n(v));if(k==="percent")return `${n(v).toFixed(2)}%`;if(k==="number")return n(v).toLocaleString();if(k==="date")return formatDate(String(v));return String(v)}
export default function Reports(){
 const loc=useLocation();const def=defs[loc.pathname]??defs["/reports/sales-margin"];
 const[data,setData]=useState<any[]>([]),[masterParties,setMasterParties]=useState<string[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
 const[q,setQ]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[party,setParty]=useState(""),[item,setItem]=useState(""),[status,setStatus]=useState("");
 const reset=()=>{setQ("");setFrom("");setTo("");setParty("");setItem("");setStatus("")};
 useEffect(()=>{reset()},[loc.pathname]);
 const load=useCallback(async()=>{
  setLoading(true);setError(null);
  let r:any;
  if(def.rpc) r=await supabase.rpc(def.rpc,{p_from:from||null,p_to:to||null});
  else {let query=supabase.from(def.view!).select("*").limit(10000);if(def.order)query=query.order(def.order,{ascending:false});r=await query;}
  if(r.error)setError(r.error.message);setData(r.data??[]);setLoading(false);
 },[def.rpc,def.view,def.order,from,to]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{
  let cancelled=false;
  const loadMasterParties=async()=>{
   const table=def.partyKey==="supplier_name"?"suppliers":def.partyKey==="customer_name"?"customers":null;
   if(!table){setMasterParties([]);return;}
   const r=await supabase.from(table).select("name").eq("is_active",true).order("name");
   if(cancelled)return;
   if(r.error){setMasterParties([]);return;}
   setMasterParties(Array.from(new Set((r.data??[]).map((x:any)=>String(x.name??"").trim()).filter(Boolean))));
  };
  void loadMasterParties();
  return()=>{cancelled=true};
 },[def.partyKey]);
 const parties=useMemo(()=>masterParties.length?masterParties:unique(data,def.partyKey),[data,def.partyKey,masterParties]),items=useMemo(()=>unique(data,def.itemKey),[data,def.itemKey]),statuses=useMemo(()=>unique(data,def.statusKey),[data,def.statusKey]);
 const rows=useMemo(()=>data.filter(r=>{if(def.dateKey&&!def.rpc){const d=String(r[def.dateKey]??"").slice(0,10);if(from&&d<from)return false;if(to&&d>to)return false}if(party&&def.partyKey&&String(r[def.partyKey]??"")!==party)return false;if(item&&def.itemKey&&String(r[def.itemKey]??"")!==item)return false;if(status&&def.statusKey&&String(r[def.statusKey]??"")!==status)return false;const s=q.trim().toLowerCase();return !s||JSON.stringify(r).toLowerCase().includes(s)}),[data,def,q,from,to,party,item,status]);
 const showDates=Boolean(def.dateKey||def.period);
 return <div className="space-y-4 pb-12">
  <div className="flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="flex items-center gap-2 text-xl font-bold"><BarChart3 className="h-5 w-5 text-blue-600"/>{def.title}</h1><p className="mt-1 text-xs text-slate-500">Filters apply to screen, column customization, Excel and Print Preview / PDF.</p>{def.note&&<p className="mt-1 text-xs font-medium text-amber-700">{def.note}</p>}</div><button className="btn-secondary no-print" onClick={()=>void load()}><RefreshCw className="h-4 w-4"/>Refresh</button></div>
  {error&&<ErrorBanner message={error}/>}<div className="no-print rounded-xl border border-slate-200 bg-white p-3"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-6"><input className="input lg:col-span-2" placeholder={`Search ${def.title}...`} value={q} onChange={e=>setQ(e.target.value)}/>{showDates&&<><label className="flex min-w-0 flex-col gap-1 text-xs font-semibold text-slate-600"><span>From date</span><input type="date" className="input w-full" aria-label="From date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="flex min-w-0 flex-col gap-1 text-xs font-semibold text-slate-600"><span>To date</span><input type="date" className="input w-full" aria-label="To date" value={to} onChange={e=>setTo(e.target.value)}/></label></>}{def.partyKey&&<select className="input" value={party} onChange={e=>setParty(e.target.value)}><option value="">All Parties</option>{parties.map(x=><option key={x}>{x}</option>)}</select>}{def.itemKey&&<select className="input" value={item} onChange={e=>setItem(e.target.value)}><option value="">All Items</option>{items.map(x=><option key={x}>{x}</option>)}</select>}{def.statusKey&&<select className="input" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All Status</option>{statuses.map(x=><option key={x}>{x}</option>)}</select>}<button className="btn-secondary" onClick={reset}><RotateCcw className="h-4 w-4"/>Reset</button></div></div>
  <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="table w-full"><thead><tr>{def.cols.map(c=><th key={c.key} className={c.kind&&c.kind!=="date"?"text-right":""}>{c.label}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={def.cols.length} className="py-12 text-center text-slate-500">Loading report…</td></tr>:rows.length?rows.map((r,i)=><tr key={String(r.id??r.sales_order_id??r.item_id??r.customer_id??r.supplier_id??r.month_start??i)}>{def.cols.map(c=><td key={c.key} className={c.kind&&c.kind!=="date"?"text-right tabular-nums":""}>{show(r[c.key],c.kind)}</td>)}</tr>):<tr><td colSpan={def.cols.length} className="py-12 text-center text-slate-500">No records for selected filters.</td></tr>}</tbody><tfoot><tr className="bg-slate-50 font-semibold"><td colSpan={def.cols.length}>{rows.length.toLocaleString()} record{rows.length===1?"":"s"}</td></tr></tfoot></table></div>
 </div>
}