import { useCallback,useEffect,useMemo,useState } from "react";
import { useLocation } from "react-router-dom";
import { BarChart3,RefreshCw,RotateCcw } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { ErrorBanner,formatCurrency,formatDate } from "@/components/ui";

type Kind="money"|"date"|"number"|"percent"; type Col={key:string;label:string;kind?:Kind};
type Def={title:string;view:string;cols:Col[];dateKey?:string;partyKey?:string;itemKey?:string;statusKey?:string;order?:string};
const n=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
const C=(...x:Col[])=>x;
const defs:Record<string,Def>={
 "/reports/sales-margin":{title:"Sales & Margin",view:"sales_margin_report",dateKey:"invoice_date",partyKey:"customer_name",order:"invoice_date",cols:C({key:"invoice_no",label:"Invoice"},{key:"invoice_date",label:"Date",kind:"date"},{key:"customer_name",label:"Customer"},{key:"sales_person",label:"Salesperson"},{key:"net_sales_amount",label:"Net Sales",kind:"money"},{key:"cost_amount",label:"Actual COGS",kind:"money"},{key:"gross_profit",label:"Gross Profit",kind:"money"},{key:"margin_percent",label:"Margin %",kind:"percent"})},
 "/reports/sales-register":{title:"Sales Register",view:"sales_register_report",dateKey:"order_date",partyKey:"customer_name",statusKey:"payment_status",order:"order_date",cols:C({key:"order_no",label:"Invoice"},{key:"order_date",label:"Date",kind:"date"},{key:"customer_name",label:"Customer"},{key:"invoice_type",label:"Type"},{key:"sales_person",label:"Salesperson"},{key:"total",label:"Total",kind:"money"},{key:"paid_amount",label:"Received",kind:"money"},{key:"outstanding_amount",label:"Outstanding",kind:"money"},{key:"payment_status",label:"Status"},{key:"due_date",label:"Due",kind:"date"})},
 "/reports/purchase-register":{title:"Purchase Register",view:"purchase_register_report",dateKey:"order_date",partyKey:"supplier_name",statusKey:"payment_status",order:"order_date",cols:C({key:"order_no",label:"Purchase Invoice"},{key:"order_date",label:"Date",kind:"date"},{key:"supplier_name",label:"Supplier"},{key:"supplier_invoice_no",label:"Supplier Ref"},{key:"total",label:"Total",kind:"money"},{key:"paid_amount",label:"Paid",kind:"money"},{key:"outstanding_amount",label:"Outstanding",kind:"money"},{key:"payment_status",label:"Status"},{key:"due_date",label:"Due",kind:"date"})},
 "/reports/customer-aging":{title:"Customer Aging",view:"customer_invoice_aging",dateKey:"invoice_date",partyKey:"customer_name",statusKey:"aging_bucket",order:"invoice_date",cols:C({key:"invoice_no",label:"Invoice"},{key:"invoice_date",label:"Date",kind:"date"},{key:"customer_name",label:"Customer"},{key:"invoice_amount",label:"Invoice",kind:"money"},{key:"paid_amount",label:"Received",kind:"money"},{key:"outstanding_amount",label:"Outstanding",kind:"money"},{key:"due_date",label:"Due",kind:"date"},{key:"overdue_days",label:"Overdue Days",kind:"number"},{key:"aging_bucket",label:"Bucket"})},
 "/reports/supplier-aging":{title:"Supplier Aging",view:"supplier_invoice_aging",dateKey:"invoice_date",partyKey:"supplier_name",statusKey:"aging_bucket",order:"invoice_date",cols:C({key:"invoice_no",label:"Invoice"},{key:"invoice_date",label:"Date",kind:"date"},{key:"supplier_name",label:"Supplier"},{key:"invoice_amount",label:"Invoice",kind:"money"},{key:"paid_amount",label:"Paid",kind:"money"},{key:"outstanding_amount",label:"Outstanding",kind:"money"},{key:"due_date",label:"Due",kind:"date"},{key:"overdue_days",label:"Overdue Days",kind:"number"},{key:"aging_bucket",label:"Bucket"})},
 "/reports/customer-item-history":{title:"Customer Item History",view:"customer_item_history_report",dateKey:"order_date",partyKey:"customer_name",itemKey:"item_name",order:"order_date",cols:C({key:"order_no",label:"Invoice"},{key:"order_date",label:"Date",kind:"date"},{key:"customer_name",label:"Customer"},{key:"item_name",label:"Item"},{key:"size",label:"Size"},{key:"qty",label:"Qty",kind:"number"},{key:"rate",label:"Sale Rate",kind:"money"},{key:"line_total",label:"Sale Value",kind:"money"},{key:"cost_total",label:"Actual Cost",kind:"money"})},
 "/reports/supplier-item-history":{title:"Supplier Item History",view:"supplier_item_history_report",dateKey:"order_date",partyKey:"supplier_name",itemKey:"item_name",order:"order_date",cols:C({key:"order_no",label:"Purchase Invoice"},{key:"order_date",label:"Date",kind:"date"},{key:"supplier_name",label:"Supplier"},{key:"item_name",label:"Item"},{key:"size",label:"Size"},{key:"qty",label:"Qty",kind:"number"},{key:"rate",label:"Rate",kind:"money"},{key:"line_total",label:"Purchase Value",kind:"money"})},
 "/reports/stock-valuation":{title:"Stock Valuation",view:"stock_godown_report",itemKey:"item_name",cols:C({key:"item_name",label:"Item"},{key:"grade",label:"Grade"},{key:"size",label:"Size"},{key:"unit",label:"UOM"},{key:"godown",label:"Godown"},{key:"quantity",label:"Qty",kind:"number"},{key:"avg_cost",label:"Avg Cost",kind:"money"},{key:"stock_value",label:"Stock Value",kind:"money"})},
 "/reports/customer-profitability":{title:"Customer Profitability",view:"customer_profitability_report",partyKey:"customer_name",cols:C({key:"customer_name",label:"Customer"},{key:"invoices",label:"Invoices",kind:"number"},{key:"net_sales",label:"Net Sales",kind:"money"},{key:"actual_cogs",label:"Actual COGS",kind:"money"},{key:"gross_profit",label:"Gross Profit",kind:"money"},{key:"margin_percent",label:"Margin %",kind:"percent"})},
 "/reports/item-profitability":{title:"Item Profitability",view:"item_profitability_report",itemKey:"item_name",cols:C({key:"item_name",label:"Item"},{key:"size",label:"Size"},{key:"unit",label:"UOM"},{key:"qty_sold",label:"Qty Sold",kind:"number"},{key:"avg_sale_rate",label:"Avg Sale Rate",kind:"money"},{key:"sales_value",label:"Sales Value",kind:"money"},{key:"actual_cost",label:"Actual Cost",kind:"money"},{key:"gross_profit",label:"Gross Profit",kind:"money"},{key:"margin_percent",label:"Margin %",kind:"percent"})},
 "/reports/salesperson-profitability":{title:"Salesperson Profitability",view:"salesperson_profitability_report",partyKey:"sales_person",cols:C({key:"sales_person",label:"Salesperson"},{key:"invoices",label:"Invoices",kind:"number"},{key:"net_sales",label:"Net Sales",kind:"money"},{key:"actual_cogs",label:"Actual COGS",kind:"money"},{key:"gross_profit",label:"Gross Profit",kind:"money"},{key:"margin_percent",label:"Margin %",kind:"percent"})},
 "/reports/customer-collections":{title:"Customer Collection Performance",view:"customer_collection_performance_report",partyKey:"customer_name",cols:C({key:"customer_name",label:"Customer"},{key:"invoices",label:"Invoices",kind:"number"},{key:"invoiced",label:"Invoiced",kind:"money"},{key:"received",label:"Received",kind:"money"},{key:"outstanding",label:"Outstanding",kind:"money"},{key:"overdue_amount",label:"Overdue",kind:"money"},{key:"avg_days_outstanding",label:"Avg Days",kind:"number"},{key:"overdue_percent",label:"Overdue %",kind:"percent"})},
 "/reports/supplier-performance":{title:"Supplier Performance",view:"supplier_performance_report",partyKey:"supplier_name",cols:C({key:"supplier_name",label:"Supplier"},{key:"purchase_invoices",label:"Invoices",kind:"number"},{key:"qty_purchased",label:"Qty Purchased",kind:"number"},{key:"purchase_value",label:"Purchase Value",kind:"money"},{key:"avg_rate",label:"Avg Rate",kind:"money"},{key:"outstanding",label:"Outstanding",kind:"money"},{key:"overdue",label:"Overdue",kind:"money"})},
 "/reports/purchase-price-variance":{title:"Purchase Price Variance",view:"purchase_price_variance_report",partyKey:"supplier_name",itemKey:"item_name",cols:C({key:"supplier_name",label:"Supplier"},{key:"item_name",label:"Item"},{key:"size",label:"Size"},{key:"qty_purchased",label:"Qty",kind:"number"},{key:"avg_purchase_rate",label:"Avg Rate",kind:"money"},{key:"min_rate",label:"Min Rate",kind:"money"},{key:"max_rate",label:"Max Rate",kind:"money"},{key:"rate_spread",label:"Rate Spread",kind:"money"},{key:"purchase_value",label:"Purchase Value",kind:"money"})},
 "/reports/inventory-aging":{title:"Inventory Aging / Slow Moving",view:"inventory_aging_report",itemKey:"item_name",statusKey:"aging_bucket",cols:C({key:"item_name",label:"Item"},{key:"size",label:"Size"},{key:"godown",label:"Godown"},{key:"quantity",label:"Qty",kind:"number"},{key:"stock_value",label:"Stock Value",kind:"money"},{key:"last_movement_date",label:"Last Movement",kind:"date"},{key:"days_since_movement",label:"Days Idle",kind:"number"},{key:"aging_bucket",label:"Aging Bucket"})},
 "/reports/inventory-turnover":{title:"Inventory Turnover",view:"inventory_turnover_report",itemKey:"item_name",cols:C({key:"item_name",label:"Item"},{key:"size",label:"Size"},{key:"current_qty",label:"Current Qty",kind:"number"},{key:"current_stock_value",label:"Stock Value",kind:"money"},{key:"qty_sold",label:"Qty Sold",kind:"number"},{key:"cogs",label:"COGS",kind:"money"},{key:"turnover_ratio",label:"Turnover",kind:"number"})},
 "/reports/stock-exceptions":{title:"Stock Exceptions",view:"stock_exception_report",itemKey:"item_name",statusKey:"exception_type",cols:C({key:"item_name",label:"Item"},{key:"size",label:"Size"},{key:"godown",label:"Godown"},{key:"quantity",label:"Qty",kind:"number"},{key:"stock_value",label:"Stock Value",kind:"money"},{key:"exception_type",label:"Exception"})},
 "/reports/business-unit-performance":{title:"Business Unit Performance",view:"business_unit_performance_report",cols:C({key:"business_unit_id",label:"Business Unit"},{key:"net_sales",label:"Net Sales",kind:"money"},{key:"gross_profit",label:"Gross Profit",kind:"money"},{key:"purchases",label:"Purchases",kind:"money"},{key:"receivables",label:"Receivables",kind:"money"},{key:"payables",label:"Payables",kind:"money"},{key:"inventory_value",label:"Inventory Value",kind:"money"})},
 "/reports/monthly-mis":{title:"Monthly Business Performance / MIS",view:"monthly_business_performance_report",dateKey:"month_start",order:"month_start",cols:C({key:"month_start",label:"Month",kind:"date"},{key:"net_sales",label:"Net Sales",kind:"money"},{key:"gross_profit",label:"Gross Profit",kind:"money"},{key:"purchases",label:"Purchases",kind:"money"})},
};
function unique(rows:any[],key?:string){return key?Array.from(new Set(rows.map(r=>String(r[key]??"")).filter(Boolean))).sort():[]}
function show(v:any,k?:Kind){if(v===null||v===undefined||v==="")return"—";if(k==="money")return formatCurrency(n(v));if(k==="percent")return `${n(v).toFixed(2)}%`;if(k==="number")return n(v).toLocaleString();if(k==="date")return formatDate(String(v));return String(v)}
export default function Reports(){const loc=useLocation();const def=defs[loc.pathname]??defs["/reports/sales-margin"];const [data,setData]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);const [q,setQ]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[party,setParty]=useState(""),[item,setItem]=useState(""),[status,setStatus]=useState("");
 const reset=()=>{setQ("");setFrom("");setTo("");setParty("");setItem("");setStatus("")}; useEffect(reset,[loc.pathname]);
 const load=useCallback(async()=>{setLoading(true);setError(null);let query=supabase.from(def.view).select("*").limit(10000);if(def.order)query=query.order(def.order,{ascending:false});const r=await query;if(r.error)setError(r.error.message);setData(r.data??[]);setLoading(false)},[def.view,def.order]);useEffect(()=>{void load()},[load]);
 const parties=useMemo(()=>unique(data,def.partyKey),[data,def.partyKey]),items=useMemo(()=>unique(data,def.itemKey),[data,def.itemKey]),statuses=useMemo(()=>unique(data,def.statusKey),[data,def.statusKey]);
 const rows=useMemo(()=>data.filter(r=>{if(def.dateKey){const d=String(r[def.dateKey]??"").slice(0,10);if(from&&d<from)return false;if(to&&d>to)return false}if(party&&def.partyKey&&String(r[def.partyKey]??"")!==party)return false;if(item&&def.itemKey&&String(r[def.itemKey]??"")!==item)return false;if(status&&def.statusKey&&String(r[def.statusKey]??"")!==status)return false;const s=q.trim().toLowerCase();return !s||JSON.stringify(r).toLowerCase().includes(s)}),[data,def,q,from,to,party,item,status]);
 return <div className="space-y-4 pb-12"><div className="flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="flex items-center gap-2 text-xl font-bold"><BarChart3 className="h-5 w-5 text-blue-600"/>{def.title}</h1><p className="mt-1 text-xs text-slate-500">Filters apply to screen, column customization, Excel and Print Preview / PDF.</p></div><button className="btn-secondary no-print" onClick={()=>void load()}><RefreshCw className="h-4 w-4"/>Refresh</button></div>{error&&<ErrorBanner message={error}/>}<div className="no-print rounded-xl border border-slate-200 bg-white p-3"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-6"><input className="input lg:col-span-2" placeholder={`Search ${def.title}...`} value={q} onChange={e=>setQ(e.target.value)}/>{def.dateKey&&<><input type="date" className="input" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" className="input" value={to} onChange={e=>setTo(e.target.value)}/></>}{def.partyKey&&<select className="input" value={party} onChange={e=>setParty(e.target.value)}><option value="">All Parties</option>{parties.map(x=><option key={x}>{x}</option>)}</select>}{def.itemKey&&<select className="input" value={item} onChange={e=>setItem(e.target.value)}><option value="">All Items</option>{items.map(x=><option key={x}>{x}</option>)}</select>}{def.statusKey&&<select className="input" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All Status</option>{statuses.map(x=><option key={x}>{x}</option>)}</select>}<button className="btn-secondary" onClick={reset}><RotateCcw className="h-4 w-4"/>Reset</button></div></div><div className="rounded-xl border border-slate-200 bg-white p-3"><div className="mb-2 text-xs font-semibold text-slate-600">{loading?"Loading…":`${rows.length.toLocaleString()} rows`}</div><div className="overflow-auto"><table className="min-w-full text-xs"><thead><tr>{def.cols.map(c=><th key={c.key} className="px-3 py-2 text-left">{c.label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id??r.sales_order_id??r.purchase_order_id??i} className="border-t border-slate-100">{def.cols.map(c=><td key={c.key} className={`px-3 py-2 ${c.kind==="money"||c.kind==="number"||c.kind==="percent"?"text-right tabular-nums":""}`}>{show(r[c.key],c.kind)}</td>)}</tr>)}{!loading&&!rows.length&&<tr><td colSpan={def.cols.length} className="px-3 py-8 text-center text-slate-400">No records found.</td></tr>}</tbody></table></div></div></div>}
