import { useCallback, useEffect, useMemo, useState, type ComponentType, type ReactNode } from "react";
import { useNavigate } from "react-router-dom";
import { AlertTriangle, Banknote, Boxes, Building2, ChevronDown, ChevronUp, Eye, EyeOff, Factory, Landmark, RefreshCw, Settings2, ShoppingCart, WalletCards } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useAuth } from "@/auth/AuthContext";
import { supabase } from "@/lib/supabase";

type AccountBreakdown={account_id:string;code?:string|null;name:string;balance:number};
type TrendRow={date:string;sales:number;purchase:number;cash_in:number;cash_out:number;gross_profit:number;margin_percent:number};
type Summary={sales_total:number;sales_documents:number;purchase_total:number;purchase_documents:number;cash_balance:number;bank_balance:number;receivables:number;payables:number;inventory_value:number;stock_quantity:number;stock_alerts:number;pending_work_orders:number;cash_accounts:AccountBreakdown[];bank_accounts:AccountBreakdown[];trend:TrendRow[];as_of:string|null;start_date:string|null;end_date:string|null;bucket:"day"|"week"|"month"};
type WidgetId="sales"|"purchases"|"receivables"|"payables"|"cash"|"bank"|"inventory"|"sales_purchase"|"cash_flow"|"profit"|"operations";
type Kpi={id:WidgetId;label:string;value:string;note:string;icon:ComponentType<{className?:string}>;color:string;to:string;expandable?:"cash"|"bank"};
type RangeKey="today"|"week"|"month"|"3m"|"6m"|"12m"|"fy"|"custom";
const EMPTY:Summary={sales_total:0,sales_documents:0,purchase_total:0,purchase_documents:0,cash_balance:0,bank_balance:0,receivables:0,payables:0,inventory_value:0,stock_quantity:0,stock_alerts:0,pending_work_orders:0,cash_accounts:[],bank_accounts:[],trend:[],as_of:null,start_date:null,end_date:null,bucket:"month"};
const DEFAULT_HIDDEN:WidgetId[]=[];
const WIDGETS:Array<{id:WidgetId;label:string}>=[{id:"sales",label:"Sales"},{id:"purchases",label:"Purchases"},{id:"receivables",label:"Receivables"},{id:"payables",label:"Payables"},{id:"cash",label:"Cash Balance"},{id:"bank",label:"Bank Balance"},{id:"inventory",label:"Inventory Value"},{id:"sales_purchase",label:"Sales vs Purchase Trend"},{id:"cash_flow",label:"Cash In vs Cash Out"},{id:"profit",label:"Gross Profit & Margin"},{id:"operations",label:"Operations & Alerts"}];
const money=(v:number)=>`Rs ${new Intl.NumberFormat("en-PK",{maximumFractionDigits:0}).format(Number(v)||0)}`;
const qty=(v:number)=>new Intl.NumberFormat("en-PK",{maximumFractionDigits:2}).format(Number(v)||0);
const iso=(d:Date)=>d.toISOString().slice(0,10);
const startOfWeek=(d:Date)=>{const x=new Date(d);const day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);return x};
const startOfMonth=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),1);
const startOfFY=(d:Date)=>new Date(d.getFullYear(),0,1);
function rangeFor(key:RangeKey){const end=new Date();let start=new Date(end);if(key==="week")start=startOfWeek(end);else if(key==="month")start=startOfMonth(end);else if(key==="3m")start=new Date(end.getFullYear(),end.getMonth()-2,1);else if(key==="6m")start=new Date(end.getFullYear(),end.getMonth()-5,1);else if(key==="12m")start=new Date(end.getFullYear(),end.getMonth()-11,1);else if(key==="fy")start=startOfFY(end);return{start:iso(start),end:iso(end)}}
function bucketFor(start:string,end:string):"day"|"week"|"month"{const days=Math.max(1,Math.round((new Date(end).getTime()-new Date(start).getTime())/86400000));return days<=31?"day":days<=120?"week":"month"}
function labelDate(value:string,bucket:string){const d=new Date(`${value}T00:00:00`);return bucket==="day"?d.toLocaleDateString(undefined,{day:"2-digit",month:"short"}):bucket==="week"?`Wk ${d.toLocaleDateString(undefined,{day:"2-digit",month:"short"})}`:d.toLocaleDateString(undefined,{month:"short",year:"2-digit"})}
function Panel({title,action,children}:{title:string;action?:ReactNode;children:ReactNode}){return <section className="min-w-0 rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex min-h-11 items-center justify-between gap-3 border-b border-slate-200 px-4 py-2.5"><h2 className="text-xs font-black text-slate-900">{title}</h2>{action}</div><div className="p-3">{children}</div></section>}
function EmptyChart({message}:{message:string}){return <div className="flex h-64 items-center justify-center rounded-lg bg-slate-50 text-center"><div><div className="text-sm font-black text-slate-700">No activity</div><div className="mt-1 text-xs font-semibold text-slate-400">{message}</div></div></div>}
export default function Dashboard(){
 const navigate=useNavigate();const{activeCompany,activeBusinessUnit}=useAuth();const companyId=activeCompany?.company_id??null;const businessUnitId=activeBusinessUnit?.business_unit_id??null;
 const initial=rangeFor("6m");const[rangeKey,setRangeKey]=useState<RangeKey>("6m");const[startDate,setStartDate]=useState(initial.start);const[endDate,setEndDate]=useState(initial.end);const[summary,setSummary]=useState<Summary>(EMPTY);const[hidden,setHidden]=useState<WidgetId[]>(DEFAULT_HIDDEN);const[preferenceId,setPreferenceId]=useState<string|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[customizeOpen,setCustomizeOpen]=useState(false);const[savingPreference,setSavingPreference]=useState(false);const[expandedAccount,setExpandedAccount]=useState<"cash"|"bank"|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);const bucket=bucketFor(startDate,endDate);const{data,error:rpcError}=await supabase.rpc("dashboard_professional_analytics",{p_start_date:startDate,p_end_date:endDate,p_bucket:bucket});if(rpcError)setError(rpcError.message);else setSummary({...EMPTY,...((data||{}) as Partial<Summary>),trend:Array.isArray((data as any)?.trend)?(data as any).trend:[],cash_accounts:Array.isArray((data as any)?.cash_accounts)?(data as any).cash_accounts:[],bank_accounts:Array.isArray((data as any)?.bank_accounts)?(data as any).bank_accounts:[]});setLoading(false)},[startDate,endDate]);
 const loadPreferences=useCallback(async()=>{if(!companyId)return;let q=supabase.from("dashboard_widget_preferences").select("id,hidden_widgets").eq("company_id",companyId);q=businessUnitId?q.eq("business_unit_id",businessUnitId):q.is("business_unit_id",null);const{data,error:e}=await q.maybeSingle();if(e){setError(e.message);return}setPreferenceId(data?.id??null);setHidden(((data?.hidden_widgets??DEFAULT_HIDDEN) as string[]).filter((id):id is WidgetId=>WIDGETS.some(w=>w.id===id)))},[companyId,businessUnitId]);
 useEffect(()=>{void load()},[load,companyId,businessUnitId]);useEffect(()=>{void loadPreferences()},[loadPreferences]);useEffect(()=>{const t=window.setInterval(()=>void load(),60000);return()=>window.clearInterval(t)},[load]);
 const applyRange=(key:RangeKey)=>{setRangeKey(key);if(key!=="custom"){const r=rangeFor(key);setStartDate(r.start);setEndDate(r.end)}};
 const saveHidden=async(next:WidgetId[])=>{if(!companyId)return;setSavingPreference(true);const payload={hidden_widgets:next,updated_at:new Date().toISOString()};const r=preferenceId?await supabase.from("dashboard_widget_preferences").update(payload).eq("id",preferenceId).select("id").single():await supabase.from("dashboard_widget_preferences").insert({...payload,company_id:companyId,business_unit_id:businessUnitId}).select("id").single();setSavingPreference(false);if(r.error){setError(r.error.message);return}if(!preferenceId)setPreferenceId(r.data.id);setHidden(next)};
 const visible=(id:WidgetId)=>!hidden.includes(id);const toggle=(id:WidgetId)=>void saveHidden(hidden.includes(id)?hidden.filter(x=>x!==id):[...hidden,id]);
 const periodLabel=`${startDate} → ${endDate}`;const chartHas=(keys:(keyof TrendRow)[])=>summary.trend.some(r=>keys.some(k=>Number(r[k])!==0));
 const kpis=useMemo<Kpi[]>(()=>[
 {id:"sales",label:"Sales",value:money(summary.sales_total),note:`${summary.sales_documents} posted document(s) · ${periodLabel}`,icon:ShoppingCart,color:"bg-blue-600",to:"/sales"},{id:"purchases",label:"Purchases",value:money(summary.purchase_total),note:`${summary.purchase_documents} posted document(s) · ${periodLabel}`,icon:Banknote,color:"bg-amber-500",to:"/purchase"},{id:"receivables",label:"Receivables",value:money(summary.receivables),note:`Posted A/R balance as of ${endDate}`,icon:WalletCards,color:"bg-emerald-600",to:"/accounting/customer-invoice-statement"},{id:"payables",label:"Payables",value:money(summary.payables),note:`Posted A/P balance as of ${endDate}`,icon:Building2,color:"bg-violet-600",to:"/reports/supplier-aging"},{id:"cash",label:"Cash Balance",value:money(summary.cash_balance),note:`Mapped cash tree · as of ${endDate}`,icon:Banknote,color:"bg-cyan-600",to:"/accounting/cash-counter",expandable:"cash"},{id:"bank",label:"Bank Balance",value:money(summary.bank_balance),note:`Mapped bank tree · as of ${endDate}`,icon:Landmark,color:"bg-sky-700",to:"/accounting/bank-reconciliation",expandable:"bank"},{id:"inventory",label:"Inventory Value",value:money(summary.inventory_value),note:`${qty(summary.stock_quantity)} current stock quantity`,icon:Boxes,color:"bg-slate-700",to:"/reports/stock-valuation"}
 ],[summary,periodLabel,endDate]);
 const renderBreakdown=(kind:"cash"|"bank")=>{const rows=kind==="cash"?summary.cash_accounts:summary.bank_accounts;if(!rows.length)return <div className="mt-2 rounded-lg bg-slate-50 p-2 text-[10px] font-semibold text-slate-500">No mapped child accounts found.</div>;return <div className="mt-2 space-y-1 rounded-lg bg-slate-50 p-2">{rows.map(r=><div key={r.account_id} className="flex items-center justify-between gap-3 text-[10px]"><span className="min-w-0 truncate font-semibold text-slate-600">{r.code?`${r.code} · `:""}{r.name}</span><span className="shrink-0 font-black tabular-nums text-slate-900">{money(r.balance)}</span></div>)}</div>};
 return <div className="mx-auto max-w-[1600px] space-y-3 p-3 lg:p-4">
  <div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-lg font-black text-slate-950">Business Overview</h1><p className="mt-0.5 text-[11px] font-semibold text-slate-500">Posted accounting data with live operational indicators.</p></div><div className="relative flex items-center gap-2"><span className="hidden text-[10px] font-bold text-emerald-700 sm:inline">● Live{summary.as_of?` · ${new Date(summary.as_of).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}`:""}</span><button type="button" onClick={()=>setCustomizeOpen(v=>!v)} className="inline-flex h-8 items-center gap-2 rounded-md border border-slate-300 bg-white px-3 text-[10px] font-black text-slate-700 shadow-sm"><Settings2 className="h-3.5 w-3.5"/>Customize</button><button type="button" onClick={()=>void load()} disabled={loading} className="inline-flex h-8 items-center gap-2 rounded-md border border-slate-300 bg-white px-3 text-[10px] font-black text-slate-700 shadow-sm"><RefreshCw className={`h-3.5 w-3.5 ${loading?"animate-spin":""}`}/>Refresh</button>{customizeOpen&&<div className="absolute right-0 top-10 z-50 w-[310px] rounded-xl border border-slate-200 bg-white p-3 shadow-2xl"><div className="mb-2 flex items-center justify-between"><div className="text-xs font-black">Show / Hide Dashboard</div><button onClick={()=>setCustomizeOpen(false)} className="text-xs font-bold text-slate-500">Close</button></div><div className="max-h-[380px] space-y-1 overflow-auto">{WIDGETS.map(w=><button key={w.id} disabled={savingPreference} onClick={()=>toggle(w.id)} className="flex w-full items-center justify-between rounded-lg px-2 py-2 text-left text-xs font-semibold hover:bg-slate-50"><span>{w.label}</span>{visible(w.id)?<Eye className="h-4 w-4 text-emerald-600"/>:<EyeOff className="h-4 w-4 text-slate-400"/>}</button>)}</div><div className="mt-2 grid grid-cols-2 gap-2"><button disabled={savingPreference} onClick={()=>void saveHidden(DEFAULT_HIDDEN)} className="rounded-md border border-slate-200 px-3 py-2 text-xs font-bold">Recommended</button><button disabled={savingPreference} onClick={()=>void saveHidden([])} className="rounded-md border border-slate-200 px-3 py-2 text-xs font-bold text-blue-700">Show All</button></div></div>}</div></div>
  <div className="flex flex-wrap items-center gap-2 rounded-xl border border-slate-200 bg-white p-2 shadow-sm"><span className="px-1 text-[10px] font-black uppercase text-slate-400">Period</span>{([['today','Today'],['week','This Week'],['month','This Month'],['3m','3M'],['6m','6M'],['12m','12M'],['fy','This FY'],['custom','Custom']] as [RangeKey,string][]).map(([k,l])=><button key={k} onClick={()=>applyRange(k)} className={`rounded-md px-2.5 py-1.5 text-[10px] font-black ${rangeKey===k?'bg-slate-900 text-white':'border border-slate-200 bg-white text-slate-600'}`}>{l}</button>)}{rangeKey==="custom"&&<><input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} className="input h-8 text-xs"/><span className="text-xs text-slate-400">to</span><input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)} className="input h-8 text-xs"/></>}</div>
  {error&&<div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-xs font-semibold text-red-700">{error}</div>}
  <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">{kpis.filter(c=>visible(c.id)).map(c=>{const Icon=c.icon;const expanded=c.expandable&&expandedAccount===c.expandable;return <div key={c.id} className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><button onClick={()=>navigate(c.to)} className="w-full text-left"><div className="flex items-center gap-2"><span className={`flex h-8 w-8 items-center justify-center rounded-lg text-white ${c.color}`}><Icon className="h-4 w-4"/></span><div className="text-[10px] font-black uppercase tracking-wide text-slate-600">{c.label}</div></div><div className="mt-3 truncate text-lg font-black tabular-nums text-slate-950">{loading?'…':c.value}</div><div className="mt-1 text-[9px] font-semibold text-slate-400">{c.note}</div></button>{c.expandable&&<button onClick={()=>setExpandedAccount(expanded?null:c.expandable!)} className="mt-2 flex w-full items-center justify-between border-t border-slate-100 pt-2 text-[10px] font-black text-blue-700"><span>Account-wise breakdown</span>{expanded?<ChevronUp className="h-3.5 w-3.5"/>:<ChevronDown className="h-3.5 w-3.5"/>}</button>}{expanded&&renderBreakdown(c.expandable!)}</div>})}</div>
  {visible('sales_purchase')&&<Panel title={`Sales vs Purchase · ${periodLabel}`}>{chartHas(['sales','purchase'])?<div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={summary.trend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tickFormatter={v=>labelDate(v,summary.bucket)} tick={{fontSize:10}}/><YAxis tick={{fontSize:9}} tickFormatter={v=>Number(v)>=1000?`${Math.round(Number(v)/1000)}k`:String(v)}/><Tooltip labelFormatter={v=>labelDate(String(v),summary.bucket)} formatter={v=>money(Number(v))}/><Legend/><Bar dataKey="sales" name="Sales" fill="#2563eb" radius={[3,3,0,0]}/><Bar dataKey="purchase" name="Purchase" fill="#10b981" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div>:<EmptyChart message="No posted sales or purchase activity for the selected period."/>}</Panel>}
  {visible('cash_flow')&&<Panel title={`Cash In vs Cash Out · ${periodLabel}`} action={<span className="text-[9px] font-bold text-slate-400">POSTED TREASURY MOVEMENTS</span>}>{chartHas(['cash_in','cash_out'])?<div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={summary.trend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tickFormatter={v=>labelDate(v,summary.bucket)} tick={{fontSize:10}}/><YAxis tick={{fontSize:9}} tickFormatter={v=>Number(v)>=1000?`${Math.round(Number(v)/1000)}k`:String(v)}/><Tooltip labelFormatter={v=>labelDate(String(v),summary.bucket)} formatter={v=>money(Number(v))}/><Legend/><Bar dataKey="cash_in" name="Cash In" fill="#0f766e" radius={[3,3,0,0]}/><Bar dataKey="cash_out" name="Cash Out" fill="#f97316" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div>:<EmptyChart message="No posted cash/bank movement for the selected period."/>}</Panel>}
  {visible('profit')&&<Panel title={`Gross Profit & Margin · ${periodLabel}`} action={<button onClick={()=>navigate('/reports/sales-margin')} className="text-[9px] font-black text-blue-700">Open margin report</button>}>{chartHas(['gross_profit'])?<div className="h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={summary.trend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tickFormatter={v=>labelDate(v,summary.bucket)} tick={{fontSize:10}}/><YAxis tick={{fontSize:9}} tickFormatter={v=>Number(v)>=1000?`${Math.round(Number(v)/1000)}k`:String(v)}/><Tooltip labelFormatter={v=>labelDate(String(v),summary.bucket)} formatter={(v,n)=>n==='margin_percent'?`${Number(v).toFixed(2)}%`:money(Number(v))}/><Legend/><Line type="monotone" dataKey="gross_profit" name="Gross Profit" stroke="#7c3aed" strokeWidth={2}/></LineChart></ResponsiveContainer></div>:<EmptyChart message="No posted sales margin data for the selected period."/>}</Panel>}
  {visible('operations')&&<Panel title="Operations & Alerts" action={<span className="text-[9px] font-bold text-slate-400">LIVE CURRENT STATE</span>}><div className="grid gap-2 sm:grid-cols-3"><button onClick={()=>navigate('/godown')} className="rounded-lg bg-amber-50 p-3 text-left text-[10px] font-bold text-amber-950"><AlertTriangle className="mb-2 h-4 w-4 text-amber-600"/>{summary.stock_alerts} stock position(s) are at or below zero.</button><button onClick={()=>navigate('/production')} className="rounded-lg bg-blue-50 p-3 text-left text-[10px] font-bold text-blue-950"><Factory className="mb-2 h-4 w-4 text-blue-600"/>{summary.pending_work_orders} work order(s) pending.</button><button onClick={()=>navigate('/reports/stock-valuation')} className="rounded-lg bg-slate-50 p-3 text-left text-[10px] font-bold text-slate-950"><Boxes className="mb-2 h-4 w-4 text-slate-600"/>{qty(summary.stock_quantity)} current stock quantity.</button></div></Panel>}
 </div>
}
