import { FormEvent, useCallback, useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { toUrduName } from "@/lib/urdu";
import DataTable, { Column } from "@/components/DataTable";
import { ConfirmModal, ErrorBanner, Modal, PageHeader } from "@/components/ui";

type Category = { id:string; name:string; name_urdu:string|null; sub_category:string|null; description:string|null; created_at:string };
type CategoryForm = { name:string; name_urdu:string; sub_category:string; description:string };
const EMPTY_FORM:CategoryForm={name:"",name_urdu:"",sub_category:"",description:""};

export default function Categories(){
 const [rows,setRows]=useState<Category[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const [error,setError]=useState<string|null>(null),[modalOpen,setModalOpen]=useState(false),[editing,setEditing]=useState<Category|null>(null),[deleteId,setDeleteId]=useState<string|null>(null),[form,setForm]=useState<CategoryForm>(EMPTY_FORM);
 const fetchCategories=useCallback(async()=>{setLoading(true);const {data,error}=await supabase.from("categories").select("id,name,name_urdu,sub_category,description,created_at").order("name");if(error){setError(error.message);setRows([])}else{setError(null);setRows((data??[]) as Category[])}setLoading(false)},[]);
 useEffect(()=>{void fetchCategories()},[fetchCategories]);
 const openCreate=()=>{setEditing(null);setForm(EMPTY_FORM);setError(null);setModalOpen(true)};
 const openEdit=(r:Category)=>{setEditing(r);setForm({name:r.name,name_urdu:r.name_urdu??"",sub_category:r.sub_category??"",description:r.description??""});setError(null);setModalOpen(true)};
 const closeModal=()=>{if(saving)return;setModalOpen(false);setEditing(null);setForm(EMPTY_FORM)};
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const name=form.name.trim();if(!name){setError("Category name is required.");return}setSaving(true);setError(null);try{let q=supabase.from("categories").select("id").ilike("name",name).limit(1);if(editing)q=q.neq("id",editing.id);const d=await q;if(d.error)throw d.error;if((d.data??[]).length)throw new Error(`Category "${name}" already exists.`);const payload={name,name_urdu:form.name_urdu.trim()||toUrduName(name)||null,sub_category:form.sub_category.trim()||null,description:form.description.trim()||null};const r=editing?await supabase.from("categories").update(payload).eq("id",editing.id):await supabase.from("categories").insert(payload);if(r.error)throw r.error;setModalOpen(false);setEditing(null);setForm(EMPTY_FORM);await fetchCategories()}catch(x){setError(x instanceof Error?x.message:"Unable to save category.")}finally{setSaving(false)}};
 const del=async()=>{if(!deleteId)return;setSaving(true);const r=await supabase.from("categories").delete().eq("id",deleteId);if(r.error)setError(r.error.message);else{setDeleteId(null);await fetchCategories()}setSaving(false)};
 const columns:Column<Category>[]=[{key:"name",label:"Category Name",render:r=><div><div className="font-bold text-slate-900">{r.name}</div><div className="text-sm text-slate-500" dir="rtl">{r.name_urdu||"—"}</div></div>},{key:"sub_category",label:"Sub-Category",render:r=>r.sub_category||"—"},{key:"description",label:"Description",render:r=>r.description||"—"},{key:"actions",label:"",className:"text-right",render:r=><div className="flex justify-end gap-2"><button type="button" onClick={()=>openEdit(r)} className="text-sm font-medium text-primary-600">Edit</button><button type="button" onClick={()=>setDeleteId(r.id)} className="text-sm font-medium text-error-600">Delete</button></div>}];
 return <div><PageHeader title="Categories & Iqsaam / کیٹیگریز اور اقسام" subtitle="English name automatically creates an editable Urdu name" action={<button type="button" onClick={openCreate} className="btn-primary">+ Add Category</button>}/>{error&&<ErrorBanner message={error}/>}<DataTable columns={columns} rows={rows} loading={loading} emptyMessage="No categories found."/><Modal open={modalOpen} title={editing?"Edit Category":"New Category"} onClose={closeModal}><form onSubmit={submit} className="space-y-4"><div><label className="label">Category Name (English)</label><input className="input" required autoFocus value={form.name} onChange={e=>setForm(c=>({...c,name:e.target.value,name_urdu:(!c.name_urdu||c.name_urdu===toUrduName(c.name))?toUrduName(e.target.value):c.name_urdu}))}/></div><div><label className="label">Urdu Name / اردو نام</label><input className="input text-right" dir="rtl" value={form.name_urdu} onChange={e=>setForm(c=>({...c,name_urdu:e.target.value}))} placeholder="خودکار اردو نام — قابل ترمیم"/></div><div><label className="label">Sub-Category / ذیلی قسم</label><input className="input" value={form.sub_category} onChange={e=>setForm(c=>({...c,sub_category:e.target.value}))}/></div><div><label className="label">Description / تفصیل</label><input className="input" value={form.description} onChange={e=>setForm(c=>({...c,description:e.target.value}))}/></div><div className="flex justify-end gap-3"><button type="button" onClick={closeModal} disabled={saving} className="btn-secondary">Cancel</button><button type="submit" disabled={saving} className="btn-primary">{saving?"Saving...":editing?"Save Changes":"Create Category"}</button></div></form></Modal><ConfirmModal open={!!deleteId} title="Delete Category" message="Are you sure?" onConfirm={del} onCancel={()=>setDeleteId(null)}/></div>
}
