import { ChangeEvent, FormEvent, useCallback, useEffect, useRef, useState } from "react";
import * as XLSX from "xlsx";
import { Download, FileSpreadsheet, Upload } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { toUrduName } from "@/lib/urdu";
import DataTable, { Column } from "@/components/DataTable";
import { ConfirmModal, ErrorBanner, Modal, PageHeader } from "@/components/ui";

type Category = { id:string; name:string; name_urdu:string|null; description:string|null; created_at:string };
type CategoryForm = { name:string; name_urdu:string; description:string };
const EMPTY_FORM:CategoryForm={name:"",name_urdu:"",description:""};
const clean=(v:unknown)=>String(v??"").trim();

export default function Categories(){
 const [rows,setRows]=useState<Category[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const [error,setError]=useState<string|null>(null),[modalOpen,setModalOpen]=useState(false),[editing,setEditing]=useState<Category|null>(null),[deleteId,setDeleteId]=useState<string|null>(null),[form,setForm]=useState<CategoryForm>(EMPTY_FORM);
 const fileRef=useRef<HTMLInputElement|null>(null);
 const fetchCategories=useCallback(async()=>{setLoading(true);const {data,error}=await supabase.from("categories").select("id,name,name_urdu,description,created_at").order("name");if(error){setError(error.message);setRows([])}else{setError(null);setRows((data??[]) as Category[])}setLoading(false)},[]);
 useEffect(()=>{void fetchCategories()},[fetchCategories]);
 const openCreate=()=>{setEditing(null);setForm(EMPTY_FORM);setError(null);setModalOpen(true)};
 const openEdit=(r:Category)=>{setEditing(r);setForm({name:r.name,name_urdu:r.name_urdu??"",description:r.description??""});setError(null);setModalOpen(true)};
 const closeModal=()=>{if(saving)return;setModalOpen(false);setEditing(null);setForm(EMPTY_FORM)};
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const name=form.name.trim();if(!name){setError("Category name is required.");return}setSaving(true);setError(null);try{let q=supabase.from("categories").select("id").ilike("name",name).limit(1);if(editing)q=q.neq("id",editing.id);const d=await q;if(d.error)throw d.error;if((d.data??[]).length)throw new Error(`Category "${name}" already exists.`);const payload={name,name_urdu:form.name_urdu.trim()||toUrduName(name)||null,description:form.description.trim()||null};const r=editing?await supabase.from("categories").update(payload).eq("id",editing.id):await supabase.from("categories").insert(payload);if(r.error)throw r.error;setModalOpen(false);setEditing(null);setForm(EMPTY_FORM);window.dispatchEvent(new Event("navilo-master-data-changed"));await fetchCategories()}catch(x){setError(x instanceof Error?x.message:"Unable to save category.")}finally{setSaving(false)}};
 const del=async()=>{if(!deleteId)return;setSaving(true);const r=await supabase.from("categories").delete().eq("id",deleteId);if(r.error)setError(r.error.message);else{setDeleteId(null);window.dispatchEvent(new Event("navilo-master-data-changed"));await fetchCategories()}setSaving(false)};
 const exportExcel=()=>{const ws=XLSX.utils.json_to_sheet(rows.map(r=>({"Category Name":r.name,"Urdu Name":r.name_urdu??"",Description:r.description??""})));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Categories");XLSX.writeFile(wb,"categories.xlsx")};
 const downloadTemplate=()=>{const ws=XLSX.utils.json_to_sheet([{"Category Name":"Steel Products","Urdu Name":"اسٹیل مصنوعات",Description:"Optional description"}]);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Categories");XLSX.writeFile(wb,"category_import_template.xlsx")};
 const importExcel=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;setSaving(true);setError(null);try{const wb=XLSX.read(await file.arrayBuffer(),{type:"array"});const sheet=wb.Sheets[wb.SheetNames[0]];const raw=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:""});const existing=new Set(rows.map(r=>r.name.trim().toLowerCase()));const seen=new Set<string>();const payload:{name:string;name_urdu:string|null;description:string|null}[]=[];const errors:string[]=[];raw.forEach((r,i)=>{const name=clean(r["Category Name"]??r["Name"]??r["name"]);const name_urdu=clean(r["Urdu Name"]??r["name_urdu"]);const description=clean(r["Description"]??r["description"]);if(!name){if(Object.values(r).some(v=>clean(v)))errors.push(`Row ${i+2}: Category Name is required.`);return}const key=name.toLowerCase();if(existing.has(key)||seen.has(key)){errors.push(`Row ${i+2}: Duplicate category "${name}".`);return}seen.add(key);payload.push({name,name_urdu:name_urdu||toUrduName(name)||null,description:description||null})});if(errors.length)throw new Error(errors.slice(0,6).join(" "));if(!payload.length)throw new Error("No valid category rows found in the file.");const {error}=await supabase.from("categories").insert(payload);if(error)throw error;window.dispatchEvent(new Event("navilo-master-data-changed"));await fetchCategories()}catch(x){setError(x instanceof Error?x.message:"Category import failed.")}finally{setSaving(false);if(fileRef.current)fileRef.current.value=""}};
 const columns:Column<Category>[]=[{key:"name",label:"Category Name",render:r=><div><div className="font-bold text-slate-900">{r.name}</div><div className="text-sm text-slate-500" dir="rtl">{r.name_urdu||"—"}</div></div>},{key:"description",label:"Description",render:r=>r.description||"—"},{key:"actions",label:"",className:"text-right",render:r=><div className="flex justify-end gap-2"><button type="button" onClick={()=>openEdit(r)} className="text-sm font-medium text-primary-600">Edit</button><button type="button" onClick={()=>setDeleteId(r.id)} className="text-sm font-medium text-error-600">Delete</button></div>}];
 const actions=<div className="flex flex-wrap gap-2"><button type="button" onClick={downloadTemplate} className="btn-secondary"><Download className="h-4 w-4"/>Template</button><button type="button" onClick={()=>fileRef.current?.click()} disabled={saving} className="btn-secondary"><Upload className="h-4 w-4"/>Import</button><button type="button" onClick={exportExcel} className="btn-secondary"><FileSpreadsheet className="h-4 w-4"/>Excel</button><button type="button" onClick={openCreate} className="btn-primary">+ Add Category</button><input ref={fileRef} hidden type="file" accept=".xlsx,.xls,.csv" onChange={importExcel}/></div>;
 return <div><PageHeader title="Categories / کیٹیگریز" subtitle="English name automatically creates an editable Urdu name" action={actions}/>{error&&<ErrorBanner message={error}/>}<DataTable columns={columns} rows={rows} loading={loading} emptyMessage="No categories found."/><Modal open={modalOpen} title={editing?"Edit Category":"New Category"} onClose={closeModal}><form onSubmit={submit} className="space-y-4"><div><label className="label">Category Name (English)</label><input className="input" required autoFocus value={form.name} onChange={e=>setForm(c=>({...c,name:e.target.value,name_urdu:(!c.name_urdu||c.name_urdu===toUrduName(c.name))?toUrduName(e.target.value):c.name_urdu}))}/></div><div><div className="flex items-center justify-between"><label className="label">Urdu Name / اردو نام</label><button type="button" className="text-xs font-semibold text-primary-600" onClick={()=>setForm(c=>({...c,name_urdu:toUrduName(c.name)}))}>Auto Urdu</button></div><input className="input text-right" dir="rtl" value={form.name_urdu} onChange={e=>setForm(c=>({...c,name_urdu:e.target.value}))} placeholder="خودکار اردو نام — قابل ترمیم"/></div><div><label className="label">Description / تفصیل</label><input className="input" value={form.description} onChange={e=>setForm(c=>({...c,description:e.target.value}))}/></div><div className="flex justify-end gap-3"><button type="button" onClick={closeModal} disabled={saving} className="btn-secondary">Cancel</button><button type="submit" disabled={saving} className="btn-primary">{saving?"Saving...":editing?"Save Changes":"Create Category"}</button></div></form></Modal><ConfirmModal open={!!deleteId} title="Delete Category" message="Are you sure?" onConfirm={del} onCancel={()=>setDeleteId(null)}/></div>
}
