import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, LockKeyhole, Printer } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { ErrorBanner, LoadingState, PageHeader, formatDate } from "@/components/ui";

interface Period { id:string; period_name:string; period_start:string; period_end:string; status:"open"|"closed"; }
interface Account { id:string; code:string; name:string; type:"revenue"|"expense"|string; }
interface Ledger { account_id:string; debit:number; credit:number; }
interface Closure { id:string; fiscal_year:number; year_start:string; year_end:string; status:string; net_profit_loss:number; closing_journal_id:string|null; closed_at:string|null; retained?:Account|null; }
const money=(n:number)=>new Intl.NumberFormat("en-PK",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0);

export default function FiscalYearClosing(){
  const [year,setYear]=useState(new Date().getFullYear()-1); const [periods,setPeriods]=useState<Period[]>([]); const [accounts,setAccounts]=useState<Account[]>([]); const [ledgers,setLedgers]=useState<Ledger[]>([]); const [closures,setClosures]=useState<Closure[]>([]);
  const [draftCount,setDraftCount]=useState(0); const [retainedReady,setRetainedReady]=useState(false); const [loading,setLoading]=useState(true); const [closing,setClosing]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState("");
  const start=`${year}-01-01`,end=`${year}-12-31`;
  const load=useCallback(async()=>{setLoading(true);setError("");const [p,a,l,c,d,m]=await Promise.all([
    supabase.from("accounting_periods").select("id,period_name,period_start,period_end,status").gte("period_start",start).lte("period_end",end).order("period_start"),
    supabase.from("chart_of_accounts").select("id,code,name,type").in("type",["revenue","expense"]).order("code"),
    supabase.from("ledgers").select("account_id,debit,credit").gte("entry_date",start).lte("entry_date",end),
    supabase.from("fiscal_year_closures").select("id,fiscal_year,year_start,year_end,status,net_profit_loss,closing_journal_id,closed_at,retained:chart_of_accounts!retained_earnings_account_id(id,code,name,type)").order("fiscal_year",{ascending:false}),
    supabase.from("journal_entries").select("id",{count:"exact",head:true}).eq("status","draft").gte("entry_date",start).lte("entry_date",end),
    supabase.from("account_mappings").select("account_id,account:chart_of_accounts(type,is_active,is_group)").eq("mapping_key","retained_earnings").maybeSingle(),
  ]);const problem=p.error||a.error||l.error||c.error||d.error||m.error;if(problem)setError(problem.message);setPeriods((p.data??[]) as Period[]);setAccounts((a.data??[]) as Account[]);setLedgers((l.data??[]) as Ledger[]);setClosures((c.data??[]).map((row:any)=>({...row,retained:Array.isArray(row.retained)?row.retained[0]??null:row.retained??null})) as Closure[]);setDraftCount(d.count??0);const mapped:any=m.data;const mappedAccount=Array.isArray(mapped?.account)?mapped.account[0]:mapped?.account;setRetainedReady(!!mapped?.account_id&&mappedAccount?.type==="equity"&&mappedAccount?.is_active&&!mappedAccount?.is_group);setLoading(false);},[start,end]);
  useEffect(()=>{void load();},[load]);
  const preview=useMemo(()=>accounts.map(account=>{const net=ledgers.filter(l=>l.account_id===account.id).reduce((s,l)=>s+(account.type==="revenue"?Number(l.credit)-Number(l.debit):Number(l.debit)-Number(l.credit)),0);return {...account,balance:net};}).filter(a=>Math.abs(a.balance)>=.005),[accounts,ledgers]);
  const revenue=preview.filter(a=>a.type==="revenue").reduce((s,a)=>s+a.balance,0);const expense=preview.filter(a=>a.type==="expense").reduce((s,a)=>s+a.balance,0);const net=revenue-expense;
  const allMonthsClosed=periods.length===12&&periods.every(p=>p.status==="closed");const alreadyClosed=closures.some(c=>c.fiscal_year===year);const ready=allMonthsClosed&&draftCount===0&&retainedReady&&!alreadyClosed;
  async function closeYear(){if(!window.confirm(`Permanently close financial year ${year}? All revenue and expense balances will transfer to Retained Earnings.`))return;setClosing(true);setError("");setSuccess("");const{data,error:e}=await supabase.rpc("close_fiscal_year",{p_fiscal_year:year});if(e)setError(e.message);else{setSuccess(`Financial year ${year} closed. ${Number(data.net_profit_loss)>=0?"Profit":"Loss"}: ${money(Math.abs(Number(data.net_profit_loss)))}`);await load();}setClosing(false);}
  function printClosure(c:Closure){const popup=window.open("","_blank","width=900,height=700");if(!popup)return;popup.document.write(`<html><head><title>Year End ${c.fiscal_year}</title><style>body{font:14px Arial;padding:40px;color:#172033}header{display:flex;justify-content:space-between;border-bottom:2px solid #173a5e;padding-bottom:18px}h1{color:#173a5e;margin:0}table{width:100%;border-collapse:collapse;margin-top:25px}td{padding:10px;border-bottom:1px solid #ddd}td:last-child{text-align:right;font-weight:bold}.ok{color:#087f5b}@media print{button{display:none}}</style></head><body><header><div><h1>FINANCIAL YEAR CLOSING</h1><div>MetalForge OS</div></div><div><b>${c.fiscal_year}</b><br>${formatDate(c.year_start)} – ${formatDate(c.year_end)}</div></header><table><tr><td>Status</td><td class="ok">${c.status.toUpperCase()}</td></tr><tr><td>Net Profit / (Loss)</td><td>${money(c.net_profit_loss)}</td></tr><tr><td>Retained Earnings Account</td><td>${c.retained?.code??""} — ${c.retained?.name??""}</td></tr><tr><td>Closing Journal</td><td>${c.closing_journal_id?`YEC-${c.fiscal_year}`:"No activity"}</td></tr><tr><td>Closed At</td><td>${c.closed_at?new Date(c.closed_at).toLocaleString():"—"}</td></tr><tr><td>Next-year opening snapshot</td><td>${c.fiscal_year+1}</td></tr></table><script>window.onload=()=>window.print()</script></body></html>`);popup.document.close();}
  if(loading)return <LoadingState/>;
  return <div><PageHeader title="Financial Year Closing / سالانہ اختتام" subtitle="Validate, transfer Profit & Loss balances to Retained Earnings, and permanently lock the financial year."/>{error&&<ErrorBanner message={error}/>} {success&&<div className="mb-4 rounded-lg bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{success}</div>}
    <div className="card mb-5 p-5"><div className="flex flex-wrap items-end justify-between gap-4"><label className="text-sm font-medium">Financial year<input className="input mt-1 block w-32" type="number" min="2000" max="2200" value={year} onChange={e=>setYear(Number(e.target.value))}/></label><button className="btn btn-primary" disabled={!ready||closing} onClick={closeYear}><LockKeyhole size={16}/>{closing?"Closing...":`Close ${year}`}</button></div><div className="mt-5 grid gap-3 md:grid-cols-4"><Check label="12 monthly periods closed" ok={allMonthsClosed} detail={`${periods.filter(p=>p.status==="closed").length}/12 closed`}/><Check label="No draft journals" ok={draftCount===0} detail={`${draftCount} drafts`}/><Check label="Retained Earnings mapping" ok={retainedReady} detail={retainedReady?"Ready":"Missing/invalid"}/><Check label="Not previously closed" ok={!alreadyClosed} detail={alreadyClosed?"Already closed":"Ready"}/></div></div>
    <div className="grid gap-5 lg:grid-cols-[1fr_340px]"><div className="card overflow-hidden"><div className="border-b px-5 py-3 font-semibold">Closing Preview</div><div className="overflow-x-auto"><table className="table"><thead><tr><th>Account</th><th>Type</th><th className="text-right">Balance to Close</th></tr></thead><tbody>{preview.length?preview.map(a=><tr key={a.id}><td>{a.code} — {a.name}</td><td>{a.type}</td><td className="text-right">{money(a.balance)}</td></tr>):<tr><td colSpan={3} className="py-8 text-center text-slate-500">No Profit & Loss activity for this year.</td></tr>}</tbody></table></div></div><div className="card p-5"><h3 className="mb-4 font-semibold">Year Result</h3><Summary label="Revenue" value={revenue}/><Summary label="Expenses" value={expense}/><div className="mt-3 border-t pt-3"><Summary label={net>=0?"Net Profit":"Net Loss"} value={Math.abs(net)} strong/></div><p className="mt-4 text-xs text-slate-500">The server recalculates all figures during closing; this preview cannot override accounting data.</p></div></div>
    <div className="card mt-5 overflow-hidden"><div className="border-b px-5 py-3 font-semibold">Closed Financial Years</div><div className="overflow-x-auto"><table className="table"><thead><tr><th>Year</th><th>Status</th><th>Retained Earnings</th><th className="text-right">Profit / (Loss)</th><th>Closing Journal</th><th></th></tr></thead><tbody>{closures.length?closures.map(c=><tr key={c.id}><td className="font-medium">{c.fiscal_year}</td><td><span className="badge badge-success">{c.status}</span></td><td>{c.retained?.code} — {c.retained?.name}</td><td className="text-right">{money(c.net_profit_loss)}</td><td>{c.closing_journal_id?`YEC-${c.fiscal_year}`:"No activity"}</td><td><button className="btn btn-secondary" onClick={()=>printClosure(c)}><Printer size={15}/>Print</button></td></tr>):<tr><td colSpan={6} className="py-8 text-center text-slate-500">No closed financial years.</td></tr>}</tbody></table></div></div>
  </div>;
}
function Check({label,ok,detail}:{label:string;ok:boolean;detail:string}){return <div className={`rounded-lg border p-3 ${ok?"border-emerald-200 bg-emerald-50":"border-amber-200 bg-amber-50"}`}><div className="flex items-center gap-2 text-sm font-medium"><CheckCircle2 size={16} className={ok?"text-emerald-600":"text-amber-600"}/>{label}</div><div className="mt-1 text-xs text-slate-600">{detail}</div></div>}
function Summary({label,value,strong=false}:{label:string;value:number;strong?:boolean}){return <div className={`flex justify-between py-1 ${strong?"text-lg font-bold":"text-sm"}`}><span>{label}</span><span>{money(value)}</span></div>}
