import SearchableSelect from "@/components/SearchableSelect";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, FileDown, Loader2, Printer, RefreshCw, Search } from "lucide-react";
import jsPDF from "jspdf";
import { supabase } from "@/lib/supabase";

type TransactionType = "salary_payment" | "expense_payment" | "loan_received" | "loan_repayment" | "capital_received" | "drawings_payment" | "other_receipt" | "other_payment";
type Account = { id:string; code:string; name:string; type:"asset"|"liability"|"equity"|"revenue"|"expense"; account_role?:string|null; detail_type?:string|null; is_group?:boolean|null; is_active?:boolean|null; allow_manual_entries?:boolean|null };
type Employee = { id:string; employee_code?:string|null; name:string; phone?:string|null; designation?:string|null; department?:string|null };
type PartySuggestion = { id:string; name:string; source:string };
type Voucher = { id:string; entry_no:string; entry_date:string; description:string; party_name?:string|null; payment_mode?:string|null };
type PostedVoucher = { entryNo:string; date:string; transactionType:string; counterAccount:string; cashBankAccount:string; amount:number; partyName:string; reference:string; notes:string };

const CONTROLLED_MAPPING_KEYS = new Set(["accounts_receivable","accounts_payable","inventory","input_vat","output_vat","cogs","cash","bank"]);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const money=(v:number)=>new Intl.NumberFormat("en-PK",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0));
const TYPES=[
 {value:"salary_payment",label:"Salary Payment",partyLabel:"Employee"},{value:"expense_payment",label:"Expense Payment",partyLabel:"Paid To"},{value:"loan_received",label:"Loan Received",partyLabel:"Lender"},{value:"loan_repayment",label:"Loan Repayment",partyLabel:"Lender"},{value:"capital_received",label:"Capital Received",partyLabel:"Owner"},{value:"drawings_payment",label:"Owner Drawings",partyLabel:"Owner"},{value:"other_receipt",label:"Other Receipt",partyLabel:"Received From"},{value:"other_payment",label:"Other Payment",partyLabel:"Paid To"},
] as const;
const isCashBank=(a:Account)=>a.type==="asset"&&(a.detail_type==="Cash on Hand"||a.detail_type==="Bank Account"||a.account_role==="cash"||a.account_role==="bank");

export default function GeneralCashBankPanel(){
 const [accounts,setAccounts]=useState<Account[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[expensePayees,setExpensePayees]=useState<PartySuggestion[]>([]),[mappedIds,setMappedIds]=useState<Record<string,string>>({}),[history,setHistory]=useState<Voucher[]>([]);
 const [transactionType,setTransactionType]=useState<TransactionType>("salary_payment"),[transactionDate,setTransactionDate]=useState(today()),[counterAccountId,setCounterAccountId]=useState(""),[cashBankAccountId,setCashBankAccountId]=useState(""),[partyName,setPartyName]=useState(""),[amount,setAmount]=useState(""),[reference,setReference]=useState(""),[notes,setNotes]=useState(""),[search,setSearch]=useState("");
 const [employeeSearch,setEmployeeSearch]=useState(""),[showEmployeeResults,setShowEmployeeResults]=useState(false),[showPartyResults,setShowPartyResults]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[success,setSuccess]=useState<string|null>(null),[lastVoucher,setLastVoucher]=useState<PostedVoucher|null>(null);
 const selectedType=TYPES.find(x=>x.value===transactionType)||TYPES[0];
 const cashBankAccounts=useMemo(()=>accounts.filter(isCashBank),[accounts]);
 const counterAccounts=useMemo(()=>{const controlled=new Set(Object.entries(mappedIds).filter(([k])=>CONTROLLED_MAPPING_KEYS.has(k)).map(([,id])=>id));return accounts.filter(a=>{if(isCashBank(a))return false;const d=String(a.detail_type||"").toLowerCase(),n=a.name.toLowerCase();if(transactionType==="salary_payment")return a.type==="expense"&&(a.id===mappedIds.salary_expense||d==="salaries"||n.includes("salary"));if(transactionType==="expense_payment")return a.type==="expense"&&a.id!==mappedIds.salary_expense&&a.id!==mappedIds.cogs&&!d.includes("cost of goods")&&d!=="cogs"&&d!=="salaries"&&!n.includes("cost of goods sold")&&!n.includes("salary");if(transactionType==="loan_received"||transactionType==="loan_repayment")return a.type==="liability"&&a.id!==mappedIds.accounts_payable&&a.id!==mappedIds.output_vat&&d!=="accounts payable"&&d!=="output vat";if(transactionType==="capital_received")return a.type==="equity"&&!d.includes("retained")&&!d.includes("draw")&&!n.includes("retained earnings")&&!n.includes("draw");if(transactionType==="drawings_payment")return a.type==="equity"&&(d.includes("draw")||n.includes("draw"));if(transactionType==="other_receipt")return !controlled.has(a.id)&&!d.includes("retained")&&(a.type==="revenue"||a.type==="liability"||a.type==="equity");if(transactionType==="other_payment")return !controlled.has(a.id)&&!d.includes("retained")&&(a.type==="expense"||a.type==="asset"||a.type==="liability"||a.type==="equity");return false})},[accounts,mappedIds,transactionType]);
 const filteredEmployees=useMemo(()=>employees.filter(e=>!employeeSearch.trim()||`${e.name} ${e.employee_code||""} ${e.designation||""}`.toLowerCase().includes(employeeSearch.toLowerCase())).slice(0,12),[employees,employeeSearch]);
 const filteredPayees=useMemo(()=>expensePayees.filter(p=>!partyName.trim()||`${p.name} ${p.source}`.toLowerCase().includes(partyName.toLowerCase())).slice(0,12),[expensePayees,partyName]);
 const filteredHistory=useMemo(()=>history.filter(r=>!search.trim()||[r.entry_no,r.entry_date,r.party_name,r.description].join(" ").toLowerCase().includes(search.toLowerCase())),[history,search]);
 const load=useCallback(async()=>{setLoading(true);try{const [ar,er,tr,mr,hr]=await Promise.all([supabase.from("chart_of_accounts").select("id,code,name,type,account_role,detail_type,is_group,is_active,allow_manual_entries").eq("is_active",true).eq("is_group",false).eq("allow_manual_entries",true).order("code"),supabase.from("employees").select("id,employee_code,name,phone,designation,department").eq("is_active",true).order("name"),supabase.from("transporters").select("id,name").order("name"),supabase.from("account_mappings").select("mapping_key,account_id"),supabase.from("journal_entries").select("id,entry_no,entry_date,description,party_name,payment_mode").eq("status","posted").eq("trans_type","General Cash/Bank").order("entry_date",{ascending:false}).limit(100)]);if(ar.error)throw ar.error;if(er.error)throw er.error;if(hr.error)throw hr.error;setAccounts((ar.data||[]) as Account[]);setEmployees((er.data||[]) as Employee[]);const m:Record<string,string>={};(mr.data||[]).forEach((r:any)=>{if(r.mapping_key&&r.account_id)m[r.mapping_key]=r.account_id});setMappedIds(m);setExpensePayees((tr.data||[]).map((r:any)=>({id:r.id,name:r.name,source:"Transporter"})));setHistory((hr.data||[]) as Voucher[]);const first=(ar.data||[]).find((a:any)=>isCashBank(a));if(first)setCashBankAccountId(x=>x||first.id)}catch(e:any){setError(e.message||"Failed to load general transactions.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{setCounterAccountId("");setPartyName("");setEmployeeSearch("");setShowPartyResults(false)},[transactionType]);
 const post=async()=>{setSaving(true);setError(null);setSuccess(null);try{const v=Number(amount);if(!transactionDate||!counterAccountId||!cashBankAccountId||!Number.isFinite(v)||v<=0)throw new Error("Complete all required transaction fields.");if(transactionType==="salary_payment"&&!partyName.trim())throw new Error("Select an employee.");if(transactionType==="expense_payment"&&!partyName.trim())throw new Error("Paid To is required.");const {data,e}=await supabase.rpc("post_general_cash_bank_transaction",{p_transaction_type:transactionType,p_transaction_date:transactionDate,p_counter_account_id:counterAccountId,p_cash_bank_account_id:cashBankAccountId,p_amount:v,p_party_name:partyName.trim()||null,p_reference:reference.trim()||null,p_notes:notes.trim()||null} as any) as any;if(e)throw e;const counter=accounts.find(a=>a.id===counterAccountId),cash=accounts.find(a=>a.id===cashBankAccountId);setLastVoucher({entryNo:String(data||"Posted"),date:transactionDate,transactionType:selectedType.label,counterAccount:counter?.name||"",cashBankAccount:cash?.name||"",amount:v,partyName:partyName.trim(),reference:reference.trim(),notes:notes.trim()});setSuccess(`Transaction posted: ${data}`);setAmount("");setReference("");setNotes("");setPartyName("");setCounterAccountId("");await load()}catch(e:any){setError(e.message||"Failed to post transaction.")}finally{setSaving(false)}};
 const printVoucher=(v:PostedVoucher)=>{const w=window.open("","_blank","width=820,height=900");if(!w)return;w.document.write(`<html><head><title>${v.entryNo}</title><style>body{font-family:Arial;padding:40px;color:#111}h1{text-align:center}.row{display:flex;justify-content:space-between;border-bottom:1px solid #ddd;padding:10px 0}.sig{display:flex;justify-content:space-between;margin-top:70px}</style></head><body><h1>GENERAL CASH / BANK VOUCHER</h1><div class="row"><b>Voucher</b><span>${v.entryNo}</span></div><div class="row"><b>Date</b><span>${v.date}</span></div><div class="row"><b>Type</b><span>${v.transactionType}</span></div><div class="row"><b>${selectedType.partyLabel}</b><span>${v.partyName||"-"}</span></div><div class="row"><b>Transaction Account</b><span>${v.counterAccount}</span></div><div class="row"><b>Cash / Bank</b><span>${v.cashBankAccount}</span></div><div class="row"><b>Amount</b><span>Rs. ${money(v.amount)}</span></div><div class="row"><b>Reference</b><span>${v.reference||"-"}</span></div><div class="row"><b>Notes</b><span>${v.notes||"-"}</span></div><div class="sig"><span>Prepared By __________</span><span>Approved By __________</span><span>Received By __________</span></div><script>window.onload=()=>window.print()</script></body></html>`);w.document.close()};
 const pdf=(v:PostedVoucher)=>{const d=new jsPDF();d.setFontSize(16);d.text("GENERAL CASH / BANK VOUCHER",105,18,{align:"center"});d.setFontSize(10);[["Voucher",v.entryNo],["Date",v.date],["Type",v.transactionType],[selectedType.partyLabel,v.partyName||"-"],["Transaction Account",v.counterAccount],["Cash / Bank",v.cashBankAccount],["Amount",`Rs. ${money(v.amount)}`],["Reference",v.reference||"-"],["Notes",v.notes||"-"]].forEach((r,i)=>{d.text(String(r[0]),18,34+i*10);d.text(String(r[1]),72,34+i*10)});d.save(`${v.entryNo}.pdf`)};
 return <div className="space-y-5"><div className="rounded-xl border bg-white"><div className="border-b p-5"><h2 className="text-xl font-bold">General Cash</h2><p className="text-slate-500">Salary, expenses, loans, capital and other receipts/payments with automatic accounting.</p></div><div className="grid gap-4 p-5 md:grid-cols-2">
 <label className="font-semibold">Transaction Type<select className="mt-2 w-full rounded-lg border p-3" value={transactionType} onChange={e=>setTransactionType(e.target.value as TransactionType)}>{TYPES.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select></label><label className="font-semibold">Date<input className="mt-2 w-full rounded-lg border p-3" type="date" value={transactionDate} onChange={e=>setTransactionDate(e.target.value)}/></label>
 <div className="relative"><label className="font-semibold">{selectedType.partyLabel}</label>{transactionType==="salary_payment"?<><input className="mt-2 w-full rounded-lg border p-3" placeholder="Search employee" value={employeeSearch} onFocus={()=>setShowEmployeeResults(true)} onChange={e=>{setEmployeeSearch(e.target.value);setPartyName(e.target.value);setShowEmployeeResults(true)}}/>{showEmployeeResults&&<div className="absolute z-30 mt-1 max-h-56 w-full overflow-auto rounded-lg border bg-white shadow">{filteredEmployees.map(e=><button type="button" className="block w-full p-3 text-left hover:bg-slate-50" key={e.id} onClick={()=>{setPartyName(e.name);setEmployeeSearch(e.name);setShowEmployeeResults(false)}}>{e.name}</button>)}</div>}</>:transactionType==="expense_payment"?<><input className="mt-2 w-full rounded-lg border p-3" placeholder="Search payee or type a name" value={partyName} onFocus={()=>setShowPartyResults(true)} onChange={e=>{setPartyName(e.target.value);setShowPartyResults(true)}}/>{showPartyResults&&filteredPayees.length>0&&<div className="absolute z-30 mt-1 w-full rounded-lg border bg-white shadow">{filteredPayees.map(p=><button type="button" className="block w-full p-3 text-left" key={p.id} onClick={()=>{setPartyName(p.name);setShowPartyResults(false)}}>{p.name} <span className="text-xs text-slate-400">{p.source}</span></button>)}</div>}</>:<input className="mt-2 w-full rounded-lg border p-3" placeholder="Name" value={partyName} onChange={e=>setPartyName(e.target.value)}/>}</div>
 <div><label className="font-semibold">Transaction Account</label><div className="mt-2"><SearchableSelect value={counterAccountId} onChange={e=>setCounterAccountId(e.target.value)} searchPlaceholder="Type to search account..."><option value="">Select account...</option>{counterAccounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</SearchableSelect></div></div><div><label className="font-semibold">Cash / Bank</label><div className="mt-2"><SearchableSelect value={cashBankAccountId} onChange={e=>setCashBankAccountId(e.target.value)} searchPlaceholder="Type to search account..."><option value="">Select cash/bank...</option>{cashBankAccounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</SearchableSelect></div></div><label className="font-semibold">Amount<input className="mt-2 w-full rounded-lg border p-3" type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="font-semibold">Reference<input className="mt-2 w-full rounded-lg border p-3" value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="font-semibold md:col-span-2">Notes<textarea className="mt-2 w-full rounded-lg border p-3" value={notes} onChange={e=>setNotes(e.target.value)}/></label>
 {error&&<div className="md:col-span-2 rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}{success&&<div className="md:col-span-2 rounded-lg bg-emerald-50 p-3 text-emerald-700">{success}</div>}<button type="button" onClick={post} disabled={saving||loading} className="md:col-span-2 rounded-lg bg-blue-600 p-3 font-semibold text-white disabled:opacity-50">{saving?<Loader2 className="mx-auto animate-spin"/>:<><CheckCircle2 className="mr-2 inline h-5 w-5"/>Post Transaction</>}</button>{lastVoucher&&<div className="md:col-span-2 flex gap-2"><button type="button" onClick={()=>printVoucher(lastVoucher)} className="rounded-lg border px-4 py-2"><Printer className="mr-2 inline h-4 w-4"/>Print Voucher</button><button type="button" onClick={()=>pdf(lastVoucher)} className="rounded-lg border px-4 py-2"><FileDown className="mr-2 inline h-4 w-4"/>PDF</button></div>}
 </div></div><div className="rounded-xl border bg-white p-5"><div className="mb-4 flex items-center justify-between"><div><h3 className="text-lg font-bold">General Transaction History</h3><p className="text-sm text-slate-500">Search posted vouchers.</p></div><button onClick={load} className="rounded-lg border p-2"><RefreshCw className="h-4 w-4"/></button></div><div className="relative mb-3"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input className="w-full rounded-lg border py-2 pl-9 pr-3" placeholder="Search voucher, name, date..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Voucher</th><th className="p-2">Date</th><th className="p-2">Description</th><th className="p-2">Party</th></tr></thead><tbody>{filteredHistory.map(r=><tr className="border-b" key={r.id}><td className="p-2">{r.entry_no}</td><td className="p-2">{r.entry_date}</td><td className="p-2">{r.description}</td><td className="p-2">{r.party_name||"-"}</td></tr>)}</tbody></table></div></div></div>
}