import { useCallback, useEffect, useMemo, useState } from "react";
import { FileDown, Printer, RefreshCw } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { exportMatrixToCSV, exportMatrixToExcel, exportMatrixToWord } from "@/lib/exportUtils";

const money=(v:number)=>new Intl.NumberFormat("en-PK",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0));
const monthNow=()=>new Date().toISOString().slice(0,7);
type Employee={id:string;employee_code?:string|null;name:string;designation?:string|null;department?:string|null};
type Row={employee_id:string;employee_code?:string|null;employee_name:string;designation?:string|null;department?:string|null;salary_month:string;entry_date:string;document_no:string;entry_type:string;debit:number;credit:number;journal_entry_id:string;balance?:number};

export default function PayrollLedger(){
 const [employees,setEmployees]=useState<Employee[]>([]),[rows,setRows]=useState<Row[]>([]),[employeeId,setEmployeeId]=useState(""),[month,setMonth]=useState(monthNow()),[showBalances,setShowBalances]=useState(true),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);const [e,l]=await Promise.all([supabase.from("employees").select("id,employee_code,name,designation,department").eq("is_active",true).order("name"),supabase.from("employee_salary_ledger").select("*").order("entry_date",{ascending:true}).order("document_no",{ascending:true})]);if(e.error||l.error)setError(e.error?.message||l.error?.message||"Failed to load payroll ledger.");setEmployees((e.data||[]) as Employee[]);setRows(((l.data||[]) as Row[]).map(r=>({...r,debit:Number(r.debit||0),credit:Number(r.credit||0)})));setLoading(false)},[]);
 useEffect(()=>{void load()},[load]);
 const filtered=useMemo(()=>{let bal=0;return rows.filter(r=>(!employeeId||r.employee_id===employeeId)&&(!month||String(r.salary_month).slice(0,7)===month)).map(r=>{bal+=Number(r.debit||0)-Number(r.credit||0);return {...r,balance:bal}})},[rows,employeeId,month]);
 const totals=useMemo(()=>filtered.reduce((a,r)=>({debit:a.debit+r.debit,credit:a.credit+r.credit}),{debit:0,credit:0}),[filtered]);
 const selected=employees.find(e=>e.id===employeeId);
 const matrix=()=>[["Employee","Code","Salary Month","Date","Document","Type","Accrued","Paid",...(showBalances?["Balance"]:[])],...filtered.map(r=>[r.employee_name,r.employee_code||"",String(r.salary_month).slice(0,7),r.entry_date,r.document_no,r.entry_type,r.debit,r.credit,...(showBalances?[r.balance||0]:[])])];
 const accrue=async()=>{if(!employeeId||!month){setError("Select employee and salary month.");return}setError(null);setMessage(null);const {data,error:e}=await supabase.rpc("accrue_employee_salary",{p_employee_id:employeeId,p_salary_month:`${month}-01`} as any);if(e){setError(e.message);return}setMessage((data as any)?.already_accrued?"Salary already accrued for this month.":`Salary accrued: ${(data as any)?.entry_no||"posted"}`);await load()};
 const printSlip=(r:Row)=>{const before=(r.balance||0)+r.credit-r.debit;const after=r.balance||0;const w=window.open("","_blank","width=820,height=900");if(!w)return;w.document.write(`<html><head><title>${r.document_no}</title><style>body{font-family:Arial;padding:36px;color:#111}h1{text-align:center}.row{display:flex;justify-content:space-between;border-bottom:1px solid #ddd;padding:9px 0}.sig{display:flex;justify-content:space-between;margin-top:60px}</style></head><body><h1>${r.entry_type==="Payment"?"SALARY PAYMENT SLIP":"SALARY ACCRUAL VOUCHER"}</h1><div class="row"><b>Employee</b><span>${r.employee_name}</span></div><div class="row"><b>Employee Code</b><span>${r.employee_code||"-"}</span></div><div class="row"><b>Salary Month</b><span>${String(r.salary_month).slice(0,7)}</span></div><div class="row"><b>Date</b><span>${r.entry_date}</span></div><div class="row"><b>Voucher</b><span>${r.document_no}</span></div><div class="row"><b>${r.entry_type==="Payment"?"Paid Now":"Monthly Salary"}</b><span>Rs. ${money(r.entry_type==="Payment"?r.credit:r.debit)}</span></div>${showBalances?`<div class="row"><b>Balance Before</b><span>Rs. ${money(before)}</span></div><div class="row"><b>Remaining Balance</b><span>Rs. ${money(after)}</span></div>`:""}<div class="sig"><span>Prepared By ______</span><span>Authorized By ______</span><span>Employee Signature ______</span></div><script>window.onload=()=>window.print()</script></body></html>`);w.document.close()};
 return <div className="space-y-4" data-print-root>
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-xl font-bold">Payroll & Salary Ledger</h1><p className="text-sm text-slate-500">Monthly salary accrual, payments, outstanding balance, reprint and export.</p></div><button className="btn-secondary no-print" onClick={()=>void load()}><RefreshCw className="h-4 w-4"/>Refresh</button></div>
  {error&&<div className="rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}{message&&<div className="rounded-lg bg-emerald-50 p-3 text-emerald-700">{message}</div>}
  <div className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-4 no-print" data-report-filters>
   <label className="text-sm font-semibold">Employee<select className="input mt-1 w-full" value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">All Employees</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>
   <label className="text-sm font-semibold">Salary Month<input className="input mt-1 w-full" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label>
   <label className="mt-6 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={showBalances} onChange={e=>setShowBalances(e.target.checked)}/> Show balance</label>
   <button className="btn-primary mt-5" onClick={()=>void accrue()} disabled={!employeeId}>Accrue Selected Month</button>
  </div>
  <div className="flex flex-wrap gap-2 no-print"><button className="btn-secondary" onClick={()=>exportMatrixToExcel("Payroll_Ledger.xlsx",matrix(),"Payroll")}>Excel</button><button className="btn-secondary" onClick={()=>exportMatrixToCSV("Payroll_Ledger.csv",matrix())}>CSV</button><button className="btn-secondary" onClick={()=>exportMatrixToWord("Payroll_Ledger.doc",matrix(),"Payroll & Salary Ledger")}>Word</button><button className="btn-primary" onClick={()=>window.print()}><Printer className="h-4 w-4"/>Print</button></div>
  <div className="grid gap-3 md:grid-cols-3" data-export-summary><div className="summary-card"><div className="summary-label">Accrued</div><div className="summary-value">Rs. {money(totals.debit)}</div></div><div className="summary-card"><div className="summary-label">Paid</div><div className="summary-value">Rs. {money(totals.credit)}</div></div><div className="summary-card"><div className="summary-label">Outstanding</div><div className="summary-value">Rs. {money(Math.max(totals.debit-totals.credit,0))}</div></div></div>
  <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full whitespace-nowrap text-sm"><thead><tr><th>Employee</th><th>Month</th><th>Date</th><th>Document</th><th>Type</th><th className="text-right">Accrued</th><th className="text-right">Paid</th>{showBalances&&<th className="text-right">Balance</th>}<th className="no-print">Action</th></tr></thead><tbody>{filtered.map(r=><tr key={`${r.document_no}:${r.entry_type}`}><td>{r.employee_name}</td><td>{String(r.salary_month).slice(0,7)}</td><td>{r.entry_date}</td><td>{r.document_no}</td><td>{r.entry_type}</td><td className="text-right">{money(r.debit)}</td><td className="text-right">{money(r.credit)}</td>{showBalances&&<td className="text-right">{money(r.balance||0)}</td>}<td className="no-print"><button type="button" data-direct-print="true" className="btn-secondary" onClick={()=>printSlip(r)}><FileDown className="h-4 w-4"/>{r.entry_type==="Payment"?"Salary Slip":"Voucher"}</button></td></tr>)}{!loading&&!filtered.length&&<tr><td colSpan={9} className="p-6 text-center text-slate-400">No payroll entries for selected filters.</td></tr>}</tbody></table></div>
  {selected&&<div className="text-xs text-slate-500">Selected employee: {selected.name}{selected.designation?` · ${selected.designation}`:""}</div>}
 </div>
}
