import { useCallback, useEffect, useMemo, useState } from "react";
import { FileText, Printer, RefreshCw } from "lucide-react";
import jsPDF from "jspdf";
import { supabase } from "@/lib/supabase";
import { exportMatrixToCSV, exportMatrixToExcel, exportMatrixToWord } from "@/lib/exportUtils";

const money=(v:number)=>new Intl.NumberFormat("en-PK",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0));
const monthNow=()=>new Date().toISOString().slice(0,7);
type Employee={id:string;employee_code?:string|null;name:string;designation?:string|null;department?:string|null};
type Row={employee_id:string;employee_code?:string|null;employee_name:string;designation?:string|null;department?:string|null;salary_month:string;entry_date:string;document_no:string;entry_type:string;debit:number;credit:number;journal_entry_id:string;balance?:number};
type SalarySummary={monthly_salary:number;previous_balance:number;paid_in_month:number;total_payable:number};

export default function PayrollLedger(){
 const [employees,setEmployees]=useState<Employee[]>([]),[rows,setRows]=useState<Row[]>([]),[employeeId,setEmployeeId]=useState(""),[month,setMonth]=useState(monthNow()),[showBalances,setShowBalances]=useState(true),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null),[summary,setSummary]=useState<SalarySummary|null>(null),[slipDocument,setSlipDocument]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError(null);const [e,l]=await Promise.all([supabase.from("employees").select("id,employee_code,name,designation,department").eq("is_active",true).order("name"),supabase.from("employee_salary_ledger").select("*").order("entry_date",{ascending:true}).order("document_no",{ascending:true})]);if(e.error||l.error)setError(e.error?.message||l.error?.message||"Failed to load payroll ledger.");setEmployees((e.data||[]) as Employee[]);setRows(((l.data||[]) as Row[]).map(r=>({...r,debit:Number(r.debit||0),credit:Number(r.credit||0)})));setLoading(false)},[]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{let cancelled=false;const run=async()=>{if(!employeeId||!month){setSummary(null);return}const {data,error:e}=await supabase.rpc("get_employee_salary_summary",{p_employee_id:employeeId,p_salary_month:`${month}-01`} as any);if(cancelled)return;if(e){setSummary(null);return}const x=(data||{}) as any;setSummary({monthly_salary:Number(x.monthly_salary||0),previous_balance:Number(x.previous_balance||0),paid_in_month:Number(x.paid_in_month||0),total_payable:Number(x.total_payable||0)})};void run();return()=>{cancelled=true}},[employeeId,month,rows]);
 const filtered=useMemo(()=>{let bal=0;return rows.filter(r=>(!employeeId||r.employee_id===employeeId)&&(!month||String(r.salary_month).slice(0,7)===month)).map(r=>{bal+=Number(r.debit||0)-Number(r.credit||0);return {...r,balance:bal}})},[rows,employeeId,month]);
 const totals=useMemo(()=>filtered.reduce((a,r)=>({debit:a.debit+r.debit,credit:a.credit+r.credit}),{debit:0,credit:0}),[filtered]);
 const selected=employees.find(e=>e.id===employeeId);
 const outstanding=Math.max(totals.debit-totals.credit,0);
 const paymentRows=useMemo(()=>filtered.filter(r=>r.entry_type==="Payment"),[filtered]);
 useEffect(()=>{if(!employeeId||!paymentRows.length){setSlipDocument("");return}if(!paymentRows.some(r=>r.document_no===slipDocument))setSlipDocument(paymentRows[paymentRows.length-1].document_no)},[employeeId,paymentRows,slipDocument]);
 const selectedSlip=paymentRows.find(r=>r.document_no===slipDocument)||null;
 const matrix=()=>[["Employee","Code","Salary Month","Date","Document","Type","Accrued","Paid",...(showBalances?["Balance"]:[])],...filtered.map(r=>[r.employee_name,r.employee_code||"",String(r.salary_month).slice(0,7),r.entry_date,r.document_no,r.entry_type,r.debit,r.credit,...(showBalances?[r.balance||0]:[])])];
 const accrue=async()=>{if(!employeeId||!month){setError("Select employee and salary month.");return}setError(null);setMessage(null);const {data,error:e}=await supabase.rpc("accrue_employee_salary",{p_employee_id:employeeId,p_salary_month:`${month}-01`} as any);if(e){setError(e.message);return}setMessage((data as any)?.already_accrued?"Salary already accrued for this month.":`Salary accrued: ${(data as any)?.entry_no||"posted"}`);await load()};
 const slipFigures=(r:Row)=>{const priorPayments=paymentRows.filter(x=>x.document_no!==r.document_no&&(`${x.entry_date}:${x.document_no}`<`${r.entry_date}:${r.document_no}`)).reduce((s,x)=>s+Number(x.credit||0),0);const monthly=Number(summary?.monthly_salary||totals.debit||0);const previous=Number(summary?.previous_balance||0);const totalPayable=previous+monthly;const before=Math.max(totalPayable-priorPayments,0);const remaining=Math.max(before-Number(r.credit||0),0);return{monthly,previous,totalPayable,priorPayments,before,remaining}};
 const printSlip=(r:Row)=>{const f=slipFigures(r);const w=window.open("","_blank","width=820,height=900");if(!w)return;w.document.write(`<html><head><title>${r.document_no}</title><style>body{font-family:Arial;padding:36px;color:#111}h1{text-align:center;margin-bottom:6px}.sub{text-align:center;color:#666;margin-bottom:22px}.row{display:flex;justify-content:space-between;border-bottom:1px solid #ddd;padding:9px 0}.sig{display:flex;justify-content:space-between;margin-top:60px;font-size:12px}</style></head><body><h1>SALARY PAYMENT SLIP</h1><div class="sub">Payroll record</div><div class="row"><b>Employee</b><span>${r.employee_name}</span></div><div class="row"><b>Employee Code</b><span>${r.employee_code||"-"}</span></div><div class="row"><b>Designation</b><span>${r.designation||"-"}</span></div><div class="row"><b>Department</b><span>${r.department||"-"}</span></div><div class="row"><b>Salary Month</b><span>${String(r.salary_month).slice(0,7)}</span></div><div class="row"><b>Monthly Salary</b><span>Rs. ${money(f.monthly)}</span></div>${showBalances?`<div class="row"><b>Previous Balance</b><span>Rs. ${money(f.previous)}</span></div><div class="row"><b>Total Payable</b><span>Rs. ${money(f.totalPayable)}</span></div><div class="row"><b>Paid Before This Slip</b><span>Rs. ${money(f.priorPayments)}</span></div>`:""}<div class="row"><b>Paid Now</b><span>Rs. ${money(r.credit)}</span></div>${showBalances?`<div class="row"><b>Remaining Balance</b><span>Rs. ${money(f.remaining)}</span></div>`:""}<div class="row"><b>Payment Date</b><span>${r.entry_date}</span></div><div class="row"><b>Voucher</b><span>${r.document_no}</span></div><div class="sig"><span>Prepared By ______</span><span>Authorized By ______</span><span>Employee Signature ______</span></div><script>window.onload=()=>window.print()</script></body></html>`);w.document.close()};
 const pdfLedger=()=>{const doc=new jsPDF({orientation:"landscape"});doc.setFontSize(16);doc.text("Payroll & Salary Ledger",14,16);doc.setFontSize(10);doc.text(`Employee: ${selected?.name||"All Employees"}   Month: ${month||"All"}`,14,24);doc.text(`Accrued: Rs. ${money(totals.debit)}   Paid: Rs. ${money(totals.credit)}   Outstanding: Rs. ${money(outstanding)}`,14,31);let y=40;filtered.forEach(r=>{if(y>190){doc.addPage();y=16}doc.text(`${r.entry_date} | ${r.employee_name} | ${r.entry_type} | Accrued Rs. ${money(r.debit)} | Paid Rs. ${money(r.credit)}${showBalances?` | Bal Rs. ${money(r.balance||0)}`:""}`,14,y);y+=7});doc.save("Payroll_Salary_Ledger.pdf")};
 const pdfSlip=(r:Row)=>{const f=slipFigures(r);const doc=new jsPDF();doc.setFontSize(17);doc.text("SALARY PAYMENT SLIP",105,18,{align:"center"});doc.setFontSize(11);const fields:any=[["Employee",r.employee_name],["Employee Code",r.employee_code||"-"],["Designation",r.designation||"-"],["Department",r.department||"-"],["Salary Month",String(r.salary_month).slice(0,7)],["Monthly Salary",`Rs. ${money(f.monthly)}`]];if(showBalances)fields.push(["Previous Balance",`Rs. ${money(f.previous)}`],["Total Payable",`Rs. ${money(f.totalPayable)}`],["Paid Before This Slip",`Rs. ${money(f.priorPayments)}`]);fields.push(["Paid Now",`Rs. ${money(r.credit)}`]);if(showBalances)fields.push(["Remaining Balance",`Rs. ${money(f.remaining)}`]);fields.push(["Payment Date",r.entry_date],["Voucher",r.document_no]);let y=32;fields.forEach(([k,v]:[string,string])=>{doc.text(k,18,y);doc.text(v,190,y,{align:"right"});doc.line(18,y+2,190,y+2);y+=11});doc.text("Prepared By __________",18,y+28);doc.text("Authorized By __________",105,y+28,{align:"center"});doc.text("Employee Signature __________",190,y+28,{align:"right"});doc.save(`${r.document_no}_Salary_Slip.pdf`)};
 return <div className="space-y-4" data-print-root>
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-xl font-bold">Payroll & Salary Ledger</h1><p className="text-sm text-slate-500">Monthly salary accrual, payments, outstanding balance, salary slips and exports.</p></div><button className="btn-secondary no-print" onClick={()=>void load()}><RefreshCw className="h-4 w-4"/>Refresh</button></div>
  {error&&<div className="rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}{message&&<div className="rounded-lg bg-emerald-50 p-3 text-emerald-700">{message}</div>}
  <div className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-4 no-print" data-report-filters>
   <label className="text-sm font-semibold">Employee<select className="input mt-1 w-full" value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">All Employees</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>
   <label className="text-sm font-semibold">Salary Month<input className="input mt-1 w-full" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label>
   <label className="mt-6 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={showBalances} onChange={e=>setShowBalances(e.target.checked)}/> Show balance on ledger/slip</label>
   <button className="btn-primary mt-5" onClick={()=>void accrue()} disabled={!employeeId}>Accrue Selected Month</button>
  </div>
  <div className="flex flex-wrap items-center gap-2 rounded-xl border bg-white p-3 no-print"><span className="mr-1 flex items-center gap-2 font-semibold"><FileText className="h-4 w-4"/>Salary Slip</span><select className="input min-w-[250px]" value={slipDocument} onChange={e=>setSlipDocument(e.target.value)} disabled={!employeeId||!paymentRows.length}><option value="">{employeeId?"Select payment voucher...":"Select employee first"}</option>{paymentRows.map(r=><option key={r.document_no} value={r.document_no}>{r.entry_date} · {r.document_no} · Rs. {money(r.credit)}</option>)}</select><button type="button" data-direct-print="true" className="btn-primary" disabled={!selectedSlip} onClick={()=>selectedSlip&&printSlip(selectedSlip)}><Printer className="h-4 w-4"/>Print Salary Slip</button><button type="button" className="btn-secondary" disabled={!selectedSlip} onClick={()=>selectedSlip&&pdfSlip(selectedSlip)}>Slip PDF</button></div>
  <div className="flex flex-wrap gap-2 no-print"><button className="btn-secondary" onClick={()=>exportMatrixToExcel("Payroll_Ledger.xlsx",matrix(),"Payroll")}>Excel</button><button className="btn-secondary" onClick={()=>exportMatrixToCSV("Payroll_Ledger.csv",matrix())}>CSV</button><button className="btn-secondary" onClick={()=>exportMatrixToWord("Payroll_Ledger.doc",matrix(),"Payroll & Salary Ledger")}>Word</button><button className="btn-secondary" onClick={pdfLedger}>Ledger PDF</button><button className="btn-primary" onClick={()=>window.print()}><Printer className="h-4 w-4"/>Print Ledger</button></div>
  <div className="grid gap-3 md:grid-cols-3" data-export-summary><div className="summary-card"><div className="summary-label">Accrued Salary</div><div className="summary-value">Rs. {money(totals.debit)}</div></div><div className="summary-card"><div className="summary-label">Paid Salary</div><div className="summary-value">Rs. {money(totals.credit)}</div></div><div className="summary-card"><div className="summary-label">Salary Payable</div><div className="summary-value">Rs. {money(outstanding)}</div></div></div>
  <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full whitespace-nowrap text-sm"><thead><tr><th>Employee</th><th>Month</th><th>Date</th><th>Document</th><th>Type</th><th className="text-right">Accrued</th><th className="text-right">Paid</th>{showBalances&&<th className="text-right">Balance</th>}</tr></thead><tbody>{filtered.map(r=><tr key={`${r.document_no}:${r.entry_type}`}><td>{r.employee_name}</td><td>{String(r.salary_month).slice(0,7)}</td><td>{r.entry_date}</td><td>{r.document_no}</td><td>{r.entry_type}</td><td className="text-right">{money(r.debit)}</td><td className="text-right">{money(r.credit)}</td>{showBalances&&<td className="text-right">{money(r.balance||0)}</td>}</tr>)}{!loading&&!filtered.length&&<tr><td colSpan={8} className="p-6 text-center text-slate-400">No payroll entries for selected filters.</td></tr>}</tbody></table></div>
  {selected&&<div className="text-xs text-slate-500">Selected employee: {selected.name}{selected.designation?` · ${selected.designation}`:""}</div>}
 </div>
}
