import { useCallback, useEffect, useMemo, useState } from "react";
import { RefreshCw } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { exportMatrixToCSV, exportMatrixToExcel, exportMatrixToWord } from "@/lib/exportUtils";

const money=(v:number)=>new Intl.NumberFormat("en-PK",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0));
const today=()=>new Date().toISOString().slice(0,10);
const monthStart=()=>`${today().slice(0,7)}-01`;
type Row={salesperson_id:string;sales_person:string;invoice_id:string;invoice_no:string;order_date:string;customer_id:string|null;customer_name:string|null;invoice_type:string|null;settlement_type:string|null;net_sales:number;received:number;outstanding:number;cash_business:number;bank_business:number;credit_business:number;actual_cogs:number;gross_profit:number;};

export default function SalespersonLedger(){
 const [rows,setRows]=useState<Row[]>([]),[person,setPerson]=useState(""),[from,setFrom]=useState(monthStart()),[to,setTo]=useState(today()),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);const {data,error:e}=await supabase.from("salesperson_business_performance_report").select("*").order("order_date",{ascending:true}).order("invoice_no",{ascending:true});if(e)setError(e.message);setRows(((data||[]) as Row[]).map(r=>({...r,net_sales:Number(r.net_sales||0),received:Number(r.received||0),outstanding:Number(r.outstanding||0),cash_business:Number(r.cash_business||0),bank_business:Number(r.bank_business||0),credit_business:Number(r.credit_business||0),actual_cogs:Number(r.actual_cogs||0),gross_profit:Number(r.gross_profit||0)})));setLoading(false)},[]);
 useEffect(()=>{void load()},[load]);
 const people=useMemo(()=>Array.from(new Map(rows.map(r=>[r.salesperson_id,r.sales_person||"Unassigned"])).entries()).sort((a,b)=>a[1].localeCompare(b[1])),[rows]);
 const filtered=useMemo(()=>rows.filter(r=>(!person||r.salesperson_id===person)&&(!from||r.order_date>=from)&&(!to||r.order_date<=to)&&(!search.trim()||`${r.invoice_no} ${r.customer_name||""} ${r.sales_person}`.toLowerCase().includes(search.toLowerCase()))),[rows,person,from,to,search]);
 const totals=useMemo(()=>filtered.reduce((a,r)=>({sales:a.sales+r.net_sales,received:a.received+r.received,outstanding:a.outstanding+r.outstanding,gp:a.gp+r.gross_profit}),{sales:0,received:0,outstanding:0,gp:0}),[filtered]);
 const matrix=()=>[["Sales Person","Date","Invoice","Customer","Invoice Type","Settlement","Net Sales","Received","Outstanding","Cash","Bank","Credit","COGS","Gross Profit"],...filtered.map(r=>[r.sales_person,r.order_date,r.invoice_no,r.customer_name||"",r.invoice_type||"",r.settlement_type||"",r.net_sales,r.received,r.outstanding,r.cash_business,r.bank_business,r.credit_business,r.actual_cogs,r.gross_profit])];
 return <div className="space-y-4" data-print-root>
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-xl font-bold">Salesperson Ledger</h1><p className="text-sm text-slate-500">Invoice-wise business ledger for each salesperson. This is a management ledger, not a GL account.</p></div><button className="btn-secondary no-print" onClick={()=>void load()}><RefreshCw className="h-4 w-4"/>Refresh</button></div>
  {error&&<div className="rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}
  <div className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-4 no-print" data-report-filters><label className="text-sm font-semibold">Sales Person<select className="input mt-1 w-full" value={person} onChange={e=>setPerson(e.target.value)}><option value="">All Salespersons</option>{people.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label className="text-sm font-semibold">From<input className="input mt-1 w-full" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-sm font-semibold">To<input className="input mt-1 w-full" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label className="text-sm font-semibold">Search<input className="input mt-1 w-full" placeholder="Invoice or customer" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
  <div className="flex flex-wrap gap-2 no-print"><button className="btn-secondary" onClick={()=>exportMatrixToExcel("Salesperson_Ledger.xlsx",matrix(),"Salesperson Ledger")}>Excel</button><button className="btn-secondary" onClick={()=>exportMatrixToCSV("Salesperson_Ledger.csv",matrix())}>CSV</button><button className="btn-secondary" onClick={()=>exportMatrixToWord("Salesperson_Ledger.doc",matrix(),"Salesperson Ledger")}>Word</button><button className="btn-primary" onClick={()=>window.print()}>Print</button></div>
  <div className="grid gap-3 md:grid-cols-4" data-export-summary><div className="summary-card"><div className="summary-label">Net Sales</div><div className="summary-value">Rs. {money(totals.sales)}</div></div><div className="summary-card"><div className="summary-label">Received</div><div className="summary-value">Rs. {money(totals.received)}</div></div><div className="summary-card"><div className="summary-label">Outstanding</div><div className="summary-value">Rs. {money(totals.outstanding)}</div></div><div className="summary-card"><div className="summary-label">Gross Profit</div><div className="summary-value">Rs. {money(totals.gp)}</div></div></div>
  <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full whitespace-nowrap text-sm"><thead><tr><th>Date</th><th>Sales Person</th><th>Invoice</th><th>Customer</th><th>Type</th><th>Settlement</th><th className="text-right">Net Sales</th><th className="text-right">Received</th><th className="text-right">Outstanding</th><th className="text-right">COGS</th><th className="text-right">Gross Profit</th></tr></thead><tbody>{filtered.map(r=><tr key={`${r.invoice_id}:${r.salesperson_id}`}><td>{r.order_date}</td><td>{r.sales_person}</td><td>{r.invoice_no}</td><td>{r.customer_name||"-"}</td><td>{r.invoice_type||"-"}</td><td>{r.settlement_type||"-"}</td><td className="text-right">{money(r.net_sales)}</td><td className="text-right">{money(r.received)}</td><td className="text-right">{money(r.outstanding)}</td><td className="text-right">{money(r.actual_cogs)}</td><td className="text-right">{money(r.gross_profit)}</td></tr>)}{!loading&&!filtered.length&&<tr><td colSpan={11} className="p-6 text-center text-slate-400">No salesperson ledger rows for selected filters.</td></tr>}</tbody></table></div>
 </div>
}
