export type ItemType = "raw" | "component" | "finished";
export type OrderStatus = "draft" | "confirmed" | "shipped" | "closed" | "posted";
export type PurchaseStatus = "draft" | "confirmed" | "received" | "closed" | "posted";
export type WorkOrderStatus = "planned" | "in_progress" | "completed" | "closed";
export type StockMovementType = "in" | "out" | "adjust";
export type JournalStatus = "draft" | "posted";
export type CuttingStatus = "pending" | "in_progress" | "completed" | "closed";
export type AccountType = "asset" | "liability" | "equity" | "revenue" | "expense";
export type GatePassType = "loading" | "unloading";
export type GatePassStatus = "pending" | "completed" | "cancelled";
export type PartyType = "customer" | "supplier";

export interface Item { id:string; user_id:string; sku:string; name:string; name_urdu?:string|null; type:ItemType; grade:string|null; size:string|null; unit:string; cost:number; price:number; created_at:string; }
export interface Customer { id:string; user_id:string; name:string; name_urdu?:string|null; email:string|null; phone:string|null; address:string|null; account_id:string|null; is_active:boolean; created_at:string; }
export interface Supplier { id:string; user_id:string; name:string; name_urdu?:string|null; email:string|null; phone:string|null; address:string|null; account_id:string|null; is_active:boolean; created_at:string; }
export interface SalesOrder { id:string; user_id:string; order_no:string; customer_id:string|null; sales_person:string|null; order_date:string; status:OrderStatus; total:number; invoice_type?:"Sale Invoice"|"Cash Bill"|"Tax Invoice"; tax_percent?:number; payment_mode?:"Credit"|"Cash"|"Bank"; payment_account_id?:string|null; loading_charge:number; unloading_charge:number; cutting_charge:number; transport_charge:number; labour_charge:number; handling_charge:number; other_charge:number; created_at:string; customer?:Customer|null; lines?:SalesOrderLine[]; }
export interface SalesOrderLine { id:string; user_id:string; order_id:string; item_id:string|null; godown_id:string|null; grade:string|null; size:string|null; description?:string|null; qty:number; unit_price:number; line_total:number; tax_percent?:number; item?:Item|null; godown?:{id:string;name:string;name_urdu?:string|null;warehouse_id?:string|null}|null; }
export interface PurchaseOrder { id:string; user_id:string; order_no:string; supplier_id:string|null; order_date:string; status:PurchaseStatus; total:number; invoice_type?:"Purchase Invoice"|"Tax Invoice"; tax_percent?:number; loading_charge:number; unloading_charge:number; cutting_charge:number; transport_charge:number; labour_charge:number; handling_charge:number; other_charge:number; created_at:string; supplier?:Supplier|null; lines?:PurchaseOrderLine[]; paid_amount?:number|null; outstanding_amount?:number|null; payment_status?:"unpaid"|"partial"|"paid"|"overpaid"|string|null; }
export interface PurchaseOrderLine { id:string; user_id:string; order_id:string; item_id:string|null; godown_id:string|null; description?:string|null; qty:number; unit_cost:number; line_total:number; tax_percent?:number; source_consolidated_purchase_invoice_id?:string|null; item?:Item|null; godown?:{id:string;name:string;name_urdu?:string|null;warehouse_id?:string|null}|null; }
export interface WorkOrder { id:string; user_id:string; order_no:string; item_id:string|null; qty:number; status:WorkOrderStatus; start_date:string|null; end_date:string|null; created_at:string; item?:Item|null; lines?:WorkOrderLine[]; }
export interface WorkOrderLine { id:string; user_id:string; order_id:string; item_id:string|null; qty:number; item?:Item|null; }
export interface StockMovement { id:string; user_id:string; item_id:string|null; type:StockMovementType; qty:number; reference:string|null; created_at:string; item?:Item|null; }
export interface WarehouseStock { id:string; user_id:string; item_id:string|null; godown:string; quantity:number; updated_at:string; item?:Item|null; }
export interface FurnaceYield { id:string; user_id:string; heat_no:string; furnace_no:string|null; charge_weight:number; output_weight:number; yield_pct:number; yield_date:string; created_at:string; }
export interface CuttingOrder { id:string; user_id:string; order_no:string; customer_id:string|null; item_id:string|null; cut_length:string|null; qty:number; loading_qty:number; status:CuttingStatus; created_at:string; customer?:Customer|null; item?:Item|null; }
export interface JournalEntry { id:string; user_id:string; entry_no:string; entry_date:string; description:string|null; status:JournalStatus; payment_mode?:string|null; party_name?:string|null; received_by?:string|null; trans_type?:string|null; reversal_of_entry_id?:string|null; reversal_reason?:string|null; created_at:string; lines?:JournalLine[]; }
export interface JournalLine { id:string; user_id:string; entry_id:string; account:string; account_id:string|null; party_type:PartyType|null; party_id:string|null; party_name:string|null; debit:number; credit:number; coa?:ChartOfAccount|null; customer?:Customer|null; supplier?:Supplier|null; }
export interface ChartOfAccount { id:string; user_id:string; code:string; name:string; type:AccountType; parent_id:string|null; is_group:boolean; allow_manual_entries:boolean; is_active:boolean; is_system_account:boolean; account_role:string|null; detail_type:string|null; parent_head:string|null; normal_balance?:"debit"|"credit"|string|null; description:string|null; created_at:string; updated_at?:string; }
export interface AccountMapping { id:string; user_id:string; mapping_key:string; account_id:string; created_at?:string; account?:ChartOfAccount|null; }
export interface Ledger { id:string; user_id:string; journal_entry_id:string|null; journal_line_id:string|null; account_id:string|null; entry_date:string; description:string|null; debit:number; credit:number; created_at:string; account?:ChartOfAccount|null; }
export interface PartyLedger { id:string; user_id:string; party_type:PartyType; party_id:string; entry_date:string; description:string|null; reference:string|null; debit:number; credit:number; balance:number; journal_entry_id:string|null; journal_line_id:string|null; created_at:string; customer?:Customer|null; supplier?:Supplier|null; }
export interface GatePass { id:string; user_id:string; pass_no:string; sales_order_id:string|null; type:GatePassType; godown:string; vehicle_no:string|null; driver_name:string|null; tare_weight:number; gross_weight:number; net_weight:number; labour_contractor:string|null; status:GatePassStatus; pass_date:string; created_at:string; sales_order?:SalesOrder|null; }
export interface InsertResult<T> { data:T|null; error:string|null; }
