import { useEffect, useState } from "react";
import { Filter, RotateCcw, X } from "lucide-react";
import { useLocation } from "react-router-dom";

type Filters={from:string;to:string;party:string;salesperson:string;item:string;status:string;rate:string;balance:string};
const empty:Filters={from:"",to:"",party:"",salesperson:"",item:"",status:"",rate:"",balance:""};
const norm=(s:string)=>s.trim().toLowerCase();

export default function OrderBookAdvancedFilters(){
 const {pathname}=useLocation();
 const active=pathname==="/sales/order-book"||pathname==="/purchase/order-book";
 const [open,setOpen]=useState(false),[f,setF]=useState<Filters>(empty);
 useEffect(()=>{if(!active)return;const apply=()=>{const table=[...document.querySelectorAll("table")].find(t=>t.textContent?.includes("Ordered")&&t.textContent?.includes("Fulfilled")&&t.textContent?.includes("Balance"));if(!table)return;table.querySelectorAll("tbody tr").forEach(row=>{const cells=[...row.querySelectorAll("td")].map(x=>norm(x.textContent||""));if(!cells.length)return;const text=cells.join(" ");let ok=true;if(f.party&&!(cells[1]||"").includes(norm(f.party)))ok=false;if(f.salesperson&&!(cells[1]||"").includes(norm(f.salesperson)))ok=false;if(f.item&&!(cells[2]||"").includes(norm(f.item)))ok=false;if(f.status&&!text.includes(norm(f.status)))ok=false;if(f.rate==="pending"&&!text.includes("pending"))ok=false;if(f.rate==="agreed"&&text.includes("pending"))ok=false;if(f.balance==="open"){const v=parseFloat((cells[5]||"").replace(/[^0-9.-]/g,""));if(!(v>0))ok=false}if(f.balance==="zero"){const v=parseFloat((cells[5]||"").replace(/[^0-9.-]/g,""));if(v!==0)ok=false}const date=(cells[0]||"").match(/\d{4}-\d{2}-\d{2}/)?.[0]||(cells[0]||"").match(/\d{2}-\d{2}-\d{4}/)?.[0];if(date){const iso=date.split("-")[0].length===4?date:date.split("-").reverse().join("-");if(f.from&&iso<f.from)ok=false;if(f.to&&iso>f.to)ok=false}(row as HTMLElement).style.display=ok?"":"none"})};apply();const mo=new MutationObserver(apply);mo.observe(document.body,{childList:true,subtree:true});return()=>mo.disconnect()},[active,f]);
 if(!active)return null;const set=(k:keyof Filters,v:string)=>setF(x=>({...x,[k]:v}));const count=Object.values(f).filter(Boolean).length;
 return <><button type="button" onClick={()=>setOpen(true)} className="fixed bottom-[13.5rem] right-5 z-[74] flex items-center gap-2 rounded-full bg-slate-800 px-4 py-2.5 text-sm font-black text-white shadow-xl hover:bg-slate-900 print:hidden"><Filter size={15}/> Filters / فلٹرز {count?`(${count})`:""}</button>{open&&<div className="fixed inset-0 z-[190] flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-3xl rounded-2xl bg-white p-5 shadow-2xl"><div className="mb-4 flex justify-between"><div><h2 className="text-lg font-black">Order Book Filters / آرڈر بک فلٹرز</h2><p className="text-sm text-slate-500">Combine multiple filters together.</p></div><button onClick={()=>setOpen(false)}><X/></button></div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3"><Field label="From Date"><input type="date" className="input w-full" value={f.from} onChange={e=>set("from",e.target.value)}/></Field><Field label="To Date"><input type="date" className="input w-full" value={f.to} onChange={e=>set("to",e.target.value)}/></Field><Field label="Customer / Supplier"><input className="input w-full" value={f.party} onChange={e=>set("party",e.target.value)} placeholder="Name..."/></Field><Field label="Salesperson"><input className="input w-full" value={f.salesperson} onChange={e=>set("salesperson",e.target.value)} placeholder="Name..."/></Field><Field label="Item"><input className="input w-full" value={f.item} onChange={e=>set("item",e.target.value)} placeholder="Item..."/></Field><Field label="Status"><select className="input w-full" value={f.status} onChange={e=>set("status",e.target.value)}><option value="">All</option><option value="confirmed">Confirmed</option><option value="open">Open</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></Field><Field label="Rate"><select className="input w-full" value={f.rate} onChange={e=>set("rate",e.target.value)}><option value="">All</option><option value="agreed">Agreed</option><option value="pending">Pending</option></select></Field><Field label="Balance"><select className="input w-full" value={f.balance} onChange={e=>set("balance",e.target.value)}><option value="">All</option><option value="open">Outstanding only</option><option value="zero">Zero balance</option></select></Field></div><div className="mt-5 flex justify-end gap-2"><button className="btn" onClick={()=>setF(empty)}><RotateCcw size={15}/> Clear All</button><button className="btn btn-primary" onClick={()=>setOpen(false)}>Apply Filters</button></div></div></div>}</>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-bold"><span className="mb-1 block">{label}</span>{children}</label>}
