import { useEffect, useMemo, useState } from "react";
import { BookOpenCheck, Loader2, X } from "lucide-react";
import { useLocation, useNavigate } from "react-router-dom";
import { supabase } from "@/lib/supabase";

type CommitmentRow={id:string;item_name:string;agreed_rate:number|string|null;uom:string|null;order_id:string;rate_status:string;ordered_qty:number|string;fulfilled_qty:number|string;cancelled_qty:number|string};
type HeaderRow={id:string;order_no:string;order_type:"sales"|"purchase";party_name:string;status:string};
type OpenRow=CommitmentRow&{header:HeaderRow;available:number};
type Godown={id:string;name:string;name_urdu?:string|null};
type LinkedLine={id:string;qty:number|string;godown_id:string;order_book_commitment_id:string;description?:string|null};

export default function OrderBookInvoiceActions(){
 const {pathname}=useLocation(); const navigate=useNavigate();
 const salesNew=pathname==="/sales/new", purchaseNew=pathname==="/purchase/new";
 const salesConsolidated=pathname==="/sales/consolidated", purchaseConsolidated=pathname==="/purchase/consolidated";
 const salesDetail=/^\/sales\/[0-9a-f-]{36}$/i.test(pathname), purchaseDetail=/^\/purchase\/[0-9a-f-]{36}$/i.test(pathname);
 const active=salesNew||purchaseNew||salesConsolidated||purchaseConsolidated||salesDetail||purchaseDetail;
 const type: "sales"|"purchase"=(salesNew||salesConsolidated||salesDetail)?"sales":"purchase";
 const detailId=(salesDetail||purchaseDetail)?pathname.split("/").pop()||"":null;
 const [enabled,setEnabled]=useState(false),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null);
 const [rows,setRows]=useState<OpenRow[]>([]),[godowns,setGodowns]=useState<Godown[]>([]),[selected,setSelected]=useState<OpenRow|null>(null),[qty,setQty]=useState(""),[godownId,setGodownId]=useState(""),[invoiceType,setInvoiceType]=useState<"without_tax"|"with_tax">("without_tax");
 const [linked,setLinked]=useState<LinkedLine|null>(null),[editAvailable,setEditAvailable]=useState(0),[detailStatus,setDetailStatus]=useState<string|null>(null);
 const consolidated=salesConsolidated||purchaseConsolidated;

 useEffect(()=>{if(!active)return;let alive=true;void(async()=>{const {data}=await supabase.from("company_settings").select("order_book_enabled").maybeSingle();if(alive)setEnabled(Boolean(data?.order_book_enabled));})();return()=>{alive=false}},[active]);
 useEffect(()=>{if(!active||!detailId)return;let alive=true;void(async()=>{setLinked(null);setDetailStatus(null);const headerTable=type==="sales"?"sales_orders":"purchase_orders";const lineTable=type==="sales"?"sales_order_lines":"purchase_order_lines";const fk=type==="sales"?"order_id":"order_id";const {data:h}=await supabase.from(headerTable).select("status").eq("id",detailId).maybeSingle();if(!alive)return;setDetailStatus(String(h?.status||""));const {data:l}=await supabase.from(lineTable).select("id,qty,godown_id,order_book_commitment_id,description").eq(fk,detailId).not("order_book_commitment_id","is",null).limit(1).maybeSingle();if(!alive||!l)return;setLinked(l as LinkedLine);const {data:a}=await supabase.rpc("order_commitment_available_qty",{p_commitment_id:l.order_book_commitment_id});setEditAvailable((Number(a)||0)+Number(l.qty||0));})();return()=>{alive=false}},[active,detailId,type]);

 const loadPicker=async()=>{setOpen(true);setLoading(true);setError(null);try{const [{data:heads,error:he},{data:cs,error:ce},{data:g,error:ge}]=await Promise.all([supabase.from("order_book_headers").select("id,order_no,order_type,party_name,status").eq("order_type",type).in("status",["confirmed","partially_fulfilled","rate_pending"]),supabase.from("order_book_commitments").select("id,item_name,agreed_rate,uom,order_id,rate_status,ordered_qty,fulfilled_qty,cancelled_qty").eq("rate_status","agreed"),supabase.from("godowns").select("id,name,name_urdu").order("name")]);if(he)throw he;if(ce)throw ce;if(ge)throw ge;const hm=new Map((heads||[]).map((h:any)=>[h.id,h as HeaderRow]));const candidates=(cs||[]).filter((c:any)=>hm.has(c.order_id));const enriched:OpenRow[]=[];for(const c of candidates){const {data:a,error:ae}=await supabase.rpc("order_commitment_available_qty",{p_commitment_id:c.id});if(ae)throw ae;const av=Number(a)||0;if(av>0)enriched.push({...c,header:hm.get(c.order_id)!,available:av} as OpenRow)}setRows(enriched);setGodowns((g||[]) as Godown[]);}catch(e:any){setError(e?.message||"Order Book commitments could not be loaded.")}finally{setLoading(false)}};
 const choose=(r:OpenRow)=>{if(!consolidated){navigate(`${type==="sales"?"/sales/new":"/purchase/new"}?orderCommitment=${r.id}`);setOpen(false);return;}setSelected(r);setQty(String(r.available));setGodownId(godowns[0]?.id||"");};
 const createConsolidated=async()=>{if(!selected)return;setSaving(true);setError(null);try{const q=Number(qty);if(q<=0||q>selected.available+0.0001)throw new Error(`Qty must be between 0 and ${selected.available}.`);if(!godownId)throw new Error("Select Godown.");const {data,error}=await supabase.rpc("create_consolidated_invoice_from_order_commitment",{p_commitment_id:selected.id,p_qty:q,p_godown_id:godownId,p_invoice_type:invoiceType});if(error)throw error;setOpen(false);setSelected(null);window.location.assign(String((data as any)?.path||pathname));}catch(e:any){setError(e?.message||"Could not create Consolidated Invoice.")}finally{setSaving(false)}};
 const editLinked=()=>{if(!linked)return;setOpen(true);setSelected(null);setQty(String(linked.qty));setGodownId(linked.godown_id);setError(null);};
 const saveLinked=async()=>{if(!linked)return;setSaving(true);setError(null);try{const q=Number(qty);if(q<=0||q>editAvailable+0.0001)throw new Error(`Qty cannot exceed ${editAvailable}.`);if(!godownId)throw new Error("Select Godown.");const {error}=await supabase.rpc("update_order_book_linked_line",{p_line_id:linked.id,p_qty:q,p_godown_id:godownId,p_kind:type==="sales"?"sales_main":"purchase_main"});if(error)throw error;setOpen(false);window.location.reload();}catch(e:any){setError(e?.message||"Could not update Order Book line.")}finally{setSaving(false)}};
 const title=useMemo(()=>consolidated?`Create ${type==="sales"?"Consolidated Sales":"Consolidated Purchase"} from Order Book`:`Select from Order Book`,[consolidated,type]);
 if(!active||!enabled)return null;
 const isDraftDetail=Boolean(detailId&&detailStatus==="draft"&&linked);
 return <>
  <div className="fixed bottom-5 left-5 z-50 print:hidden"><button className="btn btn-primary shadow-xl" onClick={()=>isDraftDetail?editLinked():void loadPicker()}><BookOpenCheck className="h-4 w-4"/>{isDraftDetail?"Edit Order Book Qty / Godown":"From Order Book / آرڈر بک سے"}</button></div>
  {open&&<div className="fixed inset-0 z-[140] flex items-center justify-center bg-slate-950/55 p-4 print:hidden"><div className="w-full max-w-4xl rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-5"><div><div className="text-lg font-black">{isDraftDetail?"Edit Linked Order Book Line / آرڈر بک لائن تبدیل کریں":title}</div><div className="text-xs text-slate-500">Item and agreed rate remain locked. Qty is limited to available balance; Godown must be linked to a warehouse.</div></div><button onClick={()=>{setOpen(false);setSelected(null)}}><X/></button></div><div className="p-5">{error&&<div className="mb-3 rounded-lg border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}
   {isDraftDetail?<div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-bold">Qty / مقدار<input className="input mt-1 w-full" type="number" min="0.001" step="0.001" max={editAvailable} value={qty} onChange={e=>setQty(e.target.value)}/><span className="mt-1 block text-xs text-slate-500">Maximum available including this draft: {editAvailable}</span></label><label className="text-sm font-bold">Godown / گودام<select className="input mt-1 w-full" value={godownId} onChange={e=>setGodownId(e.target.value)}>{godowns.map(g=><option key={g.id} value={g.id}>{g.name}{g.name_urdu?` / ${g.name_urdu}`:""}</option>)}</select></label><div className="md:col-span-2 flex justify-end"><button className="btn btn-primary" disabled={saving} onClick={()=>void saveLinked()}>{saving?<Loader2 className="h-4 w-4 animate-spin"/>:null}Save Qty / Godown</button></div></div>:
   loading?<div className="flex min-h-40 items-center justify-center"><Loader2 className="mr-2 h-5 w-5 animate-spin"/>Loading open commitments…</div>:selected&&consolidated?<div className="space-y-4"><div className="rounded-xl border bg-slate-50 p-4"><b>{selected.header.order_no}</b> — {selected.header.party_name}<br/>{selected.item_name} | Available {selected.available} {selected.uom||""} | Rate Rs {Number(selected.agreed_rate||0).toLocaleString()}</div><div className="grid gap-3 md:grid-cols-3"><label className="text-sm font-bold">Qty<input className="input mt-1 w-full" type="number" max={selected.available} min="0.001" step="0.001" value={qty} onChange={e=>setQty(e.target.value)}/></label><label className="text-sm font-bold">Godown<select className="input mt-1 w-full" value={godownId} onChange={e=>setGodownId(e.target.value)}><option value="">Select…</option>{godowns.map(g=><option key={g.id} value={g.id}>{g.name}{g.name_urdu?` / ${g.name_urdu}`:""}</option>)}</select></label><label className="text-sm font-bold">Invoice Type<select className="input mt-1 w-full" value={invoiceType} onChange={e=>setInvoiceType(e.target.value as any)}><option value="without_tax">Without Tax</option><option value="with_tax">With Tax</option></select></label></div><div className="flex justify-between"><button className="btn" onClick={()=>setSelected(null)}>Back</button><button className="btn btn-primary" disabled={saving} onClick={()=>void createConsolidated()}>{saving?<Loader2 className="h-4 w-4 animate-spin"/>:null}Create Draft</button></div></div>:<div className="max-h-[60vh] overflow-auto rounded-xl border"><table className="table w-full"><thead><tr><th>Order</th><th>Party</th><th>Item</th><th>Available</th><th>Rate</th><th></th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={6} className="py-8 text-center">No agreed open Order Book commitment available.</td></tr>:rows.map(r=><tr key={r.id}><td>{r.header.order_no}</td><td>{r.header.party_name}</td><td>{r.item_name}</td><td>{r.available} {r.uom||""}</td><td>Rs {Number(r.agreed_rate||0).toLocaleString()}</td><td><button className="btn btn-primary" onClick={()=>choose(r)}>Select</button></td></tr>)}</tbody></table></div>}
  </div></div></div>}
 </>;
}
