import { useEffect, useMemo, useState } from "react";
import { Ban, Loader2, X } from "lucide-react";
import { useLocation } from "react-router-dom";
import { supabase } from "@/lib/supabase";

type Commitment={ordered_qty:number|string;fulfilled_qty:number|string;cancelled_qty:number|string};
type Order={id:string;order_no:string;order_date:string;party_name:string;status:string;order_type:"sales"|"purchase";order_book_commitments?:Commitment[]};
const n=(v:unknown)=>Number(v)||0;

export default function OrderBookCancelControl(){
 const {pathname}=useLocation();
 const type=pathname==="/sales/order-book"?"sales":pathname==="/purchase/order-book"?"purchase":null;
 const [open,setOpen]=useState(false),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[orders,setOrders]=useState<Order[]>([]),[orderId,setOrderId]=useState(""),[reason,setReason]=useState(""),[error,setError]=useState<string|null>(null);
 const load=async()=>{if(!type)return;setLoading(true);setError(null);const {data,error}=await supabase.from("order_book_headers").select("id,order_no,order_date,party_name,status,order_type,order_book_commitments(ordered_qty,fulfilled_qty,cancelled_qty)").eq("order_type",type).not("status","in",'(cancelled,completed)').order("order_date",{ascending:false});if(error)setError(error.message);else setOrders((data||[]) as Order[]);setLoading(false)};
 useEffect(()=>{if(type&&open)void load()},[type,open]);
 const selected=orders.find(o=>o.id===orderId);
 const summary=useMemo(()=>{const cs=selected?.order_book_commitments||[];return cs.reduce((a,c)=>{const ordered=n(c.ordered_qty),fulfilled=n(c.fulfilled_qty),cancelled=n(c.cancelled_qty);a.ordered+=ordered;a.fulfilled+=fulfilled;a.cancelled+=cancelled;a.balance+=Math.max(0,ordered-fulfilled-cancelled);return a},{ordered:0,fulfilled:0,cancelled:0,balance:0})},[selected]);
 if(!type)return null;
 const cancel=async()=>{if(!orderId||!reason.trim())return setError("Select an order and enter a cancellation reason.");setSaving(true);setError(null);const {error}=await supabase.rpc("cancel_order_book_order",{p_order_id:orderId,p_reason:reason.trim()});if(error){setError(error.message);setSaving(false);return}setSaving(false);setOpen(false);setOrderId("");setReason("");window.location.reload()};
 return <>
  {!open&&<button type="button" onClick={()=>setOpen(true)} className="fixed bottom-32 right-5 z-[72] flex items-center gap-2 rounded-full bg-red-600 px-4 py-2.5 text-sm font-black text-white shadow-xl hover:bg-red-700 print:hidden"><Ban size={15}/> Cancel Order / آرڈر منسوخ کریں</button>}
  {open&&<div className="fixed inset-0 z-[170] flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-xl rounded-2xl bg-white p-5 shadow-2xl"><div className="mb-4 flex items-start justify-between"><div><h2 className="text-lg font-black">Cancel Order / آرڈر منسوخ کریں</h2><p className="mt-1 text-sm text-slate-500">Only the unfulfilled balance will be cancelled. Posted invoices, stock and accounting stay unchanged.</p></div><button onClick={()=>setOpen(false)}><X/></button></div>{error&&<div className="mb-3 rounded-lg bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}{loading?<div className="py-8 text-center"><Loader2 className="mx-auto animate-spin"/></div>:<><label className="block text-sm font-bold">Order<select className="input mt-1 w-full" value={orderId} onChange={e=>setOrderId(e.target.value)}><option value="">Select order...</option>{orders.map(o=><option key={o.id} value={o.id}>{o.order_no} · {o.party_name} · {o.order_date}</option>)}</select></label>{selected&&<div className="mt-3 grid grid-cols-4 gap-2 text-sm"><div className="rounded border p-2"><div className="text-slate-500">Ordered</div><b>{summary.ordered}</b></div><div className="rounded border p-2"><div className="text-slate-500">Fulfilled</div><b>{summary.fulfilled}</b></div><div className="rounded border p-2"><div className="text-slate-500">Already Cancelled</div><b>{summary.cancelled}</b></div><div className="rounded border border-red-200 bg-red-50 p-2"><div className="text-red-600">Will Cancel</div><b>{summary.balance}</b></div></div>}<label className="mt-4 block text-sm font-bold">Cancellation Reason / منسوخی کی وجہ<textarea className="input mt-1 min-h-24 w-full" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason is required..."/></label><div className="mt-4 rounded-lg bg-amber-50 p-3 text-xs text-amber-800">If this order is linked to any Draft invoice line, cancellation will be blocked until that draft line is removed. This prevents broken reservations.</div><div className="mt-5 flex justify-end gap-2"><button className="btn" onClick={()=>setOpen(false)}>Close</button><button className="btn bg-red-600 text-white hover:bg-red-700" disabled={saving||!orderId||!reason.trim()} onClick={()=>void cancel()}>{saving?<Loader2 className="animate-spin" size={15}/>:<Ban size={15}/>} Confirm Cancel</button></div></>}</div></div>}
 </>
}
