import { useCallback, useEffect, useMemo, useState } from "react";
import { Printer, X } from "lucide-react";
import { useLocation } from "react-router-dom";
import { supabase } from "@/lib/supabase";

type Commitment={id:string;item_name:string;ordered_qty:number|string;fulfilled_qty:number|string;cancelled_qty:number|string;uom:string|null;rate_status:string;agreed_rate:number|string|null;effective_at:string|null;status:string;remarks:string|null};
type Header={id:string;order_no:string;order_date:string;party_id:string;party_name:string;salesperson_name:string|null;status:string;remarks:string|null;order_book_commitments?:Commitment[]};
type History={id:string;commitment_id:string;old_rate:number|string|null;new_rate:number|string|null;effective_at:string;reason:string;created_at?:string};
type Fulfillment={id:string;commitment_id:string;document_type:string;document_id:string;document_no:string;document_date:string;qty:number|string;rate:number|string;created_at:string};
const n=(v:unknown)=>Number(v)||0;
const money=(v:unknown)=>`Rs ${n(v).toLocaleString(undefined,{maximumFractionDigits:2})}`;
const shortOrderNo=(v:string)=>{const m=v.match(/^(SO|PO)-(?:\d{8}-)?(\d+)$/i);return m?`${m[1].toUpperCase()}-${String(Number(m[2])).padStart(4,"0")}`:v};

export default function OrderBookCustomerReport(){
 const {pathname}=useLocation();
 const [open,setOpen]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null),[customerId,setCustomerId]=useState("");
 const [customers,setCustomers]=useState<{id:string;name:string;phone?:string|null;address?:string|null}[]>([]),[orders,setOrders]=useState<Header[]>([]),[history,setHistory]=useState<History[]>([]),[fulfillments,setFulfillments]=useState<Fulfillment[]>([]);
 const loadCustomers=useCallback(async()=>{const {data,error}=await supabase.from("customers").select("id,name,phone,address").order("name");if(!error)setCustomers(data||[])},[]);
 useEffect(()=>{if(pathname==="/sales/order-book")void loadCustomers()},[loadCustomers,pathname]);
 const loadReport=async(id:string)=>{setCustomerId(id);setError(null);if(!id){setOrders([]);setHistory([]);setFulfillments([]);return}setLoading(true);try{const {data:o,error:e}=await supabase.from("order_book_headers").select("id,order_no,order_date,party_id,party_name,salesperson_name,status,remarks,order_book_commitments(id,item_name,ordered_qty,fulfilled_qty,cancelled_qty,uom,rate_status,agreed_rate,effective_at,status,remarks)").eq("order_type","sales").eq("party_id",id).order("order_date",{ascending:false});if(e)throw e;const os=((o||[]) as Header[]).filter(x=>(x.order_book_commitments||[]).length>0);setOrders(os);const ids=os.flatMap(x=>(x.order_book_commitments||[]).map(c=>c.id));if(ids.length){const [hr,fr]=await Promise.all([supabase.from("order_book_rate_history").select("id,commitment_id,old_rate,new_rate,effective_at,reason,created_at").in("commitment_id",ids).order("effective_at",{ascending:true}),supabase.from("order_book_fulfillments").select("id,commitment_id,document_type,document_id,document_no,document_date,qty,rate,created_at").in("commitment_id",ids).order("document_date",{ascending:true})]);if(hr.error)throw hr.error;if(fr.error)throw fr.error;setHistory((hr.data||[]) as History[]);setFulfillments((fr.data||[]) as Fulfillment[])}else{setHistory([]);setFulfillments([])}}catch(e:any){setError(e?.message||"Could not load customer order report.")}finally{setLoading(false)}};
 const customer=customers.find(c=>c.id===customerId);
 const totals=useMemo(()=>orders.flatMap(o=>o.order_book_commitments||[]).reduce((a,c)=>{const ordered=n(c.ordered_qty),fulfilled=n(c.fulfilled_qty),cancelled=n(c.cancelled_qty),balance=Math.max(0,ordered-fulfilled-cancelled);a.ordered+=ordered;a.fulfilled+=fulfilled;a.cancelled+=cancelled;a.balance+=balance;if(c.rate_status==="agreed")a.openValue+=balance*n(c.agreed_rate);return a},{ordered:0,fulfilled:0,cancelled:0,balance:0,openValue:0}),[orders]);
 const orderCount=orders.length, invoiceCount=new Set(fulfillments.map(f=>f.document_id)).size;
 const historyFor=(id:string)=>history.filter(h=>h.commitment_id===id);
 const fulfillmentFor=(id:string)=>fulfillments.filter(f=>f.commitment_id===id);
 if(pathname!=="/sales/order-book"&&!open)return null;
 return <>
  {!open&&<button type="button" className="fixed bottom-20 right-5 z-[70] flex items-center gap-2 rounded-full bg-emerald-600 px-4 py-2.5 text-sm font-black text-white shadow-xl hover:bg-emerald-700 print:hidden" onClick={()=>setOpen(true)} title="Customer Order Report"><Printer size={15}/> Customer Order Report / کسٹمر آرڈر رپورٹ</button>}
  {open&&<div className="fixed inset-0 z-[140] overflow-auto bg-slate-950/50 p-4"><div className="mx-auto max-w-7xl rounded-2xl bg-white p-5 shadow-xl">
   <div className="no-print mb-4 flex flex-wrap items-center gap-2"><h2 className="mr-auto text-lg font-black">Customer Order Book Report / کسٹمر آرڈر بک رپورٹ</h2><select className="input min-w-64" value={customerId} onChange={e=>void loadReport(e.target.value)}><option value="">Select customer...</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="btn btn-primary" disabled={!customerId||loading} onClick={()=>window.print()}><Printer size={15}/> Print</button><button className="btn" onClick={()=>setOpen(false)}><X size={16}/></button></div>
   {error&&<div className="mb-3 rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}{loading&&<div className="py-10 text-center">Loading...</div>}
   {!loading&&customerId&&<div id="customer-order-book-report" className="print-report text-xs text-slate-900"><div className="mb-4 border-b pb-3 text-center"><h1 className="text-xl font-black">Customer Order Book Statement</h1><div className="text-base font-black">{customer?.name}</div><div>{customer?.phone||""}{customer?.address?` · ${customer.address}`:""}</div><div className="mt-1 text-slate-500">Complete order, delivery/invoice and rate revision history</div></div>
    <div className="mb-4 grid grid-cols-4 gap-2">{[["Total Orders",orderCount],["Total Ordered Qty",totals.ordered],["Delivered / Invoiced Qty",totals.fulfilled],["Outstanding Qty",totals.balance],["Cancelled Qty",totals.cancelled],["Invoices",invoiceCount],["Outstanding Value",money(totals.openValue)],["Customer",customer?.name||"—"]].map(([k,v])=><div key={String(k)} className="rounded-lg border bg-slate-50 p-2.5"><div className="font-bold text-slate-500">{k}</div><div className="mt-0.5 text-base font-black">{String(v)}</div></div>)}</div>
    {orders.length===0?<div className="py-10 text-center">No Order Book commitments found for this customer.</div>:orders.map(o=>{const cs=o.order_book_commitments||[];const ot=cs.reduce((a,c)=>{const ordered=n(c.ordered_qty),fulfilled=n(c.fulfilled_qty),cancelled=n(c.cancelled_qty),balance=Math.max(0,ordered-fulfilled-cancelled);a.ordered+=ordered;a.fulfilled+=fulfilled;a.balance+=balance;if(c.rate_status==="agreed")a.value+=balance*n(c.agreed_rate);return a},{ordered:0,fulfilled:0,balance:0,value:0});return <section key={o.id} className="mb-5 break-inside-avoid rounded-lg border"><div className="flex flex-wrap items-center justify-between gap-2 bg-slate-100 p-2.5"><div><span className="font-black text-sm">Order {shortOrderNo(o.order_no)}</span><span className="ml-3">Date: {o.order_date}</span><span className="ml-3 font-bold uppercase">{o.status}</span></div><div>Salesperson: <b>{o.salesperson_name||"—"}</b></div></div><div className="grid grid-cols-4 border-y bg-white px-2 py-1.5"><span>Ordered: <b>{ot.ordered}</b></span><span>Fulfilled: <b>{ot.fulfilled}</b></span><span>Balance: <b>{ot.balance}</b></span><span>Open Value: <b>{money(ot.value)}</b></span></div>{o.remarks&&<div className="px-2 py-1">Remarks: {o.remarks}</div>}<table className="w-full border-collapse"><thead><tr>{["Item / Description","Ordered","Fulfilled","Cancelled","Balance","Current Rate","Open Value","Status"].map(h=><th key={h} className="border p-1.5 text-left">{h}</th>)}</tr></thead><tbody>{cs.map(c=>{const bal=Math.max(0,n(c.ordered_qty)-n(c.fulfilled_qty)-n(c.cancelled_qty));const hs=historyFor(c.id);const fs=fulfillmentFor(c.id);return <><tr key={c.id}><td className="border p-1.5">{c.item_name}{c.remarks?<><br/><span className="text-slate-500">{c.remarks}</span></>:null}</td><td className="border p-1.5">{n(c.ordered_qty)} {c.uom||""}</td><td className="border p-1.5">{n(c.fulfilled_qty)} {c.uom||""}</td><td className="border p-1.5">{n(c.cancelled_qty)} {c.uom||""}</td><td className="border p-1.5 font-black">{bal} {c.uom||""}</td><td className="border p-1.5">{c.rate_status==="agreed"?money(c.agreed_rate):"Pending"}</td><td className="border p-1.5">{c.rate_status==="agreed"?money(bal*n(c.agreed_rate)):"—"}</td><td className="border p-1.5 uppercase">{c.status}</td></tr>{fs.length>0&&<tr key={`${c.id}-fulfillment`}><td colSpan={8} className="border bg-emerald-50 p-2"><b>Invoices / Fulfillment:</b> {fs.map((f,i)=><span key={f.id} className="ml-3 inline-block">{i+1}. {f.document_no} · {f.document_date} · {n(f.qty)} {c.uom||""} @ {money(f.rate)}</span>)}</td></tr>}{hs.length>0&&<tr key={`${c.id}-history`}><td colSpan={8} className="border bg-amber-50 p-2"><b>Rate History:</b> {hs.map((h,i)=><span key={h.id} className="ml-3 inline-block">{i+1}. {h.old_rate==null?"Pending":money(h.old_rate)} → {money(h.new_rate)} · {new Date(h.effective_at).toLocaleDateString()}{h.reason?` · ${h.reason}`:""}</span>)}</td></tr>}</>})}</tbody></table></section>})}
   </div>}
  </div></div>}
  <style>{`@media print{body *{visibility:hidden!important}#customer-order-book-report,#customer-order-book-report *{visibility:visible!important}#customer-order-book-report{position:absolute;left:0;top:0;width:100%;padding:7mm}.no-print{display:none!important}@page{size:A4 landscape;margin:7mm}.break-inside-avoid{break-inside:avoid}#customer-order-book-report{font-size:10px}#customer-order-book-report table{page-break-inside:auto}#customer-order-book-report tr{page-break-inside:avoid}}`}</style>
 </>
}
