import SearchableSelect from "@/components/SearchableSelect";
import { useEffect, useMemo, useState } from "react";
import { BookOpenCheck, Loader2, Plus, ReceiptText, Trash2, X } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { calculateConfiguredChargeAmount, chargeQuantityForUnit, type ConfiguredChargeUnit } from "@/lib/chargeCalculation";

type PurchaseDraft={id:string;supplier_id:string|null;status:string;invoice_type:"Purchase Invoice"|"Tax Invoice";tax_percent:number|string|null};
type HeaderRow={id:string;order_no:string;party_id:string|null;party_name:string;status:string};
type CommitmentRow={id:string;order_id:string;item_id:string;item_name:string;uom:string|null;agreed_rate:number|string|null;rate_status:string};
type PickRow=CommitmentRow&{header:HeaderRow;available:number};
type Godown={id:string;name:string;name_urdu?:string|null};
type BasketRow={commitment:PickRow;qty:string;godown_id:string};
type Charge={charge_key:string;charge_name:string;charge_name_urdu?:string|null;default_rate:number|string;unit:ConfiguredChargeUnit;is_fixed:boolean;tax_applicable:boolean;purchase_treatment?:"landed_cost"|"expense"|null;cost_account_id?:string|null};
type ExistingCharge={charge_key:string;amount:number|string;quantity:number|string|null;rate:number|string|null};
type LineRow={item_id:string;qty:number|string;unit_cost:number|string;line_total:number|string};
type Item={id:string;unit?:string|null;weight_per_piece?:number|string|null};
const money=(value:unknown)=>`Rs ${(Number(value)||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default function PurchaseDraftAddControls({orderId,onChanged}:{orderId:string;onChanged?:()=>void}){
 const [draft,setDraft]=useState<PurchaseDraft|null>(null),[checking,setChecking]=useState(false);
 const [poOpen,setPoOpen]=useState(false),[poLoading,setPoLoading]=useState(false),[poSaving,setPoSaving]=useState(false),[poError,setPoError]=useState<string|null>(null),[poRows,setPoRows]=useState<PickRow[]>([]),[godowns,setGodowns]=useState<Godown[]>([]),[basket,setBasket]=useState<BasketRow[]>([]);
 const [chargeOpen,setChargeOpen]=useState(false),[chargeLoading,setChargeLoading]=useState(false),[chargeSaving,setChargeSaving]=useState(false),[chargeError,setChargeError]=useState<string|null>(null),[charges,setCharges]=useState<Charge[]>([]),[selectedKeys,setSelectedKeys]=useState<string[]>([]),[amounts,setAmounts]=useState<Record<string,string>>({}),[chargeToAdd,setChargeToAdd]=useState(""),[lines,setLines]=useState<LineRow[]>([]),[items,setItems]=useState<Item[]>([]);
 useEffect(()=>{let alive=true;setChecking(true);void(async()=>{const {data,error}=await supabase.from("purchase_orders").select("id,supplier_id,status,invoice_type,tax_percent").eq("id",orderId).maybeSingle();if(!alive)return;setChecking(false);if(!error&&data)setDraft(data as PurchaseDraft)})();return()=>{alive=false}},[orderId]);
 const isDraft=draft?.status==="draft";
 const loadPO=async()=>{if(!draft?.supplier_id)return;setPoOpen(true);setPoLoading(true);setPoError(null);setBasket([]);try{const [{data:heads,error:he},{data:commitments,error:ce},{data:g,error:ge}]=await Promise.all([supabase.from("order_book_headers").select("id,order_no,party_id,party_name,status").eq("order_type","purchase").eq("party_id",draft.supplier_id).in("status",["confirmed","partially_fulfilled","rate_pending"]),supabase.from("order_book_commitments").select("id,order_id,item_id,item_name,uom,agreed_rate,rate_status").eq("rate_status","agreed"),supabase.from("godowns").select("id,name,name_urdu").order("name")]);if(he)throw he;if(ce)throw ce;if(ge)throw ge;const hm=new Map((heads||[]).map((h:any)=>[h.id,h as HeaderRow]));const result:PickRow[]=[];for(const c of (commitments||[]) as CommitmentRow[]){const h=hm.get(c.order_id);if(!h)continue;const {data:a,error:ae}=await supabase.rpc("order_commitment_available_qty",{p_commitment_id:c.id});if(ae)throw ae;const available=Number(a)||0;if(available>0)result.push({...c,header:h,available})}setPoRows(result);setGodowns((g||[]) as Godown[])}catch(e:any){setPoError(e?.message||"Could not load Purchase Order commitments.")}finally{setPoLoading(false)}};
 const addBasket=(row:PickRow)=>{if(!basket.some(x=>x.commitment.id===row.id))setBasket(cur=>[...cur,{commitment:row,qty:String(row.available),godown_id:godowns[0]?.id||""}])};
 const updateBasket=(id:string,field:"qty"|"godown_id",value:string)=>setBasket(cur=>cur.map(x=>x.commitment.id===id?{...x,[field]:value}:x));
 const attachPO=async()=>{if(!basket.length)return;setPoSaving(true);setPoError(null);try{const payload=basket.map(entry=>{const qty=Number(entry.qty);if(!qty||qty<=0||qty>entry.commitment.available+0.0001)throw new Error(`Qty for ${entry.commitment.item_name} must be between 0 and ${entry.commitment.available}.`);if(!entry.godown_id)throw new Error(`Select Godown for ${entry.commitment.item_name}.`);return{commitment_id:entry.commitment.id,qty,godown_id:entry.godown_id}});const {error}=await supabase.rpc("add_order_commitments_to_purchase_draft_batch",{p_order_id:orderId,p_lines:payload});if(error)throw error;setPoOpen(false);onChanged?.()}catch(e:any){setPoError(e?.message||"Could not add Purchase Order lines.")}finally{setPoSaving(false)}};
 const loadCharges=async()=>{setChargeOpen(true);setChargeLoading(true);setChargeError(null);setChargeToAdd("");try{const [{data:master,error:me},{data:existing,error:ee},{data:lineData,error:le},{data:itemData,error:ie}]=await Promise.all([supabase.from("charge_master").select("charge_key,charge_name,charge_name_urdu,default_rate,unit,is_fixed,tax_applicable,purchase_treatment,cost_account_id").eq("is_active",true).in("applies_to",["purchase","both"]).order("charge_name"),supabase.from("purchase_order_charges").select("charge_key,amount,quantity,rate").eq("order_id",orderId).order("created_at"),supabase.from("purchase_order_lines").select("item_id,qty,unit_cost,line_total").eq("order_id",orderId).is("source_consolidated_purchase_invoice_id",null),supabase.from("items").select("id,unit,weight_per_piece")]);if(me)throw me;if(ee)throw ee;if(le)throw le;if(ie)throw ie;const loaded=(master||[]) as Charge[];const old=(existing||[]) as ExistingCharge[];setCharges(loaded);setLines((lineData||[]) as LineRow[]);setItems((itemData||[]) as Item[]);setSelectedKeys(old.map(r=>r.charge_key));setAmounts(Object.fromEntries(old.map(r=>[r.charge_key,String(Number(r.amount)||0)])))}catch(e:any){setChargeError(e?.message||"Could not load Purchase Charges.")}finally{setChargeLoading(false)}};
 const directSubtotal=useMemo(()=>lines.reduce((s,r)=>s+(Number(r.line_total)||((Number(r.qty)||0)*(Number(r.unit_cost)||0))),0),[lines]);
 const selectedCharges=useMemo(()=>charges.filter(c=>selectedKeys.includes(c.charge_key)),[charges,selectedKeys]);
 const availableCharges=useMemo(()=>charges.filter(c=>!selectedKeys.includes(c.charge_key)),[charges,selectedKeys]);
 const addCharge=()=>{const c=charges.find(x=>x.charge_key===chargeToAdd);if(!c)return;const amount=calculateConfiguredChargeAmount({unit:c.unit,rate:Number(c.default_rate)||0,rows:lines,items,baseAmount:directSubtotal});setSelectedKeys(cur=>cur.includes(c.charge_key)?cur:[...cur,c.charge_key]);setAmounts(cur=>({...cur,[c.charge_key]:String(amount)}));setChargeToAdd("")};
 const saveCharges=async()=>{setChargeSaving(true);setChargeError(null);try{const payload=selectedCharges.map(c=>({charge_key:c.charge_key,amount:Math.max(0,Number(amounts[c.charge_key])||0),quantity:chargeQuantityForUnit(c.unit,lines,items,directSubtotal),rate:Number(c.default_rate)||0})).filter(r=>r.amount>0);const {error}=await supabase.rpc("replace_purchase_order_charges",{p_order_id:orderId,p_charges:payload});if(error)throw error;setChargeOpen(false);onChanged?.()}catch(e:any){setChargeError(e?.message||"Could not save Purchase Charges.")}finally{setChargeSaving(false)}};
 if(checking||!isDraft)return null;
 return <><button type="button" className="btn btn-secondary" onClick={()=>void loadPO()}><BookOpenCheck className="h-4 w-4"/> Add from PO / آرڈر بک سے شامل کریں</button><button type="button" className="btn btn-secondary" onClick={()=>void loadCharges()}><ReceiptText className="h-4 w-4"/> Add Charge / چارج شامل کریں</button>
 {poOpen&&<div className="fixed inset-0 z-[180] flex items-center justify-center bg-slate-950/55 p-4 print:hidden"><div className="flex max-h-[90vh] w-full max-w-6xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl"><div className="flex items-start justify-between border-b p-5"><div><div className="text-lg font-black">Add from PO / Purchase Order Book</div><div className="mt-1 text-xs text-slate-500">Only this supplier's open agreed commitments are shown. Rate remains locked; Qty and Godown can be selected.</div></div><button onClick={()=>setPoOpen(false)}><X className="h-5 w-5"/></button></div><div className="overflow-auto p-5">{poError&&<div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-red-700">{poError}</div>}{poLoading?<div className="py-12 text-center"><Loader2 className="mx-auto animate-spin"/></div>:<div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-xl border"><table className="table w-full"><thead><tr><th>PO</th><th>Item</th><th>Available</th><th>Rate</th><th/></tr></thead><tbody>{poRows.map(r=><tr key={r.id}><td>{r.header.order_no}</td><td>{r.item_name}</td><td>{r.available} {r.uom||""}</td><td>{money(r.agreed_rate)}</td><td><button className="btn" disabled={basket.some(x=>x.commitment.id===r.id)} onClick={()=>addBasket(r)}><Plus className="h-4 w-4"/>Add</button></td></tr>)}</tbody></table></div><div className="space-y-3">{basket.map(entry=><div key={entry.commitment.id} className="rounded-xl border p-3"><div className="flex justify-between"><b>{entry.commitment.item_name}</b><button onClick={()=>setBasket(cur=>cur.filter(x=>x.commitment.id!==entry.commitment.id))}><Trash2 className="h-4 w-4"/></button></div><div className="mt-2 grid grid-cols-2 gap-2"><input className="input" type="number" value={entry.qty} onChange={e=>updateBasket(entry.commitment.id,"qty",e.target.value)}/><SearchableSelect className="input" value={entry.godown_id} onChange={e=>updateBasket(entry.commitment.id,"godown_id",e.target.value)}><option value="">Godown…</option>{godowns.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</SearchableSelect></div></div>)}<button className="btn btn-primary w-full" disabled={poSaving||!basket.length} onClick={()=>void attachPO()}>{poSaving?<Loader2 className="h-4 w-4 animate-spin"/>:<BookOpenCheck className="h-4 w-4"/>}Add to Draft</button></div></div>}</div></div></div>}
 {chargeOpen&&<div className="fixed inset-0 z-[180] flex items-center justify-center bg-slate-950/55 p-4 print:hidden"><div className="w-full max-w-3xl rounded-2xl bg-white shadow-2xl"><div className="flex justify-between border-b p-5"><div><div className="text-lg font-black">Purchase Charges / پرچیز چارجز</div><div className="text-xs text-slate-500">Charge Master is the only source for rates and calculation bases.</div></div><button onClick={()=>setChargeOpen(false)}><X className="h-5 w-5"/></button></div><div className="p-5">{chargeError&&<div className="mb-3 rounded-lg bg-red-50 p-3 text-red-700">{chargeError}</div>}{chargeLoading?<div className="py-10 text-center"><Loader2 className="mx-auto animate-spin"/></div>:<><div className="flex gap-2"><SearchableSelect className="input flex-1" value={chargeToAdd} onChange={e=>setChargeToAdd(e.target.value)}><option value="">Select charge…</option>{availableCharges.map(c=><option key={c.charge_key} value={c.charge_key}>{c.charge_name}{c.charge_name_urdu?` / ${c.charge_name_urdu}`:""}</option>)}</SearchableSelect><button className="btn" onClick={addCharge} disabled={!chargeToAdd}><Plus className="h-4 w-4"/>Add</button></div><div className="mt-4 space-y-2">{selectedCharges.map(c=><div key={c.charge_key} className="grid grid-cols-[1fr_180px_auto] items-center gap-2 rounded-lg border p-3"><div><b>{c.charge_name}</b><div className="text-xs text-slate-500">{c.unit}</div></div><input className="input text-right" type="number" min="0" value={amounts[c.charge_key]||"0"} onChange={e=>setAmounts(cur=>({...cur,[c.charge_key]:e.target.value}))}/><button onClick={()=>setSelectedKeys(cur=>cur.filter(k=>k!==c.charge_key))}><Trash2 className="h-4 w-4"/></button></div>)}</div><div className="mt-4 flex justify-end"><button className="btn btn-primary" disabled={chargeSaving} onClick={()=>void saveCharges()}>{chargeSaving?<Loader2 className="h-4 w-4 animate-spin"/>:<ReceiptText className="h-4 w-4"/>}Save Charges</button></div></>}</div></div></div>}</>;
}
