import { useEffect, useState } from "react";
import { Languages, Loader2, Save } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { NAVILO_LANGUAGES, languageDisplayLabel, type LanguageMode } from "@/lib/languageConfig";

export default function UserLanguagePreference(){
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState<string|null>(null);
  const [useCompanyDefault,setUseCompanyDefault]=useState(true),[mode,setMode]=useState<LanguageMode>("bilingual"),[primary,setPrimary]=useState("en"),[secondary,setSecondary]=useState("ur");
  useEffect(()=>{void(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return;}const{data,error}=await supabase.from("user_language_preferences").select("*").eq("user_id",user.id).maybeSingle();if(error)setError(error.message);if(data){setUseCompanyDefault(data.use_company_default!==false);setMode((data.screen_language_mode||"bilingual") as LanguageMode);setPrimary(data.primary_language||"en");setSecondary(data.secondary_language||"ur");}setLoading(false);})();},[]);
  const save=async()=>{if(mode==="bilingual"&&(!secondary||secondary===primary)){setError("Primary and secondary languages must be different.");return;}setSaving(true);setError(null);const{data:{user}}=await supabase.auth.getUser();if(!user){setError("No signed-in user.");setSaving(false);return;}const{error}=await supabase.from("user_language_preferences").upsert({user_id:user.id,use_company_default:useCompanyDefault,screen_language_mode:mode,primary_language:primary,secondary_language:mode==="bilingual"?secondary:null,updated_at:new Date().toISOString()},{onConflict:"user_id"});setSaving(false);if(error)return setError(error.message);setSaved(true);setTimeout(()=>setSaved(false),2500);};
  if(loading)return <section className="rounded-xl border border-slate-200 p-4"><Loader2 className="h-4 w-4 animate-spin"/></section>;
  return <section className="rounded-xl border border-violet-200 bg-violet-50 p-4"><div className="flex items-center gap-2 font-bold"><Languages size={18}/>My Language Preference / User Override</div><label className="mt-3 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={useCompanyDefault} onChange={e=>setUseCompanyDefault(e.target.checked)}/>Use company default languages</label>{!useCompanyDefault&&<div className="mt-3 grid gap-3 md:grid-cols-3"><Select label="Mode" value={mode} onChange={v=>setMode(v as LanguageMode)} options={[['single','Single Language'],['bilingual','Bilingual / Two Languages']]}/><Select label="Primary" value={primary} onChange={setPrimary} options={NAVILO_LANGUAGES.map(l=>[l.code,languageDisplayLabel(l.code)])}/>{mode==="bilingual"&&<Select label="Secondary" value={secondary} onChange={setSecondary} options={NAVILO_LANGUAGES.filter(l=>l.code!==primary).map(l=>[l.code,languageDisplayLabel(l.code)])}/>}</div>}{error&&<div className="mt-2 text-xs font-semibold text-red-600">{error}</div>}{saved&&<div className="mt-2 text-xs font-semibold text-emerald-700">User language preference saved.</div>}<button type="button" onClick={()=>void save()} disabled={saving} className="btn btn-secondary mt-3">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Save My Language</button></section>;
}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[][]}){return <label className="text-sm font-medium">{label}<select className="input mt-1 w-full" value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
