import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";
import { Modal, PageHeader } from "@/components/ui";
import SearchableSelect from "@/components/SearchableSelect";

type Status="issued"|"loading"|"weighed"|"finalized"|"cancelled";
type GP={id:string;pass_no:string;customer_id:string|null;customer_name:string|null;vehicle_no:string|null;driver_name:string|null;token_notes:string|null;loaded_by_name:string|null;tare_weight:number;gross_weight:number;net_weight:number;status:Status;pass_date:string;created_at:string};
type Line={id?:string;gate_pass_id?:string;item_id:string|null;item_description:string;requested_qty:number;actual_qty:number;uom:string;warehouse_id:string|null;godown_id:string|null;remarks:string|null;warehouse?:{name:string}|null;godown?:{name:string}|null};
type Customer={id:string;name:string;name_urdu:string|null;phone:string|null};
type Item={id:string;sku:string;name:string;name_urdu:string|null;grade:string|null;size:string|null;unit:string|null;warehouse_id:string|null};
type Uom={id:string;name:string;symbol:string};
type Warehouse={id:string;name:string;name_urdu:string|null};
type Godown={id:string;name:string;location:string|null;warehouse_id:string|null};
type Instruction={id:string;name_en:string;name_ur:string|null;is_active:boolean};

const emptyLine=():Line=>({item_id:null,item_description:"",requested_qty:0,actual_qty:0,uom:"kg",warehouse_id:null,godown_id:null,remarks:null});
const statusLabel:Record<Status,string>={issued:"Token Issued",loading:"Loading",weighed:"Kanta Complete",finalized:"Final Gate Pass",cancelled:"Cancelled"};

export default function LoadingUnloading(){
 const [rows,setRows]=useState<GP[]>([]),[lines,setLines]=useState<Record<string,Line[]>>({}),[customers,setCustomers]=useState<Customer[]>([]),[items,setItems]=useState<Item[]>([]),[uoms,setUoms]=useState<Uom[]>([]),[warehouses,setWarehouses]=useState<Warehouse[]>([]),[godowns,setGodowns]=useState<Godown[]>([]),[instructions,setInstructions]=useState<Instruction[]>([]);
 const [loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[createOpen,setCreateOpen]=useState(false),[workOpen,setWorkOpen]=useState(false),[kantaOpen,setKantaOpen]=useState(false),[addInstructionOpen,setAddInstructionOpen]=useState(false),[selected,setSelected]=useState<GP|null>(null);
 const [token,setToken]=useState({customer_id:"",customer_name:"",vehicle_no:"",driver_name:"",token_notes:"",pass_date:new Date().toISOString().slice(0,10)}),[tokenLines,setTokenLines]=useState<Line[]>([emptyLine()]),[workLines,setWorkLines]=useState<Line[]>([]),[loadedBy,setLoadedBy]=useState(""),[tare,setTare]=useState(""),[gross,setGross]=useState(""),[weighRef,setWeighRef]=useState("");
 const [instructionId,setInstructionId]=useState(""),[newInstruction,setNewInstruction]=useState({en:"",ur:""});
 const net=Math.max((Number(gross)||0)-(Number(tare)||0),0);

 const load=useCallback(async()=>{setLoading(true);setError(null);const [g,l,c,i,u,w,d,ins]=await Promise.all([
  supabase.from("gate_passes").select("id,pass_no,customer_id,customer_name,vehicle_no,driver_name,token_notes,loaded_by_name,tare_weight,gross_weight,net_weight,status,pass_date,created_at").order("created_at",{ascending:false}),
  supabase.from("gate_pass_lines").select("id,gate_pass_id,item_id,item_description,requested_qty,actual_qty,uom,warehouse_id,godown_id,remarks,warehouse:warehouses(name),godown:godowns(name)"),
  supabase.from("customers").select("id,name,name_urdu,phone").order("name"),
  supabase.from("items").select("id,sku,name,name_urdu,grade,size,unit,warehouse_id").order("name"),
  supabase.from("uom").select("id,name,symbol").order("name"),
  supabase.from("warehouses").select("id,name,name_urdu").order("name"),
  supabase.from("godowns").select("id,name,location,warehouse_id").order("name"),
  supabase.from("gate_pass_loading_instructions").select("id,name_en,name_ur,is_active").eq("is_active",true).order("name_en")
 ]);
  const e=g.error||l.error||c.error||i.error||u.error||w.error||d.error||ins.error;
  if(e)setError(e.message);else{setRows((g.data||[]) as GP[]);const m:Record<string,Line[]>={};for(const x of (l.data||[]) as any[])(m[x.gate_pass_id]??=[]).push(x);setLines(m);setCustomers((c.data||[]) as Customer[]);setItems((i.data||[]) as Item[]);setUoms((u.data||[]) as Uom[]);setWarehouses((w.data||[]) as Warehouse[]);setGodowns((d.data||[]) as Godown[]);setInstructions((ins.data||[]) as Instruction[])}
  setLoading(false)
 },[]);
 useEffect(()=>{void load()},[load]);

 const nextNo=useMemo(()=>{let n=0;for(const r of rows){const m=r.pass_no?.match(/(\d+)$/);if(m)n=Math.max(n,Number(m[1]))}return `GP-${String(n+1).padStart(4,"0")}`},[rows]);
 const customerDisplay=(gp:GP)=>{const c=customers.find(x=>x.id===gp.customer_id);return [gp.customer_name||c?.name,c?.name_urdu].filter(Boolean).join(" / ")||"—"};
 const lineDisplay=(x:Line)=>{const item=items.find(i=>i.id===x.item_id);return [x.item_description,item?.name_urdu].filter(Boolean).join(" / ")||"—"};
 const itemLabel=(x:Item)=>[x.sku,x.name,x.name_urdu,x.size,x.grade].filter(Boolean).join(" · ");
 const chooseCustomer=(id:string)=>{const c=customers.find(x=>x.id===id);setToken(t=>({...t,customer_id:id,customer_name:c?.name||""}))};
 const chooseItem=(ri:number,id:string)=>{const it=items.find(x=>x.id===id);setTokenLines(v=>v.map((x,i)=>i===ri?{...x,item_id:id||null,item_description:it?[it.name,it.size,it.grade].filter(Boolean).join(" / "):"",uom:it?.unit||uoms[0]?.symbol||"kg",warehouse_id:it?.warehouse_id||null,godown_id:null}:x))};
 const chooseInstruction=(id:string)=>{setInstructionId(id);const x=instructions.find(a=>a.id===id);if(x)setToken(t=>({...t,token_notes:[x.name_en,x.name_ur].filter(Boolean).join(" / ")}))};
 const saveNewInstruction=async()=>{if(!newInstruction.en.trim()){setError("English instruction required hai.");return}const {data,error}=await supabase.from("gate_pass_loading_instructions").insert({instruction:newInstruction.en.trim(),name_en:newInstruction.en.trim(),name_ur:newInstruction.ur.trim()||null}).select("id,name_en,name_ur,is_active").single();if(error){setError(error.message);return}const x=data as Instruction;setInstructions(v=>[...v,x].sort((a,b)=>a.name_en.localeCompare(b.name_en)));setInstructionId(x.id);setToken(t=>({...t,token_notes:[x.name_en,x.name_ur].filter(Boolean).join(" / ")}));setNewInstruction({en:"",ur:""});setAddInstructionOpen(false)};
 const createToken=async(e:React.FormEvent)=>{e.preventDefault();setError(null);const valid=tokenLines.filter(x=>x.item_id&&x.item_description.trim()&&x.requested_qty>0);if(!token.customer_id){setError("Customer master se customer select karein.");return}if(!valid.length){setError("Kam az kam aik material aur quantity required hai.");return}const {data,error}=await supabase.from("gate_passes").insert({pass_no:"AUTO",type:"loading",customer_id:token.customer_id,customer_name:token.customer_name,vehicle_no:token.vehicle_no.trim()||null,driver_name:token.driver_name.trim()||null,token_notes:token.token_notes.trim()||null,status:"issued",pass_date:token.pass_date,tare_weight:0,gross_weight:0,net_weight:0,order_book_header_id:null,sales_order_id:null}).select("id").single();if(error){setError(error.message);return}const {error:le}=await supabase.from("gate_pass_lines").insert(valid.map(x=>({gate_pass_id:data.id,item_id:x.item_id,item_description:x.item_description,requested_qty:x.requested_qty,actual_qty:0,uom:x.uom,remarks:x.remarks||null})));if(le){setError(le.message);return}setCreateOpen(false);setInstructionId("");setToken({customer_id:"",customer_name:"",vehicle_no:"",driver_name:"",token_notes:"",pass_date:new Date().toISOString().slice(0,10)});setTokenLines([emptyLine()]);await load()};
 const openLoading=(gp:GP)=>{setSelected(gp);setLoadedBy(gp.loaded_by_name||"");setWorkLines((lines[gp.id]||[]).map(x=>({...x})));setWorkOpen(true)};
 const saveLoading=async(e:React.FormEvent)=>{e.preventDefault();if(!selected)return;for(const x of workLines){if(x.actual_qty<=0||!x.warehouse_id||!x.godown_id){setError("Har line par Actual Qty, Warehouse aur Godown required hain.");return}const {error}=await supabase.from("gate_pass_lines").update({actual_qty:x.actual_qty,warehouse_id:x.warehouse_id,godown_id:x.godown_id,remarks:x.remarks}).eq("id",x.id);if(error){setError(error.message);return}}const {error}=await supabase.from("gate_passes").update({status:"loading",loaded_by_name:loadedBy.trim()||null,loading_completed_at:new Date().toISOString()}).eq("id",selected.id);if(error)setError(error.message);else{setWorkOpen(false);await load()}};
 const saveKanta=async(e:React.FormEvent)=>{e.preventDefault();if(!selected)return;if(Number(tare)<=0||Number(gross)<=Number(tare)){setError("Valid Tare aur Gross required hai.");return}const {error}=await supabase.from("gate_passes").update({tare_weight:Number(tare),gross_weight:Number(gross),status:"weighed",weighed_at:new Date().toISOString(),weighbridge_reference:weighRef.trim()||null}).eq("id",selected.id);if(error)setError(error.message);else{setKantaOpen(false);await load()}};
 const finalize=async(gp:GP)=>{if(!confirm(`${gp.pass_no} ko Final Gate Pass banana hai?`))return;const {error}=await supabase.from("gate_passes").update({status:"finalized"}).eq("id",gp.id);if(error)setError(error.message);else await load()};
 const printGP=(gp:GP,final=false)=>{const ls=lines[gp.id]||[];const w=window.open("","_blank");if(!w)return;w.document.write(`<html><head><meta charset="UTF-8"><title>${gp.pass_no}</title><style>body{font-family:Arial,"Noto Nastaliq Urdu","Noto Sans Arabic",sans-serif;padding:28px;color:#111827}h1{text-align:center;margin-bottom:8px}p{font-size:13px;line-height:1.8}.ur{direction:rtl;unicode-bidi:plaintext}table{width:100%;border-collapse:collapse;margin-top:18px}th,td{border:1px solid #cbd5e1;padding:8px;font-size:12px;vertical-align:top}th{background:#f1f5f9}.meta{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap}.instructions{padding:10px 12px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px}</style></head><body><h1>${final?"FINAL GATE PASS / حتمی گیٹ پاس":"LOADING TOKEN / لوڈنگ ٹوکن"}</h1><div class="meta"><p><b>Token / GP:</b> ${gp.pass_no}<br><b>Date / تاریخ:</b> ${gp.pass_date}</p><p><b>Customer / کسٹمر:</b> <span dir="auto">${customerDisplay(gp)}</span><br><b>Vehicle / گاڑی:</b> ${gp.vehicle_no||"—"}<br><b>Driver / ڈرائیور:</b> ${gp.driver_name||"—"}</p></div>${gp.token_notes?`<p class="instructions"><b>Instructions / ہدایات:</b> <span dir="auto">${gp.token_notes}</span></p>`:""}<table><tr><th>Material / مال</th><th>Requested / مطلوبہ</th><th>Actual / اصل</th><th>Warehouse / Godown<br>ویئرہاؤس / گودام</th></tr>${ls.map(x=>`<tr><td dir="auto">${lineDisplay(x)}</td><td>${x.requested_qty} ${x.uom}</td><td>${final?`${x.actual_qty} ${x.uom}`:""}</td><td>${final?`${x.warehouse?.name||""} / ${x.godown?.name||""}`:""}</td></tr>`).join("")}</table>${final?`<p><b>Weighbridge / کانٹا:</b> Tare ${gp.tare_weight} kg · Gross ${gp.gross_weight} kg · Net ${gp.net_weight} kg</p><p><b>Loaded By / لوڈر:</b> ${gp.loaded_by_name||"—"}</p>`:""}<script>window.onload=()=>window.print()</script></body></html>`);w.document.close()};

 return <div className="space-y-4"><PageHeader title="Gate Pass / Loading / Kanta" subtitle="Manual Token → Loading → Weighbridge → Final Gate Pass" action={<button className="btn btn-primary" onClick={()=>setCreateOpen(true)}>+ New Loading Token</button>}/>{error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 <div className="grid grid-cols-2 gap-2 md:grid-cols-4">{(["issued","loading","weighed","finalized"] as Status[]).map(s=><div key={s} className="rounded-xl border bg-white p-3"><div className="text-xs text-slate-500">{statusLabel[s]}</div><div className="text-2xl font-bold">{rows.filter(r=>r.status===s).length}</div></div>)}</div>
 <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="p-3">Token / GP</th><th>Customer / کسٹمر</th><th>Vehicle / گاڑی</th><th>Material / مال</th><th>Status</th><th>Action</th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="p-5">Loading…</td></tr>:rows.map(gp=><tr key={gp.id} className="border-t"><td className="p-3 font-semibold">{gp.pass_no}</td><td dir="auto">{customerDisplay(gp)}</td><td>{gp.vehicle_no||"—"}</td><td>{(lines[gp.id]||[]).map(x=><div key={x.id||x.item_description} dir="auto">{lineDisplay(x)}</div>)}</td><td>{statusLabel[gp.status]}</td><td><div className="flex gap-1"><button className="btn btn-secondary" onClick={()=>printGP(gp,gp.status==="finalized")}>{gp.status==="finalized"?"Print Final GP":"Print Token"}</button>{gp.status==="issued"&&<button className="btn btn-primary" onClick={()=>openLoading(gp)}>Loading</button>}{gp.status==="loading"&&<button className="btn btn-primary" onClick={()=>{setSelected(gp);setTare(String(gp.tare_weight||""));setGross(String(gp.gross_weight||""));setKantaOpen(true)}}>Kanta</button>}{gp.status==="weighed"&&<button className="btn btn-primary" onClick={()=>finalize(gp)}>Generate Final GP</button>}</div></td></tr>)}</tbody></table></div>

 <Modal open={createOpen} onClose={()=>setCreateOpen(false)} title="New Loading Token" panelClassName="!max-w-6xl !w-[96vw]"><form onSubmit={createToken} className="space-y-4"><div className="grid gap-3 md:grid-cols-4"><div><label className="label">Token / GP No.</label><input className="input bg-slate-100" value={`${nextNo} (Auto)`} readOnly/></div><div><label className="label">Customer / Party</label><SearchableSelect className="input" value={token.customer_id} onChange={e=>chooseCustomer(e.target.value)} searchPlaceholder="Search customer..."><option value="">Select Customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}{c.name_urdu?` / ${c.name_urdu}`:""}</option>)}</SearchableSelect></div><div><label className="label">Vehicle No.</label><input className="input" value={token.vehicle_no} onChange={e=>setToken({...token,vehicle_no:e.target.value})}/></div><div><label className="label">Date</label><input type="date" className="input" value={token.pass_date} onChange={e=>setToken({...token,pass_date:e.target.value})}/></div><div><label className="label">Driver</label><input className="input" value={token.driver_name} onChange={e=>setToken({...token,driver_name:e.target.value})}/></div>
 <div className="md:col-span-3"><div className="mb-1 flex items-center justify-between"><label className="label">Token Instructions / Notes — English / اردو</label><button type="button" className="text-xs font-semibold text-blue-600" onClick={()=>setAddInstructionOpen(true)}>+ Add New</button></div><SearchableSelect className="input" value={instructionId} onChange={e=>chooseInstruction(e.target.value)} searchPlaceholder="Search English or Urdu instruction..."><option value="">Search / Select Instruction</option>{instructions.map(x=><option key={x.id} value={x.id}>{x.name_en}{x.name_ur?` / ${x.name_ur}`:""}</option>)}</SearchableSelect><textarea className="input mt-2 min-h-20" dir="auto" placeholder="Selected instruction appears here; extra note bhi likh sakte hain..." value={token.token_notes} onChange={e=>setToken({...token,token_notes:e.target.value})}/></div></div>
 <div className="space-y-2">{tokenLines.map((x,i)=><div key={i} className="grid grid-cols-12 gap-2"><div className="col-span-5"><SearchableSelect className="input" value={x.item_id||""} onChange={e=>chooseItem(i,e.target.value)} searchPlaceholder="Search item..."><option value="">Select Item</option>{items.map(it=><option key={it.id} value={it.id}>{itemLabel(it)}</option>)}</SearchableSelect></div><input className="input col-span-2" type="number" step="any" placeholder="Qty" value={x.requested_qty||""} onChange={e=>setTokenLines(v=>v.map((a,j)=>j===i?{...a,requested_qty:Number(e.target.value)}:a))}/><div className="col-span-2"><SearchableSelect className="input" value={x.uom} onChange={e=>setTokenLines(v=>v.map((a,j)=>j===i?{...a,uom:e.target.value}:a))}>{uoms.map(u=><option key={u.id} value={u.symbol}>{u.symbol} · {u.name}</option>)}</SearchableSelect></div><input className="input col-span-3" placeholder="Remarks" value={x.remarks||""} onChange={e=>setTokenLines(v=>v.map((a,j)=>j===i?{...a,remarks:e.target.value}:a))}/></div>)}</div><div className="flex justify-between"><button type="button" className="btn btn-secondary" onClick={()=>setTokenLines(v=>[...v,emptyLine()])}>+ Add Material</button><button className="btn btn-primary">Issue & Save Token</button></div></form></Modal>
 <Modal open={addInstructionOpen} onClose={()=>setAddInstructionOpen(false)} title="Add Loading Instruction / لوڈنگ ہدایت"><div className="space-y-3"><div><label className="label">English</label><input className="input" value={newInstruction.en} onChange={e=>setNewInstruction({...newInstruction,en:e.target.value})}/></div><div><label className="label">Urdu / اردو</label><input className="input text-right" dir="rtl" value={newInstruction.ur} onChange={e=>setNewInstruction({...newInstruction,ur:e.target.value})}/></div><div className="flex justify-end"><button type="button" className="btn btn-primary" onClick={()=>void saveNewInstruction()}>Save & Use / محفوظ کریں</button></div></div></Modal>
 <Modal open={workOpen} onClose={()=>setWorkOpen(false)} title={`Loading — ${selected?.pass_no||""}`} panelClassName="!max-w-7xl !w-[97vw]"><form onSubmit={saveLoading} className="space-y-4"><input className="input max-w-md" placeholder="Loaded By / Loader Name" value={loadedBy} onChange={e=>setLoadedBy(e.target.value)} required/>{workLines.map((x,i)=><div key={x.id||i} className="grid grid-cols-12 gap-2"><div className="col-span-3 p-2" dir="auto">{lineDisplay(x)}</div><input className="input col-span-2" type="number" step="any" placeholder="Actual Qty" value={x.actual_qty||""} onChange={e=>setWorkLines(v=>v.map((a,j)=>j===i?{...a,actual_qty:Number(e.target.value)}:a))}/><div className="col-span-2"><SearchableSelect className="input" value={x.warehouse_id||""} onChange={e=>setWorkLines(v=>v.map((a,j)=>j===i?{...a,warehouse_id:e.target.value||null,godown_id:null}:a))}><option value="">Warehouse</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}{w.name_urdu?` / ${w.name_urdu}`:""}</option>)}</SearchableSelect></div><div className="col-span-2"><SearchableSelect className="input" value={x.godown_id||""} onChange={e=>setWorkLines(v=>v.map((a,j)=>j===i?{...a,godown_id:e.target.value||null}:a))}><option value="">Godown</option>{godowns.filter(g=>g.warehouse_id===x.warehouse_id).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</SearchableSelect></div><input className="input col-span-3" value={x.remarks||""} onChange={e=>setWorkLines(v=>v.map((a,j)=>j===i?{...a,remarks:e.target.value}:a))}/></div>)}<div className="flex justify-end"><button className="btn btn-primary">Save Loading & Send to Kanta</button></div></form></Modal>
 <Modal open={kantaOpen} onClose={()=>setKantaOpen(false)} title={`Kanta / Weighbridge — ${selected?.pass_no||""}`}><form onSubmit={saveKanta} className="space-y-3"><div className="grid grid-cols-3 gap-3"><input className="input" type="number" placeholder="Tare kg" value={tare} onChange={e=>setTare(e.target.value)}/><input className="input" type="number" placeholder="Gross kg" value={gross} onChange={e=>setGross(e.target.value)}/><input className="input bg-slate-100" value={`${net} kg Net`} readOnly/></div><input className="input" placeholder="Kanta Slip / Reference" value={weighRef} onChange={e=>setWeighRef(e.target.value)}/><div className="flex justify-end"><button className="btn btn-primary">Save Kanta</button></div></form></Modal></div>;
}
