import { useCallback, useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { StockMovement, Item } from "@/types";
import DataTable, { Column } from "@/components/DataTable";
import { PageHeader, Modal, ErrorBanner, formatDate } from "@/components/ui";
import { Printer, FileSpreadsheet, ArrowRightLeft } from "lucide-react";

interface WarehouseOption{id:string;name:string}
interface GodownOption{id:string;name:string;warehouse_id:string}
type MovementRow=StockMovement&{warehouse_id?:string|null;godown_id?:string|null;item?:Item|null;reason?:string|null;remarks?:string|null;adjustment_action?:string|null;approved_by_name?:string|null;entered_by_name?:string|null;previous_qty?:number|null;resulting_qty?:number|null;source_type?:string|null};

export default function StockMovements(){
 const[rows,setRows]=useState<MovementRow[]>([]),[items,setItems]=useState<Item[]>([]),[warehouses,setWarehouses]=useState<WarehouseOption[]>([]),[godowns,setGodowns]=useState<GodownOption[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[transferModalOpen,setTransferModalOpen]=useState(false);
 const[transferForm,setTransferForm]=useState({item_id:"",warehouse_id:"",from_godown_id:"",to_godown_id:"",qty:"0",reference:""});
 const fetchRows=useCallback(async()=>{setLoading(true);const[movementRes,itemRes,warehouseRes,godownRes]=await Promise.all([
  supabase.from("stock_movements").select("*").order("created_at",{ascending:false}),supabase.from("items").select("*").order("name"),supabase.from("warehouses").select("id,name").order("name"),supabase.from("godowns").select("id,name,warehouse_id").order("name")]);
  if(movementRes.error){setError(movementRes.error.message);setRows([]);setLoading(false);return}if(itemRes.error||warehouseRes.error||godownRes.error){setError(itemRes.error?.message||warehouseRes.error?.message||godownRes.error?.message||"Unable to load stock movement details");setLoading(false);return}
  const im=new Map((itemRes.data??[]).map((i:any)=>[i.id,i]));setItems((itemRes.data??[]) as Item[]);setWarehouses((warehouseRes.data??[]).map((w:any)=>({id:String(w.id),name:String(w.name??"")})));setGodowns((godownRes.data??[]).map((g:any)=>({id:String(g.id),name:String(g.name??""),warehouse_id:String(g.warehouse_id??"")})));setRows((movementRes.data??[]).map((r:any)=>({...r,item:im.get(r.item_id)??null})) as MovementRow[]);setError(null);setLoading(false)},[]);
 useEffect(()=>{void fetchRows()},[fetchRows]);
 const warehouseGodowns=(wid:string)=>godowns.filter(g=>String(g.warehouse_id)===String(wid));
 const openTransfer=()=>{if(!warehouses.length)return setError("No warehouse is available.");const wid=warehouses[0].id,list=warehouseGodowns(wid);if(list.length<2)return setError("At least two godowns are required in the selected warehouse for transfer.");setError(null);setTransferForm({item_id:"",warehouse_id:wid,from_godown_id:list[0].id,to_godown_id:list[1].id,qty:"0",reference:""});setTransferModalOpen(true)};
 const handleTransferSubmit=async(e:React.FormEvent)=>{e.preventDefault();setError(null);const qty=Number(transferForm.qty),from=godowns.find(g=>g.id===transferForm.from_godown_id),to=godowns.find(g=>g.id===transferForm.to_godown_id);if(!transferForm.item_id)return setError("Please select an item.");if(!from||!to||from.id===to.id)return setError("Select different source and destination godowns.");if(!Number.isFinite(qty)||qty<=0)return setError("Transfer quantity must be greater than zero.");const{data:sourceStock,error:stockError}=await supabase.from("warehouse_stock").select("quantity").eq("item_id",transferForm.item_id).eq("warehouse_id",transferForm.warehouse_id).eq("godown_id",from.id).maybeSingle();if(stockError)return setError(stockError.message);if(qty>Number(sourceStock?.quantity??0))return setError(`Insufficient stock in source godown. Available: ${Number(sourceStock?.quantity??0).toLocaleString()}`);const{error:transferError}=await supabase.rpc("transfer_stock_v2",{p_item_id:transferForm.item_id,p_warehouse_id:transferForm.warehouse_id,p_from_godown_id:from.id,p_to_godown_id:to.id,p_qty:Number(qty.toFixed(3)),p_reference:transferForm.reference.trim()||null});if(transferError)return setError(transferError.message);setTransferModalOpen(false);await fetchRows()};
 const handlePrint=()=>window.print();
 const csvEsc=(v:unknown)=>`"${String(v??"").replace(/"/g,'""')}"`;
 const handleExportExcel=()=>{let csv="Date,Warehouse,Godown,Item,Type,Action,Quantity,Reason,Reference,Approved By,Entered By,Previous Qty,Resulting Qty,Remarks\r\n";rows.forEach((r:any)=>{const wh=warehouses.find(w=>w.id===r.warehouse_id)?.name??"",gd=godowns.find(g=>g.id===r.godown_id)?.name??r.godown??"",it=r.item?.name??"";csv+=[r.created_at?new Date(r.created_at).toLocaleString():"",wh,gd,it,r.type,r.adjustment_action??"",r.qty,r.reason??"",r.reference??"",r.approved_by_name??"",r.entered_by_name??"",r.previous_qty??"",r.resulting_qty??"",r.remarks??""].map(csvEsc).join(",")+"\r\n"});const blob=new Blob([csv],{type:"text/csv;charset=utf-8;"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="Stock_Movements.csv";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)};
 const typeColors:Record<string,string>={in:"bg-success-100 text-success-700",out:"bg-error-100 text-error-700",adjust:"bg-warning-100 text-warning-700",purchase_return:"bg-purple-100 text-purple-700",sale_return:"bg-blue-100 text-blue-700"};
 const columns:Column<MovementRow>[]=[
  {key:"created_at",label:"Date / تاریخ",render:r=>formatDate(r.created_at)},
  {key:"warehouse_id",label:"Warehouse / ویئرہاؤس",render:(r:any)=>warehouses.find(w=>w.id===r.warehouse_id)?.name??"—"},
  {key:"godown",label:"Godown / گودام",render:(r:any)=>godowns.find(g=>g.id===r.godown_id)?.name??r.godown??"—"},
  {key:"item",label:"Item / آئٹم",render:(r:any)=><span className="font-medium text-slate-900">{r.item?.name??"—"}</span>},
  {key:"type",label:"Type / قسم",render:(r:any)=><span className={`badge ${typeColors[r.type]??"bg-slate-100 text-slate-700"}`}>{r.type==="adjust"&&r.adjustment_action?`adjust ${r.adjustment_action}`:String(r.type).replace("_"," ")}</span>},
  {key:"qty",label:"Quantity / مقدار",render:(r:any)=>{const neg=r.type==="out"||r.type==="purchase_return"||(r.type==="adjust"&&r.adjustment_action==="remove");return <span className={neg?"font-medium text-error-600":"font-medium text-success-600"}>{neg?"-":"+"}{Number(r.qty).toLocaleString()}</span>}},
  {key:"reason",label:"Reason / وجہ",render:(r:any)=>r.reason??(r.source_type==="source_document"?"Source Document":"—")},
  {key:"reference",label:"Reference / حوالہ",render:(r:any)=>r.reference??"—"},
  {key:"approved_by_name",label:"Approved By / منظوری",render:(r:any)=>r.approved_by_name??"—"},
  {key:"entered_by_name",label:"Entered By / اندراج",render:(r:any)=>r.entered_by_name??"—"},
  {key:"resulting_qty",label:"Stock Before → After",render:(r:any)=>r.previous_qty==null||r.resulting_qty==null?"—":`${Number(r.previous_qty).toLocaleString()} → ${Number(r.resulting_qty).toLocaleString()}`},
 ];
 return <div className="space-y-6"><style>{`@media print{body *{visibility:hidden}#printable-movements,#printable-movements *{visibility:visible}#printable-movements{position:absolute;left:0;top:0;width:100%}.no-print{display:none!important}}`}</style><div id="printable-movements" className="space-y-6"><div className="flex flex-col items-start justify-between gap-4 rounded-xl border border-slate-200 bg-white p-6 shadow-sm sm:flex-row sm:items-center"><PageHeader title="Stock Movements / اسٹاک موومنٹس" subtitle="Source movements, controlled adjustments and godown transfers with audit trail / مکمل اسٹاک آڈٹ ٹریل"/><div className="no-print flex flex-wrap items-center gap-2"><button type="button" onClick={handleExportExcel} className="flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-medium text-white"><FileSpreadsheet className="h-4 w-4"/>Export Excel</button><button type="button" onClick={handlePrint} className="flex items-center gap-2 rounded-lg bg-slate-800 px-4 py-2 text-sm font-medium text-white"><Printer className="h-4 w-4"/>Print</button><button type="button" onClick={openTransfer} className="flex items-center gap-2 rounded-lg bg-amber-600 px-4 py-2 text-sm font-medium text-white"><ArrowRightLeft className="h-4 w-4"/>Transfer Stock</button></div></div>{error&&<ErrorBanner message={error}/>}<DataTable columns={columns} rows={rows} loading={loading} emptyMessage="No stock movements yet."/></div>
 <Modal open={transferModalOpen} title="Transfer Stock Between Godowns / گوداموں کے درمیان اسٹاک منتقل کریں" onClose={()=>setTransferModalOpen(false)}><form onSubmit={handleTransferSubmit} className="space-y-4"><div><label className="label">Item / آئٹم</label><select className="input" required value={transferForm.item_id} onChange={e=>setTransferForm({...transferForm,item_id:e.target.value})}><option value="">— Select item —</option>{items.map(item=><option key={item.id} value={item.id}>{item.name} ({item.sku})</option>)}</select></div><div><label className="label">Warehouse / ویئرہاؤس</label><select className="input" required value={transferForm.warehouse_id} onChange={e=>{const wid=e.target.value,list=warehouseGodowns(wid);setTransferForm({...transferForm,warehouse_id:wid,from_godown_id:list[0]?.id??"",to_godown_id:list[1]?.id??""})}}><option value="">— Select warehouse —</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></div><div className="grid grid-cols-2 gap-4"><div><label className="label">From Godown</label><select className="input" required value={transferForm.from_godown_id} onChange={e=>setTransferForm({...transferForm,from_godown_id:e.target.value})}>{warehouseGodowns(transferForm.warehouse_id).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></div><div><label className="label">To Godown</label><select className="input" required value={transferForm.to_godown_id} onChange={e=>setTransferForm({...transferForm,to_godown_id:e.target.value})}>{warehouseGodowns(transferForm.warehouse_id).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></div></div><div><label className="label">Quantity / مقدار</label><input className="input" type="number" min="0.001" step="0.001" required value={transferForm.qty} onChange={e=>setTransferForm({...transferForm,qty:e.target.value})}/></div><div><label className="label">Reference / حوالہ</label><input className="input" value={transferForm.reference} onChange={e=>setTransferForm({...transferForm,reference:e.target.value})}/></div><div className="flex justify-end gap-3"><button type="button" onClick={()=>setTransferModalOpen(false)} className="btn-secondary">Cancel</button><button type="submit" className="btn-primary">Transfer Stock</button></div></form></Modal></div>
}
