import { useCallback, useEffect, useState } from "react";
import { KeyRound, Loader2 } from "lucide-react";
import { supabase } from "@/lib/supabase";

const roles=["company_owner","admin","accounts","sales","purchase","store","production","viewer"];
type Unit={id:string;name:string;code:string;unit_type:string;is_active:boolean};

export default function BusinessWorkspaceLoginControl({companyId}:{companyId:string}){
 const[units,setUnits]=useState<Unit[]>([]),[unitId,setUnitId]=useState(""),[fullName,setFullName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[role,setRole]=useState("viewer"),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);const{data,error}=await supabase.from("business_units").select("id,name,code,unit_type,is_active").eq("company_id",companyId).eq("is_active",true).order("is_default",{ascending:false}).order("name");if(error)setError(error.message);const rows=(data??[]) as Unit[];setUnits(rows);setUnitId(x=>rows.some(r=>r.id===x)?x:(rows[0]?.id??""));setLoading(false)},[companyId]);
 useEffect(()=>{void load()},[load]);
 const create=async()=>{if(!unitId||!email.trim()||password.length<8){setError("Business workspace, email and minimum 8 character password are required.");return}setSaving(true);setError("");setMessage("");try{const{data,error}=await supabase.functions.invoke("platform-admin",{body:{action:"create_user",company_id:companyId,business_unit_id:unitId,full_name:fullName.trim(),email:email.trim(),password,role}});if(error)throw error;if(data?.error)throw new Error(data.error);const unit=units.find(x=>x.id===unitId);setMessage(`${unit?.name??"Business"} dedicated login created. This ID opens only this business workspace.`);setFullName("");setEmail("");setPassword("");setRole("viewer")}catch(e){setError(e instanceof Error?e.message:"Could not create workspace login.")}finally{setSaving(false)}};
 return <section className="rounded-xl border border-blue-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-2"><KeyRound className="h-5 w-5 text-blue-700"/><div><h2 className="font-semibold text-slate-900">Dedicated Business Login IDs</h2><p className="text-xs text-slate-500">Create a separate login for Steel, Transport or any other business. Each ID is locked to its assigned workspace, so separate IDs can stay logged in at the same time in separate browser profiles/devices.</p></div></div>{error&&<div className="mt-3 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>}{message&&<div className="mt-3 rounded-lg bg-emerald-50 px-3 py-2 text-sm text-emerald-700">{message}</div>}{loading?<div className="mt-4 flex items-center gap-2 text-sm"><Loader2 className="h-4 w-4 animate-spin"/>Loading workspaces...</div>:<><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><select className="input" value={unitId} onChange={e=>setUnitId(e.target.value)}>{units.map(u=><option key={u.id} value={u.id}>{u.name} ({u.code})</option>)}</select><input className="input" placeholder="Full name" value={fullName} onChange={e=>setFullName(e.target.value)}/><input className="input" type="email" placeholder="Business login email" value={email} onChange={e=>setEmail(e.target.value)}/><input className="input" type="password" placeholder="Temporary password" value={password} onChange={e=>setPassword(e.target.value)}/><select className="input" value={role} onChange={e=>setRole(e.target.value)}>{roles.map(r=><option key={r} value={r}>{r}</option>)}</select></div><button className="btn-primary mt-3" disabled={saving||!unitId} onClick={()=>void create()}>{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<KeyRound className="h-4 w-4"/>}Create Dedicated Business Login</button>{units.length===0&&<div className="mt-2 text-xs text-slate-500">Create a business/service first, then create its login ID.</div>}</>}</section>;
}