import { useCallback, useEffect, useMemo, useState } from "react";
import { BriefcaseBusiness, Loader2, Plus } from "lucide-react";
import { supabase } from "@/lib/supabase";

const moduleKeys=["dashboard","master","sales","purchase","inventory","production","accounting","reports","settings"] as const;
const unitTypes=["steel","transport","retail","fuel","construction","custom"] as const;
type Unit={id:string;company_id:string;code:string;name:string;unit_type:string;is_active:boolean;is_default:boolean};
type UnitModule={id:string;business_unit_id:string;module_key:string;enabled:boolean};
export default function BusinessUnitControl({companyId,onSaved}:{companyId:string;onSaved?:()=>void|Promise<void>}){
 const[units,setUnits]=useState<Unit[]>([]),[mods,setMods]=useState<UnitModule[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const[name,setName]=useState(""),[code,setCode]=useState(""),[type,setType]=useState<(typeof unitTypes)[number]>("custom");
 const load=useCallback(async()=>{setLoading(true);setError("");const[u,m]=await Promise.all([supabase.from("business_units").select("*").eq("company_id",companyId).order("is_default",{ascending:false}).order("name"),supabase.from("business_unit_modules").select("id,business_unit_id,module_key,enabled").eq("company_id",companyId)]);const e=u.error||m.error;if(e)setError(e.message);setUnits((u.data??[]) as Unit[]);setMods((m.data??[]) as UnitModule[]);setLoading(false)},[companyId]);
 useEffect(()=>{void load()},[load]);
 const enabledByUnit=useMemo(()=>{const map=new Map<string,Set<string>>();mods.filter(x=>x.enabled).forEach(x=>{const s=map.get(x.business_unit_id)??new Set<string>();s.add(x.module_key);map.set(x.business_unit_id,s)});return map},[mods]);
 const create=async()=>{if(!name.trim()||!code.trim()){setError("Business unit name and code are required.");return}setSaving(true);setError("");try{const{data:u,error:e}=await supabase.from("business_units").insert({company_id:companyId,name:name.trim(),code:code.trim().toUpperCase(),unit_type:type,is_active:true,is_default:false}).select("id").single();if(e)throw e;const defaults=type==="steel"?[...moduleKeys]:["dashboard","master","accounting","reports","settings"];const{error:me}=await supabase.from("business_unit_modules").insert(defaults.map(module_key=>({business_unit_id:u.id,company_id:companyId,module_key,enabled:true})));if(me)throw me;setName("");setCode("");setType("custom");await load();await onSaved?.()}catch(e){setError(e instanceof Error?e.message:"Could not create business unit.")}finally{setSaving(false)}};
 const patchUnit=async(unit:Unit,patch:Partial<Unit>)=>{setSaving(true);setError("");try{const{error:e}=await supabase.from("business_units").update(patch).eq("id",unit.id);if(e)throw e;await load();await onSaved?.()}catch(e){setError(e instanceof Error?e.message:"Could not update business unit.")}finally{setSaving(false)}};
 const toggleModule=async(unit:Unit,moduleKey:string)=>{setSaving(true);setError("");try{const enabled=enabledByUnit.get(unit.id)?.has(moduleKey)??false;const existing=mods.find(x=>x.business_unit_id===unit.id&&x.module_key===moduleKey);const result=existing?await supabase.from("business_unit_modules").update({enabled:!enabled}).eq("id",existing.id):await supabase.from("business_unit_modules").insert({business_unit_id:unit.id,company_id:companyId,module_key:moduleKey,enabled:true});if(result.error)throw result.error;await load();await onSaved?.()}catch(e){setError(e instanceof Error?e.message:"Could not update module access.")}finally{setSaving(false)}};
 if(loading)return <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><Loader2 className="h-5 w-5 animate-spin"/></section>;
 return <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-2"><BriefcaseBusiness className="h-5 w-5 text-blue-700"/><div><h2 className="font-semibold text-slate-900">Business Units / Services</h2><p className="text-xs text-slate-500">Steel, Transport, Retail, Fuel or any future service. Each unit has separate module access.</p></div></div>{error&&<div className="mt-3 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>}
 <div className="mt-4 grid gap-3 sm:grid-cols-4"><input className="input" placeholder="Business unit name" value={name} onChange={e=>setName(e.target.value)}/><input className="input" placeholder="Code e.g. TRANSPORT" value={code} onChange={e=>setCode(e.target.value)}/><select className="input" value={type} onChange={e=>setType(e.target.value as typeof type)}>{unitTypes.map(x=><option key={x} value={x}>{x.replace(/\b\w/g,c=>c.toUpperCase())}</option>)}</select><button className="btn-primary" disabled={saving} onClick={()=>void create()}><Plus className="h-4 w-4"/>Add Service</button></div>
 <div className="mt-4 space-y-3">{units.map(unit=><div key={unit.id} className="rounded-xl border border-slate-200 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="font-black text-slate-900">{unit.name} <span className="text-xs font-bold text-slate-400">({unit.code})</span>{unit.is_default&&<span className="ml-2 rounded bg-blue-50 px-2 py-0.5 text-[10px] font-black uppercase text-blue-700">Default</span>}</div><div className="text-xs text-slate-500">{unit.unit_type} · {unit.is_active?"Active":"Disabled"}</div></div><button className="btn-secondary" disabled={saving||unit.is_default} onClick={()=>void patchUnit(unit,{is_active:!unit.is_active})}>{unit.is_active?"Disable":"Enable"}</button></div><div className="mt-3 flex flex-wrap gap-2">{moduleKeys.map(k=>{const on=enabledByUnit.get(unit.id)?.has(k)??false;return <button key={k} disabled={saving} onClick={()=>void toggleModule(unit,k)} className={`rounded-full border px-2.5 py-1 text-xs font-bold ${on?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-slate-200 bg-slate-50 text-slate-400"}`}>{k}: {on?"ON":"OFF"}</button>})}</div></div>)}</div></section>
}
