import { useCallback, useEffect, useMemo, useState } from "react";
import { Building2, Calculator, Layers3, Loader2, Plus, Save, ShieldCheck } from "lucide-react";
import { supabase } from "@/lib/supabase";

type Props={companyId:string};
type Policy={company_id:string;base_currency:string;inventory_valuation_method:string;allow_negative_stock:boolean;require_document_approval:boolean;backdate_days:number;fiscal_year_start_month:number;decimal_places:number;enforce_period_lock:boolean;enforce_balanced_journals:boolean;enforce_posted_immutability:boolean};
type Unit={id:string;name:string;code:string};
type Location={id:string;business_unit_id:string|null;code:string;name:string;location_type:string;is_active:boolean};
type Dimension={id:string;business_unit_id:string|null;dimension_type:string;code:string;name:string;is_active:boolean};
const defaultPolicy=(companyId:string):Policy=>({company_id:companyId,base_currency:"PKR",inventory_valuation_method:"weighted_average",allow_negative_stock:false,require_document_approval:false,backdate_days:30,fiscal_year_start_month:7,decimal_places:2,enforce_period_lock:true,enforce_balanced_journals:true,enforce_posted_immutability:true});
export default function CoreAccountingControl({companyId}:Props){
 const[policy,setPolicy]=useState<Policy>(defaultPolicy(companyId));const[units,setUnits]=useState<Unit[]>([]),[locations,setLocations]=useState<Location[]>([]),[dimensions,setDimensions]=useState<Dimension[]>([]);const[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[saved,setSaved]=useState("");
 const[loc,setLoc]=useState({business_unit_id:"",code:"",name:"",location_type:"branch"});const[dim,setDim]=useState({business_unit_id:"",dimension_type:"cost_center",code:"",name:""});
 const load=useCallback(async()=>{setLoading(true);setError("");const[p,u,l,d]=await Promise.all([supabase.from("company_accounting_policies").select("company_id,base_currency,inventory_valuation_method,allow_negative_stock,require_document_approval,backdate_days,fiscal_year_start_month,decimal_places,enforce_period_lock,enforce_balanced_journals,enforce_posted_immutability").eq("company_id",companyId).maybeSingle(),supabase.from("business_units").select("id,name,code").eq("company_id",companyId).eq("is_active",true).order("name"),supabase.from("operating_locations").select("id,business_unit_id,code,name,location_type,is_active").eq("company_id",companyId).order("code"),supabase.from("accounting_dimensions").select("id,business_unit_id,dimension_type,code,name,is_active").eq("company_id",companyId).order("dimension_type").order("code")]);const first=p.error||u.error||l.error||d.error;if(first)setError(first.message);setPolicy((p.data as Policy|null)??defaultPolicy(companyId));setUnits((u.data??[]) as Unit[]);setLocations((l.data??[]) as Location[]);setDimensions((d.data??[]) as Dimension[]);setLoading(false)},[companyId]);useEffect(()=>{void load()},[load]);
 const unitMap=useMemo(()=>new Map(units.map(u=>[u.id,`${u.name} (${u.code})`])),[units]);
 const savePolicy=async()=>{setBusy(true);setError("");setSaved("");try{const{error:e}=await supabase.from("company_accounting_policies").upsert({...policy,company_id:companyId,updated_at:new Date().toISOString()},{onConflict:"company_id"});if(e)throw e;setSaved("Core accounting policy saved.")}catch(e){setError(e instanceof Error?e.message:"Could not save accounting policy.")}finally{setBusy(false)}};
 const addLocation=async()=>{if(!loc.code.trim()||!loc.name.trim())return;setBusy(true);setError("");try{const{error:e}=await supabase.from("operating_locations").insert({company_id:companyId,business_unit_id:loc.business_unit_id||null,code:loc.code.trim().toUpperCase(),name:loc.name.trim(),location_type:loc.location_type});if(e)throw e;setLoc({business_unit_id:"",code:"",name:"",location_type:"branch"});await load()}catch(e){setError(e instanceof Error?e.message:"Could not add location.")}finally{setBusy(false)}};
 const addDimension=async()=>{if(!dim.code.trim()||!dim.name.trim())return;setBusy(true);setError("");try{const{error:e}=await supabase.from("accounting_dimensions").insert({company_id:companyId,business_unit_id:dim.business_unit_id||null,dimension_type:dim.dimension_type,code:dim.code.trim().toUpperCase(),name:dim.name.trim()});if(e)throw e;setDim({business_unit_id:"",dimension_type:"cost_center",code:"",name:""});await load()}catch(e){setError(e instanceof Error?e.message:"Could not add accounting dimension.")}finally{setBusy(false)}};
 const toggle=async(table:"operating_locations"|"accounting_dimensions",id:string,is_active:boolean)=>{setBusy(true);setError("");try{const{error:e}=await supabase.from(table).update({is_active:!is_active,updated_at:new Date().toISOString()}).eq("id",id).eq("company_id",companyId);if(e)throw e;await load()}catch(e){setError(e instanceof Error?e.message:"Update failed.")}finally{setBusy(false)}};
 if(loading)return <section className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex items-center text-sm text-slate-500"><Loader2 className="mr-2 h-4 w-4 animate-spin"/>Loading core accounting controls...</div></section>;
 return <section className="rounded-xl border bg-white p-4 shadow-sm"><div className="mb-4 flex items-start gap-2"><ShieldCheck className="mt-0.5 h-5 w-5 text-blue-700"/><div><h2 className="font-semibold text-slate-900">Core Accounting & Multi-Service Policy</h2><p className="text-xs text-slate-500">Company-wide rules used by Steel, Transport, Retail, Fuel and future services.</p></div></div>{error&&<div className="mb-3 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>}{saved&&<div className="mb-3 rounded-lg bg-emerald-50 px-3 py-2 text-sm text-emerald-700">{saved}</div>}
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-semibold text-slate-600">Base Currency<input className="input mt-1 w-full" value={policy.base_currency} onChange={e=>setPolicy({...policy,base_currency:e.target.value.toUpperCase()})}/></label><label className="text-xs font-semibold text-slate-600">Inventory Valuation<select className="input mt-1 w-full" value={policy.inventory_valuation_method} onChange={e=>setPolicy({...policy,inventory_valuation_method:e.target.value})}><option value="weighted_average">Weighted Average</option><option value="fifo">FIFO</option></select></label><label className="text-xs font-semibold text-slate-600">Backdate Limit (days)<input className="input mt-1 w-full" type="number" min="0" value={policy.backdate_days} onChange={e=>setPolicy({...policy,backdate_days:Math.max(0,Number(e.target.value)||0)})}/></label><label className="text-xs font-semibold text-slate-600">Fiscal Year Starts<select className="input mt-1 w-full" value={policy.fiscal_year_start_month} onChange={e=>setPolicy({...policy,fiscal_year_start_month:Number(e.target.value)})}>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{new Date(2000,i,1).toLocaleString("en",{month:"long"})}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">Decimal Places<input className="input mt-1 w-full" type="number" min="0" max="6" value={policy.decimal_places} onChange={e=>setPolicy({...policy,decimal_places:Math.min(6,Math.max(0,Number(e.target.value)||0))})}/></label></div>
 <div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{[["enforce_balanced_journals","Balanced journals mandatory"],["enforce_posted_immutability","Posted entries immutable"],["enforce_period_lock","Closed period lock"],["require_document_approval","Document approvals"],["allow_negative_stock","Allow negative stock"]].map(([key,label])=><label key={key} className="flex items-center gap-2 rounded-lg border bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-700"><input type="checkbox" checked={Boolean(policy[key as keyof Policy])} onChange={e=>setPolicy({...policy,[key]:e.target.checked})}/>{label}</label>)}</div><button className="btn-primary mt-4" disabled={busy} onClick={()=>void savePolicy()}><Save className="h-4 w-4"/>Save Core Policy</button>
 <div className="mt-6 grid gap-5 xl:grid-cols-2"><div className="rounded-xl border p-3"><div className="flex items-center gap-2"><Building2 className="h-4 w-4"/><h3 className="font-semibold">Operating Locations</h3></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><select className="input" value={loc.business_unit_id} onChange={e=>setLoc({...loc,business_unit_id:e.target.value})}><option value="">Company-wide</option>{units.map(u=><option key={u.id} value={u.id}>{u.name} ({u.code})</option>)}</select><select className="input" value={loc.location_type} onChange={e=>setLoc({...loc,location_type:e.target.value})}>{["branch","plant","warehouse","store","station","office","site","custom"].map(x=><option key={x}>{x}</option>)}</select><input className="input" placeholder="Code" value={loc.code} onChange={e=>setLoc({...loc,code:e.target.value})}/><input className="input" placeholder="Location name" value={loc.name} onChange={e=>setLoc({...loc,name:e.target.value})}/></div><button className="btn-secondary mt-2" disabled={busy||!loc.code.trim()||!loc.name.trim()} onClick={()=>void addLocation()}><Plus className="h-4 w-4"/>Add Location</button><div className="mt-3 space-y-1">{locations.length===0&&<div className="text-xs text-slate-400">No locations configured yet.</div>}{locations.map(x=><div key={x.id} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-xs"><div><span className="font-bold">{x.code}</span> · {x.name} · {x.location_type}{x.business_unit_id?` · ${unitMap.get(x.business_unit_id)??"BU"}`:" · company-wide"}</div><button className="btn-secondary h-7 px-2" disabled={busy} onClick={()=>void toggle("operating_locations",x.id,x.is_active)}>{x.is_active?"Disable":"Enable"}</button></div>)}</div></div>
 <div className="rounded-xl border p-3"><div className="flex items-center gap-2"><Layers3 className="h-4 w-4"/><h3 className="font-semibold">Accounting Dimensions</h3></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><select className="input" value={dim.business_unit_id} onChange={e=>setDim({...dim,business_unit_id:e.target.value})}><option value="">Company-wide</option>{units.map(u=><option key={u.id} value={u.id}>{u.name} ({u.code})</option>)}</select><select className="input" value={dim.dimension_type} onChange={e=>setDim({...dim,dimension_type:e.target.value})}>{["cost_center","profit_center","department","project","route","vehicle","machine","counter","tank","custom"].map(x=><option key={x}>{x}</option>)}</select><input className="input" placeholder="Code" value={dim.code} onChange={e=>setDim({...dim,code:e.target.value})}/><input className="input" placeholder="Dimension name" value={dim.name} onChange={e=>setDim({...dim,name:e.target.value})}/></div><button className="btn-secondary mt-2" disabled={busy||!dim.code.trim()||!dim.name.trim()} onClick={()=>void addDimension()}><Plus className="h-4 w-4"/>Add Dimension</button><div className="mt-3 space-y-1">{dimensions.length===0&&<div className="text-xs text-slate-400">No dimensions configured yet.</div>}{dimensions.map(x=><div key={x.id} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-xs"><div><span className="font-bold">{x.code}</span> · {x.name} · {x.dimension_type}{x.business_unit_id?` · ${unitMap.get(x.business_unit_id)??"BU"}`:" · company-wide"}</div><button className="btn-secondary h-7 px-2" disabled={busy} onClick={()=>void toggle("accounting_dimensions",x.id,x.is_active)}>{x.is_active?"Disable":"Enable"}</button></div>)}</div></div></div>
 <div className="mt-4 rounded-lg bg-blue-50 px-3 py-2 text-xs text-blue-800"><Calculator className="mr-1 inline h-3.5 w-3.5"/>Central rules now support balanced posting, period lock, posted-entry immutability, multi-currency foundation, cost/profit dimensions, document sequences, approvals, inter-unit mapping, attachments and accounting exception tracking.</div></section>;
}
