import { useCallback, useEffect, useMemo, useState } from "react";
import { Navigate } from "react-router-dom";
import { Download, Loader2, Plus, ShieldCheck, Users } from "lucide-react";
import { useAuth } from "@/auth/AuthContext";
import { supabase } from "@/lib/supabase";
import { PageHeader, ErrorBanner } from "@/components/ui";
import SubscriptionControl from "./SubscriptionControl";
import TransactionResetControl from "./TransactionResetControl";
import BusinessUnitControl from "./BusinessUnitControl";
import CompanyDeleteControl from "./CompanyDeleteControl";
import CoreAccountingControl from "./CoreAccountingControl";

type Company={id:string;name:string;code:string;status:string;subscription_expires_at:string|null;max_users:number;contact_email:string|null;contact_phone:string|null;address:string|null;notes:string|null};
type Membership={id:string;company_id:string;user_id:string;role:string;is_active:boolean};
type Profile={id:string;email:string|null;full_name:string|null};
const roles=["company_owner","admin","accounts","sales","purchase","store","production","viewer"];
const invoke=async(action:string,payload:Record<string,unknown>)=>{const{data,error}=await supabase.functions.invoke("platform-admin",{body:{action,...payload}});if(error)throw error;if(data?.error)throw new Error(data.error);return data};
export default function OwnerPanel(){
 const{isPlatformOwner,refreshAccess}=useAuth();
 const[companies,setCompanies]=useState<Company[]>([]),[memberships,setMemberships]=useState<Membership[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[selectedCompanyId,setSelectedCompanyId]=useState("");
 const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const[company,setCompany]=useState({name:"",code:"",contact_email:"",contact_phone:"",address:"",notes:"",subscription_expires_at:"",max_users:"10"});
 const[user,setUser]=useState({full_name:"",email:"",password:"",role:"viewer"});
 const[openingDate,setOpeningDate]=useState(()=>new Date().toISOString().slice(0,10)),[openingFile,setOpeningFile]=useState<File|null>(null),[openingResult,setOpeningResult]=useState("");
 const load=useCallback(async()=>{if(!isPlatformOwner){setLoading(false);return}setLoading(true);const[c,m,p]=await Promise.all([supabase.from("companies").select("*").order("created_at",{ascending:false}),supabase.from("company_memberships").select("*").order("created_at",{ascending:false}),supabase.from("user_profiles").select("id,email,full_name").order("email")]);const e=c.error||m.error||p.error;setError(e?.message||"");const cs=(c.data??[]) as Company[];setCompanies(cs);setMemberships((m.data??[]) as Membership[]);setProfiles((p.data??[]) as Profile[]);setSelectedCompanyId(x=>cs.some(v=>v.id===x)?x:(cs[0]?.id||""));setLoading(false)},[isPlatformOwner]);
 useEffect(()=>{void load()},[load]);
 const selected=companies.find(c=>c.id===selectedCompanyId);const pmap=useMemo(()=>new Map(profiles.map(p=>[p.id,p])),[profiles]);
 if(!isPlatformOwner)return <Navigate to="/" replace/>;
 const createCompany=async()=>{if(!company.name.trim()||!company.code.trim()){setError("Company name and code are required.");return}setSaving(true);setError("");try{await invoke("create_company",{...company,name:company.name.trim(),code:company.code.trim().toUpperCase(),max_users:Math.max(1,Number(company.max_users)||10),subscription_expires_at:company.subscription_expires_at?new Date(company.subscription_expires_at).toISOString():null});setCompany({name:"",code:"",contact_email:"",contact_phone:"",address:"",notes:"",subscription_expires_at:"",max_users:"10"});await load();await refreshAccess()}catch(e){setError(e instanceof Error?e.message:"Could not create company.")}finally{setSaving(false)}};
 const patch=async(c:Company,status:string)=>{setSaving(true);try{await invoke("set_company_status",{company_id:c.id,status});await load();await refreshAccess()}catch(e){setError(e instanceof Error?e.message:"Update failed.")}finally{setSaving(false)}};
 const createUser=async()=>{if(!selectedCompanyId||!user.email.trim()||user.password.length<8){setError("Select company, enter email and minimum 8 character password.");return}setSaving(true);try{await invoke("create_user",{company_id:selectedCompanyId,...user});setUser({full_name:"",email:"",password:"",role:"viewer"});await load()}catch(e){setError(e instanceof Error?e.message:"Could not create user.")}finally{setSaving(false)}};
 const updateMember=async(m:Membership,x:Record<string,unknown>)=>{setSaving(true);try{await invoke("update_membership",{membership_id:m.id,...x});await load()}catch(e){setError(e instanceof Error?e.message:"Access update failed.")}finally{setSaving(false)}};
 const downloadTemplate=async()=>{const XLSX=await import("xlsx");const ws=XLSX.utils.aoa_to_sheet([["Party Type","Party Name","Amount","Side","Opening Date"],["customer","Example Customer",1000,"debit",openingDate],["supplier","Example Supplier",500,"credit",openingDate]]);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Opening Balances");XLSX.writeFile(wb,"MetalForge-Opening-Balances.xlsx")};
 const importOpening=async()=>{if(!openingFile||!selectedCompanyId)return;setSaving(true);setOpeningResult("");try{const XLSX=await import("xlsx");const wb=XLSX.read(await openingFile.arrayBuffer(),{type:"array"});const rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(wb.Sheets[wb.SheetNames[0]],{defval:""}).map(r=>({party_type:String(r["Party Type"]||r.party_type||"").toLowerCase(),party_name:String(r["Party Name"]||r.party_name||""),amount:Number(r.Amount||r.amount||0),side:String(r.Side||r.side||"").toLowerCase(),opening_date:String(r["Opening Date"]||r.opening_date||openingDate)}));const out=await invoke("import_opening_balances",{company_id:selectedCompanyId,opening_date:openingDate,rows});setOpeningResult(`Imported ${out?.imported??rows.length} opening balances.`);setOpeningFile(null)}catch(e){setError(e instanceof Error?e.message:"Opening import failed.")}finally{setSaving(false)}};
 if(loading)return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="mr-2 h-5 w-5 animate-spin"/>Loading owner controls...</div>;
 return <div className="space-y-6"><PageHeader title="Owner Control Center" subtitle="Full platform control: companies, services, subscriptions, users, opening data and lifecycle"/>{error&&<ErrorBanner message={error}/>}<section className="rounded-xl border bg-white p-4 shadow-sm"><div className="mb-4 flex items-center gap-2"><ShieldCheck className="h-5 w-5"/><h2 className="font-semibold">Create company</h2></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input className="input" placeholder="Company name" value={company.name} onChange={e=>setCompany({...company,name:e.target.value})}/><input className="input" placeholder="Company code" value={company.code} onChange={e=>setCompany({...company,code:e.target.value})}/><input className="input" type="date" value={company.subscription_expires_at} onChange={e=>setCompany({...company,subscription_expires_at:e.target.value})}/><input className="input" type="number" min="1" value={company.max_users} onChange={e=>setCompany({...company,max_users:e.target.value})}/><input className="input" placeholder="Email" value={company.contact_email} onChange={e=>setCompany({...company,contact_email:e.target.value})}/><input className="input" placeholder="Phone" value={company.contact_phone} onChange={e=>setCompany({...company,contact_phone:e.target.value})}/><input className="input sm:col-span-2" placeholder="Address" value={company.address} onChange={e=>setCompany({...company,address:e.target.value})}/></div><textarea className="input mt-3 min-h-20 w-full" placeholder="Notes" value={company.notes} onChange={e=>setCompany({...company,notes:e.target.value})}/><button className="btn-primary mt-3" disabled={saving} onClick={()=>void createCompany()}><Plus className="h-4 w-4"/>Create Company</button></section>
 <section className="rounded-xl border bg-white p-4 shadow-sm"><div className="mb-4 flex items-center gap-2"><Users className="h-5 w-5"/><h2 className="font-semibold">Companies & access</h2></div><div className="grid gap-4 lg:grid-cols-2">{companies.map(c=>{const ms=memberships.filter(m=>m.company_id===c.id);return <div key={c.id} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-3"><div><div className="font-semibold">{c.name} <span className="text-xs text-slate-400">({c.code})</span></div><div className="text-xs text-slate-500">{c.status} · max {c.max_users} users</div></div><div className="flex flex-wrap gap-2"><button className="btn-secondary" disabled={saving} onClick={()=>void patch(c,c.status==="suspended"?"active":"suspended")}>{c.status==="suspended"?"Activate":"Suspend"}</button><CompanyDeleteControl companyId={c.id} companyName={c.name} companyCode={c.code} onDeleted={async()=>{await load();await refreshAccess()}}/></div></div><div className="mt-4 space-y-2">{ms.map(m=>{const p=pmap.get(m.user_id);return <div key={m.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-slate-50 p-2"><div className="text-sm">{p?.full_name||p?.email||m.user_id}</div><div className="flex gap-2"><select className="input h-8 py-1 text-xs" value={m.role} onChange={e=>void updateMember(m,{role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select><button className="btn-secondary h-8" onClick={()=>void updateMember(m,{is_active:!m.is_active})}>{m.is_active?"Disable":"Enable"}</button></div></div>})}</div></div>})}</div></section>
 <section className="rounded-xl border bg-white p-4 shadow-sm"><h2 className="font-semibold">Selected company controls</h2><select className="input mt-3 w-full sm:w-96" value={selectedCompanyId} onChange={e=>setSelectedCompanyId(e.target.value)}>{companies.map(c=><option key={c.id} value={c.id}>{c.name} ({c.code})</option>)}</select></section>
 {selectedCompanyId&&<BusinessUnitControl companyId={selectedCompanyId} onSaved={refreshAccess}/>} {selectedCompanyId&&<CoreAccountingControl companyId={selectedCompanyId}/>} {selectedCompanyId&&<SubscriptionControl companyId={selectedCompanyId} onSaved={async()=>{await load();await refreshAccess()}}/>}
 <section className="rounded-xl border bg-white p-4 shadow-sm"><h2 className="font-semibold">Create login ID</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input className="input" placeholder="Full name" value={user.full_name} onChange={e=>setUser({...user,full_name:e.target.value})}/><input className="input" type="email" placeholder="Email / login ID" value={user.email} onChange={e=>setUser({...user,email:e.target.value})}/><input className="input" type="password" placeholder="Temporary password" value={user.password} onChange={e=>setUser({...user,password:e.target.value})}/><select className="input" value={user.role} onChange={e=>setUser({...user,role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select></div><button className="btn-primary mt-3" disabled={saving||!selectedCompanyId} onClick={()=>void createUser()}>Create User</button></section>
 <section className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">Import opening balances</h2><p className="text-xs text-slate-500">Customer/supplier opening balances from Excel/CSV.</p></div><button className="btn-secondary" onClick={()=>void downloadTemplate()}><Download className="h-4 w-4"/>Download Excel Template</button></div><div className="mt-3 grid gap-3 sm:grid-cols-3"><input className="input" type="date" value={openingDate} onChange={e=>setOpeningDate(e.target.value)}/><input className="input sm:col-span-2" type="file" accept=".xlsx,.xls,.csv" onChange={e=>setOpeningFile(e.target.files?.[0]??null)}/></div><button className="btn-primary mt-3" disabled={saving||!openingFile||!selectedCompanyId} onClick={()=>void importOpening()}>Import Opening Balances</button>{openingResult&&<div className="mt-2 text-sm text-emerald-700">{openingResult}</div>}</section>
 {selected&&<TransactionResetControl companyId={selected.id} companyName={selected.name} companyCode={selected.code}/>}</div>;
}
