import { useCallback, useEffect, useMemo, useState } from "react";
import { Navigate } from "react-router-dom";
import { Download, Loader2, Plus, ShieldCheck, Users } from "lucide-react";
import { useAuth } from "@/auth/AuthContext";
import { supabase } from "@/lib/supabase";
import { PageHeader, ErrorBanner } from "@/components/ui";
import SubscriptionControl from "./SubscriptionControl";
import TransactionResetControl from "./TransactionResetControl";
import BusinessUnitControl from "./BusinessUnitControl";

type Company={id:string;name:string;code:string;status:string;subscription_expires_at:string|null;max_users:number;contact_email:string|null;contact_phone:string|null;address:string|null;notes:string|null};
type Membership={id:string;company_id:string;user_id:string;role:string;is_active:boolean;permissions:Record<string,unknown>;created_at:string};
type Profile={id:string;email:string|null;full_name:string|null;platform_role:string;is_active:boolean;last_company_id:string|null};
type CompanyForm={name:string;code:string;contact_email:string;contact_phone:string;address:string;notes:string;subscription_expires_at:string;max_users:string};
type UserForm={email:string;password:string;full_name:string;role:string};
const emptyCompany:CompanyForm={name:"",code:"",contact_email:"",contact_phone:"",address:"",notes:"",subscription_expires_at:"",max_users:"10"};
const emptyUser:UserForm={email:"",password:"",full_name:"",role:"viewer"};
const roles=["company_owner","admin","accounts","sales","purchase","store","production","viewer"];
const invoke=async(action:string,payload:Record<string,unknown>)=>{const{data,error}=await supabase.functions.invoke("platform-admin",{body:{action,...payload}});if(error)throw error;if(data?.error)throw new Error(data.error);return data};
export default function OwnerPanel(){
 const{isPlatformOwner,refreshAccess}=useAuth();const[companies,setCompanies]=useState<Company[]>([]),[memberships,setMemberships]=useState<Membership[]>([]),[profiles,setProfiles]=useState<Profile[]>([]);const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");const[companyForm,setCompanyForm]=useState<CompanyForm>(emptyCompany),[userForm,setUserForm]=useState<UserForm>(emptyUser),[selectedCompanyId,setSelectedCompanyId]=useState("");const[openingDate,setOpeningDate]=useState(()=>new Date().toISOString().slice(0,10)),[openingFile,setOpeningFile]=useState<File|null>(null),[openingResult,setOpeningResult]=useState("");
 const load=useCallback(async()=>{if(!isPlatformOwner){setLoading(false);return}setLoading(true);setError("");const[c,m,p]=await Promise.all([supabase.from("companies").select("*").order("created_at",{ascending:false}),supabase.from("company_memberships").select("*").order("created_at",{ascending:false}),supabase.from("user_profiles").select("id,email,full_name,platform_role,is_active,last_company_id").order("email")]);const first=c.error||m.error||p.error;if(first)setError(first.message);setCompanies((c.data??[]) as Company[]);setMemberships((m.data??[]) as Membership[]);setProfiles((p.data??[]) as Profile[]);setSelectedCompanyId(x=>x||c.data?.[0]?.id||"");setLoading(false)},[isPlatformOwner]);useEffect(()=>{void load()},[load]);
 const membersByCompany=useMemo(()=>{const map=new Map<string,Membership[]>();memberships.forEach(m=>map.set(m.company_id,[...(map.get(m.company_id)??[]),m]));return map},[memberships]);const profileById=useMemo(()=>new Map(profiles.map(p=>[p.id,p])),[profiles]);const selectedCompany=companies.find(c=>c.id===selectedCompanyId);if(!isPlatformOwner)return <Navigate to="/" replace/>;
 const createCompany=async()=>{if(!companyForm.name.trim()||!companyForm.code.trim()){setError("Company name and code are required.");return}setSaving(true);setError("");try{const{error:e}=await supabase.from("companies").insert({name:companyForm.name.trim(),code:companyForm.code.trim().toUpperCase(),contact_email:companyForm.contact_email||null,contact_phone:companyForm.contact_phone||null,address:companyForm.address||null,notes:companyForm.notes||null,subscription_expires_at:companyForm.subscription_expires_at?new Date(companyForm.subscription_expires_at).toISOString():null,max_users:Math.max(1,Number(companyForm.max_users)||10)});if(e)throw e;setCompanyForm(emptyCompany);await load();await refreshAccess()}catch(e){setError(e instanceof Error?e.message:"Could not create company.")}finally{setSaving(false)}};
 const patchCompany=async(id:string,patch:Partial<Company>)=>{setSaving(true);setError("");try{const{error:e}=await supabase.from("companies").update(patch).eq("id",id);if(e)throw e;await load();await refreshAccess()}catch(e){setError(e instanceof Error?e.message:"Could not update company.")}finally{setSaving(false)}};
 const createUser=async()=>{if(!selectedCompanyId||!userForm.email.trim()||userForm.password.length<8){setError("Select company, enter email, and use a password of at least 8 characters.");return}setSaving(true);setError("");try{await invoke("create_user",{company_id:selectedCompanyId,email:userForm.email.trim(),password:userForm.password,full_name:userForm.full_name.trim()||null,role:userForm.role});setUserForm(emptyUser);await load()}catch(e){setError(e instanceof Error?e.message:"Could not create user.")}finally{setSaving(false)}};
 const updateMember=async(m:Membership,patch:{role?:string;is_active?:boolean})=>{setSaving(true);setError("");try{await invoke("update_membership",{membership_id:m.id,...patch});await load()}catch(e){setError(e instanceof Error?e.message:"Could not update membership.")}finally{setSaving(false)}};
 const readRows=async(file:File)=>{const XLSX=await import("xlsx");const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:"array"});const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(ws,{defval:""});return rows.map(r=>({party_type:String(r.party_type||r["Party Type"]||"").trim().toLowerCase(),party_name:String(r.party_name||r["Party Name"]||"").trim(),amount:Number(r.amount||r.Amount||0),side:String(r.side||r.Side||"").trim().toLowerCase(),opening_date:String(r.opening_date||r["Opening Date"]||openingDate).trim()||openingDate}))};
 const downloadOpeningTemplate=async()=>{const XLSX=await import("xlsx");const ws=XLSX.utils.aoa_to_sheet([["Party Type","Party Name","Amount","Side","Opening Date"],["customer","Example Customer",1000,"debit",openingDate],["supplier","Example Supplier",500,"credit",openingDate]]);ws["!cols"]=[{wch:16},{wch:32},{wch:16},{wch:14},{wch:16}];const info=XLSX.utils.aoa_to_sheet([["Opening Balance Import Template"],["Party Type","customer or supplier"],["Party Name","Required"],["Amount","Positive number"],["Side","debit or credit"],["Opening Date","YYYY-MM-DD; can be left blank to use the screen date"]]);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Opening Balances");XLSX.utils.book_append_sheet(wb,info,"Instructions");XLSX.writeFile(wb,"MetalForge-Opening-Balances.xlsx")};
 const importOpening=async()=>{if(!selectedCompanyId||!openingFile){setError("Select a company and opening-balance file.");return}setSaving(true);setError("");setOpeningResult("");try{const rows=await readRows(openingFile);if(!rows.length)throw new Error("The file has no data rows.");const result=await invoke("import_opening_balances",{company_id:selectedCompanyId,opening_date:openingDate,rows});setOpeningResult(`Imported ${result?.imported??rows.length} opening balances.`);setOpeningFile(null)}catch(e){setError(e instanceof Error?e.message:"Opening balance import failed.")}finally{setSaving(false)}};
 if(loading)return <div className="flex min-h-[50vh] items-center justify-center text-slate-500"><Loader2 className="mr-2 h-5 w-5 animate-spin"/>Loading owner controls...</div>;
 return <div className="space-y-6"><PageHeader title="Owner Control Center" subtitle="Companies, business units, subscriptions, module access, users, expiry and opening data"/>{error&&<ErrorBanner message={error}/>}<section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-4 flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-slate-700"/><h2 className="font-semibold text-slate-900">Create company</h2></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input className="input" placeholder="Company name" value={companyForm.name} onChange={e=>setCompanyForm({...companyForm,name:e.target.value})}/><input className="input" placeholder="Code" value={companyForm.code} onChange={e=>setCompanyForm({...companyForm,code:e.target.value})}/><input className="input" type="date" value={companyForm.subscription_expires_at} onChange={e=>setCompanyForm({...companyForm,subscription_expires_at:e.target.value})}/><input className="input" type="number" min="1" placeholder="Max users" value={companyForm.max_users} onChange={e=>setCompanyForm({...companyForm,max_users:e.target.value})}/><input className="input" placeholder="Contact email" value={companyForm.contact_email} onChange={e=>setCompanyForm({...companyForm,contact_email:e.target.value})}/><input className="input" placeholder="Contact phone" value={companyForm.contact_phone} onChange={e=>setCompanyForm({...companyForm,contact_phone:e.target.value})}/><input className="input sm:col-span-2" placeholder="Address" value={companyForm.address} onChange={e=>setCompanyForm({...companyForm,address:e.target.value})}/></div><textarea className="input mt-3 min-h-20 w-full" placeholder="Notes" value={companyForm.notes} onChange={e=>setCompanyForm({...companyForm,notes:e.target.value})}/><button className="btn-primary mt-3" disabled={saving} onClick={()=>void createCompany()}><Plus className="h-4 w-4"/>Create Company</button></section>
 <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-4 flex items-center gap-2"><Users className="h-5 w-5 text-slate-700"/><h2 className="font-semibold text-slate-900">Companies & access</h2></div><div className="grid gap-4 lg:grid-cols-2">{companies.map(c=>{const ms=membersByCompany.get(c.id)??[];return <div key={c.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="font-semibold text-slate-900">{c.name} <span className="text-xs text-slate-400">({c.code})</span></div><div className="mt-1 text-xs text-slate-500">{c.status} · {c.subscription_expires_at?`expires ${new Date(c.subscription_expires_at).toLocaleDateString()}`:"no expiry"} · max {c.max_users} users</div></div><div className="flex gap-2"><button className="btn-secondary" disabled={saving} onClick={()=>void patchCompany(c.id,{status:c.status==="suspended"?"active":"suspended"})}>{c.status==="suspended"?"Activate":"Suspend"}</button><button className="btn-secondary" disabled={saving} onClick={()=>{const days=Number(window.prompt("Extend subscription by how many days?","30")||0);if(days>0){const base=c.subscription_expires_at?new Date(c.subscription_expires_at):new Date();base.setDate(base.getDate()+days);void patchCompany(c.id,{subscription_expires_at:base.toISOString(),status:"active"})}}}>Extend</button></div></div><div className="mt-4 space-y-2">{ms.length===0&&<div className="text-xs text-slate-400">No users assigned yet.</div>}{ms.map(m=>{const p=profileById.get(m.user_id);return <div key={m.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-slate-50 px-3 py-2"><div><div className="text-sm font-medium text-slate-800">{p?.full_name||p?.email||m.user_id}</div><div className="text-xs text-slate-500">{p?.email||m.user_id}</div></div><div className="flex items-center gap-2"><select className="input h-8 py-1 text-xs" value={m.role} disabled={saving} onChange={e=>void updateMember(m,{role:e.target.value})}>{roles.map(r=><option key={r} value={r}>{r}</option>)}</select><button className="btn-secondary h-8" disabled={saving} onClick={()=>void updateMember(m,{is_active:!m.is_active})}>{m.is_active?"Disable":"Enable"}</button></div></div>})}</div></div>})}</div></section>
 <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="font-semibold text-slate-900">Selected company controls</h2><select className="input mt-3 w-full sm:w-96" value={selectedCompanyId} onChange={e=>setSelectedCompanyId(e.target.value)}>{companies.map(c=><option key={c.id} value={c.id}>{c.name} ({c.code})</option>)}</select></section>
 {selectedCompanyId&&<BusinessUnitControl companyId={selectedCompanyId} onSaved={refreshAccess}/>} {selectedCompanyId&&<SubscriptionControl companyId={selectedCompanyId} onSaved={async()=>{await load();await refreshAccess()}}/>}
 <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="font-semibold text-slate-900">Create login ID</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input className="input" placeholder="Full name" value={userForm.full_name} onChange={e=>setUserForm({...userForm,full_name:e.target.value})}/><input className="input" type="email" placeholder="Email / login ID" value={userForm.email} onChange={e=>setUserForm({...userForm,email:e.target.value})}/><input className="input" type="password" placeholder="Temporary password" value={userForm.password} onChange={e=>setUserForm({...userForm,password:e.target.value})}/><select className="input" value={userForm.role} onChange={e=>setUserForm({...userForm,role:e.target.value})}>{roles.map(r=><option key={r} value={r}>{r}</option>)}</select></div><button className="btn-primary mt-3" disabled={saving||!selectedCompanyId} onClick={()=>void createUser()}>Create User</button></section>
 <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-slate-900">Import opening balances</h2><p className="mt-1 text-xs text-slate-500">Excel/CSV columns: Party Type, Party Name, Amount, Side, Opening Date. Side: debit or credit.</p></div><button type="button" className="btn-secondary" onClick={()=>void downloadOpeningTemplate()}><Download className="h-4 w-4"/>Download Excel Template</button></div><div className="mt-3 grid gap-3 sm:grid-cols-3"><input className="input" type="date" value={openingDate} onChange={e=>setOpeningDate(e.target.value)}/><input className="input sm:col-span-2" type="file" accept=".xlsx,.xls,.csv" onChange={e=>setOpeningFile(e.target.files?.[0]??null)}/></div><button className="btn-primary mt-3" disabled={saving||!selectedCompanyId||!openingFile} onClick={()=>void importOpening()}>Import Opening Balances</button>{openingResult&&<div className="mt-3 rounded-lg bg-emerald-50 px-3 py-2 text-sm text-emerald-700">{openingResult}</div>}</section>
 {selectedCompany&&<TransactionResetControl companyId={selectedCompany.id} companyName={selectedCompany.name} companyCode={selectedCompany.code}/>}</div>
}
