import SearchableSelect from "@/components/SearchableSelect";
import { useEffect,useMemo,useState } from "react";
import { supabase } from "@/lib/supabase";

type Plan={id:string;name:string;billing_cycle:"monthly"|"yearly"|"custom";price:number;max_users:number;max_business_units:number|null;max_branches:number|null;max_godowns:number|null};
type Sub={id:string;plan_id:string|null;billing_cycle:string;status:string;starts_at:string;expires_at:string|null;amount:number;notes:string|null};
type Mod={module_key:string;enabled:boolean};
type CompanyLimits={max_users:number|null;max_business_units:number|null;max_branches:number|null;max_godowns:number|null};
const MODULES=[["master","Master Data"],["sales","Sales"],["purchase","Purchase"],["inventory","Inventory / Stock"],["production","Production / Cutting"],["transport","Transport"],["accounting","Accounting"],["reports","Reports"],["settings","Settings"]] as const;
const statusLabel=(value:string)=>value.replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
const positive=(value:string,fallback:number|null)=>{const n=Number(value);return Number.isFinite(n)&&n>=1?Math.floor(n):fallback};

export default function SubscriptionControl({companyId,onSaved}:{companyId:string;onSaved?:()=>Promise<void>|void}){
 const[plans,setPlans]=useState<Plan[]>([]),[sub,setSub]=useState<Sub|null>(null),[mods,setMods]=useState<Mod[]>([]),[companyLimits,setCompanyLimits]=useState<CompanyLimits|null>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 const[planId,setPlanId]=useState(""),[billing,setBilling]=useState<"monthly"|"yearly"|"custom">("monthly"),[status,setStatus]=useState("active"),[expiry,setExpiry]=useState(""),[amount,setAmount]=useState("0"),[notes,setNotes]=useState("");
 const[maxUsers,setMaxUsers]=useState("10"),[maxUnits,setMaxUnits]=useState("1"),[maxBranches,setMaxBranches]=useState("1"),[maxGodowns,setMaxGodowns]=useState("1");

 const load=async()=>{const[p,s,m,c]=await Promise.all([
   supabase.from("subscription_plans").select("id,name,billing_cycle,price,max_users,max_business_units,max_branches,max_godowns").eq("is_active",true).order("name"),
   supabase.from("company_subscriptions").select("id,plan_id,billing_cycle,status,starts_at,expires_at,amount,notes").eq("company_id",companyId).in("status",["trial","active","past_due","suspended"]).order("created_at",{ascending:false}).limit(1),
   supabase.from("company_modules").select("module_key,enabled").eq("company_id",companyId),
   supabase.from("companies").select("max_users,max_business_units,max_branches,max_godowns").eq("id",companyId).single(),
 ]);const e=p.error||s.error||m.error||c.error;if(e)throw e;setPlans((p.data??[]) as Plan[]);setSub((s.data?.[0]??null) as Sub|null);setMods((m.data??[]) as Mod[]);setCompanyLimits(c.data as CompanyLimits)};
 useEffect(()=>{void load().catch(e=>setMsg(e.message))},[companyId]);
 const enabled=useMemo(()=>new Set(mods.filter(x=>x.enabled).map(x=>x.module_key)),[mods]);
 useEffect(()=>{const p=plans.find(x=>x.id===sub?.plan_id);setPlanId(sub?.plan_id??plans[0]?.id??"");setBilling((sub?.billing_cycle as any)??p?.billing_cycle??"monthly");setStatus(sub?.status??"active");setAmount(String(sub?.amount??p?.price??0));setExpiry(sub?.expires_at?new Date(sub.expires_at).toISOString().slice(0,10):"");setNotes(sub?.notes??"");if(companyLimits){setMaxUsers(String(companyLimits.max_users??p?.max_users??10));setMaxUnits(String(companyLimits.max_business_units??p?.max_business_units??1));setMaxBranches(String(companyLimits.max_branches??p?.max_branches??1));setMaxGodowns(String(companyLimits.max_godowns??p?.max_godowns??1))}},[companyId,sub?.id,plans.length,companyLimits?.max_users,companyLimits?.max_business_units,companyLimits?.max_branches,companyLimits?.max_godowns]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setMsg("");try{await fn();await load();await onSaved?.();setMsg("Saved successfully.")}catch(e){setMsg(e instanceof Error?e.message:"Request failed")}finally{setBusy(false)}};
 const save=()=>run(async()=>{const plan=plans.find(x=>x.id===planId),expires=expiry?`${expiry}T23:59:59.999Z`:null,payload={company_id:companyId,plan_id:planId||null,billing_cycle:billing,status,starts_at:sub?.starts_at??new Date().toISOString(),expires_at:expires,amount:Number(amount)||0,notes:notes.trim()||null,updated_at:new Date().toISOString()};const q=sub?supabase.from("company_subscriptions").update(payload).eq("id",sub.id):supabase.from("company_subscriptions").insert(payload);const{error}=await q;if(error)throw error;const companyStatus=status==="suspended"?"suspended":"active";const{error:ce}=await supabase.from("companies").update({subscription_expires_at:expires,max_users:positive(maxUsers,plan?.max_users??10),max_business_units:positive(maxUnits,plan?.max_business_units??1),max_branches:positive(maxBranches,plan?.max_branches??1),max_godowns:positive(maxGodowns,plan?.max_godowns??1),status:companyStatus,updated_at:new Date().toISOString()}).eq("id",companyId);if(ce)throw ce});
 const toggle=(key:string,value:boolean)=>run(async()=>{const{error}=await supabase.from("company_modules").upsert({company_id:companyId,module_key:key,enabled:value,updated_at:new Date().toISOString()},{onConflict:"company_id,module_key"});if(error)throw error});
 const selectedPlan=plans.find(x=>x.id===planId);
 const applyPlanLimits=()=>{if(!selectedPlan)return;setMaxUsers(String(selectedPlan.max_users??10));setMaxUnits(String(selectedPlan.max_business_units??1));setMaxBranches(String(selectedPlan.max_branches??1));setMaxGodowns(String(selectedPlan.max_godowns??1));};
 return <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold text-slate-900">Subscription, Limits & Service Access</h2><p className="mt-1 text-xs text-slate-500">Owner controls the commercial plan, company limits and licensed NAVILO modules. Company admins can work only inside these limits.</p></div>{sub&&<span className="rounded-full border border-slate-200 bg-slate-50 px-3 py-1 text-xs font-semibold text-slate-700">Current status: {statusLabel(sub.status)}</span>}</div>{msg&&<div className="mt-3 rounded-lg bg-slate-50 px-3 py-2 text-xs">{msg}</div>}
 <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><label className="text-xs font-semibold text-slate-700">Plan<SearchableSelect className="input mt-1 w-full" value={planId} onChange={e=>{setPlanId(e.target.value);const p=plans.find(x=>x.id===e.target.value);if(p){setBilling(p.billing_cycle);setAmount(String(p.price))}}}>{plans.map(p=><option key={p.id} value={p.id}>{p.name} · {p.max_users} users</option>)}</SearchableSelect></label><label className="text-xs font-semibold text-slate-700">Billing Cycle<SearchableSelect className="input mt-1 w-full" value={billing} onChange={e=>setBilling(e.target.value as any)}><option value="monthly">Monthly</option><option value="yearly">Yearly</option><option value="custom">Custom</option></SearchableSelect></label><label className="text-xs font-semibold text-slate-700">Subscription Status<SearchableSelect className="input mt-1 w-full" value={status} onChange={e=>setStatus(e.target.value)}><option value="trial">Trial</option><option value="active">Active</option><option value="past_due">Past Due</option><option value="suspended">Suspended</option></SearchableSelect></label><label className="text-xs font-semibold text-slate-700">Expiry Date<input className="input mt-1 w-full" type="date" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label><label className="text-xs font-semibold text-slate-700">Amount<input className="input mt-1 w-full" type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label></div>
 <div className="mt-4 rounded-xl border border-blue-200 bg-blue-50/30 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="text-sm font-bold text-slate-900">Company Resource Limits</div><div className="text-xs text-slate-500">Hard limits are enforced by the database, not only by the screen.</div></div><button type="button" className="btn-secondary" disabled={!selectedPlan||busy} onClick={applyPlanLimits}>Use Plan Defaults</button></div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-semibold text-slate-700">Max Users<input className="input mt-1 w-full" type="number" min="1" value={maxUsers} onChange={e=>setMaxUsers(e.target.value)}/></label><label className="text-xs font-semibold text-slate-700">Max Business Units<input className="input mt-1 w-full" type="number" min="1" value={maxUnits} onChange={e=>setMaxUnits(e.target.value)}/></label><label className="text-xs font-semibold text-slate-700">Max Branches<input className="input mt-1 w-full" type="number" min="1" value={maxBranches} onChange={e=>setMaxBranches(e.target.value)}/></label><label className="text-xs font-semibold text-slate-700">Max Godowns<input className="input mt-1 w-full" type="number" min="1" value={maxGodowns} onChange={e=>setMaxGodowns(e.target.value)}/></label></div></div>
 <div className="mt-3 grid gap-3 lg:grid-cols-[1fr_300px]"><label className="text-xs font-semibold text-slate-700">Internal Subscription Note<textarea className="input mt-1 min-h-16 w-full" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Payment reference, renewal note or internal owner remark"/></label><div className="rounded-lg border border-slate-200 bg-slate-50 p-3 text-xs text-slate-600"><div className="font-semibold text-slate-800">Selected plan defaults</div><div className="mt-1">Users: <strong>{selectedPlan?.max_users??"—"}</strong></div><div>Business Units: <strong>{selectedPlan?.max_business_units??"Not set"}</strong></div><div>Branches: <strong>{selectedPlan?.max_branches??"Not set"}</strong></div><div>Godowns: <strong>{selectedPlan?.max_godowns??"Not set"}</strong></div><div>Default price: <strong>{selectedPlan?.price??"—"}</strong></div></div></div>
 <button className="btn-primary mt-3" disabled={busy||!planId} onClick={()=>void save()}>Save Subscription & Limits</button>
 <div className="mt-5"><div className="mb-2 text-xs font-bold uppercase tracking-wider text-slate-500">Licensed Modules</div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{MODULES.map(([key,label])=><label key={key} className="flex items-center justify-between rounded-lg border border-slate-200 px-3 py-2 text-sm"><span>{label}</span><input type="checkbox" checked={enabled.has(key)} disabled={busy} onChange={e=>void toggle(key,e.target.checked)}/></label>)}</div></div>
 </section>;
}
