import { useCallback,useEffect,useMemo,useState } from "react";
import { Printer } from "lucide-react";import { supabase } from "@/lib/supabase";import { ErrorBanner,LoadingState,PageHeader } from "@/components/ui";
interface Account{id:string;code:string;name:string;type:string;detail_type:string|null;}interface L{account_id:string;entry_date:string;debit:number;credit:number;journal?:{trans_type:string|null}|null;}
const money=(n:number)=>new Intl.NumberFormat("en-PK",{minimumFractionDigits:2,maximumFractionDigits:2}).format(n||0);const norm=(s:string|null)=>String(s||"").toLowerCase().replace(/[^a-z]/g,"");
export default function CashFlowStatement(){const year=new Date().getFullYear();const[from,setFrom]=useState(`${year}-01-01`);const[to,setTo]=useState(new Date().toISOString().slice(0,10));const[accounts,setAccounts]=useState<Account[]>([]);const[lines,setLines]=useState<L[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");const[a,l]=await Promise.all([supabase.from("chart_of_accounts").select("id,code,name,type,detail_type").eq("is_group",false),supabase.from("ledgers").select("account_id,entry_date,debit,credit,journal:journal_entries!journal_entry_id(trans_type)").lte("entry_date",to)]);if(a.error||l.error)setError(a.error?.message||l.error?.message||"Unable to load cash flow.");setAccounts((a.data??[]) as Account[]);setLines((l.data??[]).map((row:any)=>({...row,journal:Array.isArray(row.journal)?row.journal[0]??null:row.journal})) as L[]);setLoading(false);},[to]);useEffect(()=>{void load()},[load]);
 const report=useMemo(()=>{const financialLines=lines.filter(x=>x.journal?.trans_type!=="Year End Closing");const before=(id:string)=>financialLines.filter(x=>x.account_id===id&&x.entry_date<from).reduce((s,x)=>s+Number(x.debit)-Number(x.credit),0);const end=(id:string)=>financialLines.filter(x=>x.account_id===id&&x.entry_date<=to).reduce((s,x)=>s+Number(x.debit)-Number(x.credit),0);const period=(id:string)=>end(id)-before(id);let income=0,depr=0,wc=0,invest=0,finance=0,cashOpen=0,cashEnd=0;const working:any[]=[],investRows:any[]=[],financeRows:any[]=[];
 accounts.forEach(a=>{const d=norm(`${a.detail_type} ${a.name}`),p=period(a.id),o=before(a.id),e=end(a.id);if(a.type==="revenue")income-=p;if(a.type==="expense")income-=p;if(a.type==="expense"&&d.includes("depreciation")){depr+=p;}const isCash=d.includes("cash")||d.includes("bank");if(a.type==="asset"&&isCash){cashOpen+=o;cashEnd+=e;}else if(a.type==="asset"&&(d.includes("receivable")||d.includes("inventory")||d.includes("currentasset"))){const v=o-e;wc+=v;if(Math.abs(v)>=.005)working.push({name:a.name,value:v});}else if(a.type==="liability"&&(d.includes("payable")||d.includes("currentliabil")||d.includes("vat"))){const v=o-e;wc+=v;if(Math.abs(v)>=.005)working.push({name:a.name,value:v});}if(a.type==="asset"&&(d.includes("fixedasset")||d.includes("noncurrentasset"))&&!d.includes("accumulated")){const v=-p;invest+=v;if(Math.abs(v)>=.005)investRows.push({name:a.name,value:v});}if(a.type==="equity"||d.includes("loan")){const v=-p;finance+=v;if(Math.abs(v)>=.005)financeRows.push({name:a.name,value:v});}});
 const operating=income+depr+wc,actual=cashEnd-cashOpen,unclassified=actual-operating-invest-finance;return{income,depr,working,investRows,financeRows,operating,invest,finance,unclassified,actual,cashOpen,cashEnd};},[accounts,lines,from,to]);
 if(loading)return <LoadingState/>;return <div className="print-report"><PageHeader title="Cash Flow Statement / کیش فلو" subtitle="Indirect-method statement with operating, investing and financing activities." action={<button className="btn btn-secondary no-print" onClick={()=>window.print()}><Printer size={15}/>Print</button>}/>{error&&<ErrorBanner message={error}/>}<div className="card mb-5 p-4 no-print"><div className="flex gap-3"><label className="text-sm">From<input className="input ml-2" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-sm">To<input className="input ml-2" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div></div><div className="card overflow-hidden"><Section title="Operating Activities" rows={[{name:"Net profit / (loss)",value:report.income},{name:"Depreciation add-back",value:report.depr},...report.working]} total={report.operating}/><Section title="Investing Activities" rows={report.investRows} total={report.invest}/><Section title="Financing Activities" rows={report.financeRows} total={report.finance}/>{Math.abs(report.unclassified)>=.005&&<Section title="Unclassified Cash Movement" rows={[{name:"Classification/reconciliation adjustment",value:report.unclassified}]} total={report.unclassified}/>}<div className="border-t-2 border-slate-700 bg-slate-50 p-5"><Row name="Net change in cash" value={report.actual} strong/><Row name="Opening cash & bank" value={report.cashOpen}/><Row name="Closing cash & bank" value={report.cashEnd} strong/></div></div></div>}
function Section({title,rows,total}:{title:string;rows:{name:string;value:number}[];total:number}){return <section className="border-b p-5"><h3 className="mb-3 font-semibold text-primary-700">{title}</h3>{rows.length?rows.map((r,i)=><Row key={`${r.name}-${i}`} {...r}/>):<div className="text-sm text-slate-400">No activity</div>}<div className="mt-2 border-t pt-2"><Row name={`Net cash from ${title.toLowerCase()}`} value={total} strong/></div></section>}
function Row({name,value,strong=false}:{name:string;value:number;strong?:boolean}){return <div className={`flex justify-between py-1 ${strong?"font-bold":"text-sm"}`}><span>{name}</span><span className={value<0?"text-red-600":""}>{money(value)}</span></div>}
