-- Canonical management reporting layer. Runtime migration applied to Supabase production.
-- Views are SECURITY INVOKER so underlying RLS remains authoritative.

create or replace view public.customer_profitability_report with (security_invoker=true) as
select user_id,company_id,business_unit_id,operating_location_id,customer_name,count(distinct sales_order_id)::int invoices,sum(net_sales_amount)::numeric net_sales,sum(cost_amount)::numeric actual_cogs,sum(gross_profit)::numeric gross_profit,case when sum(net_sales_amount)<>0 then round(sum(gross_profit)*100/sum(net_sales_amount),2) else 0 end::numeric margin_percent from public.sales_margin_report group by user_id,company_id,business_unit_id,operating_location_id,customer_name;

create or replace view public.item_profitability_report with (security_invoker=true) as
select user_id,company_id,business_unit_id,operating_location_id,item_id,item_name,sku,size,unit,sum(qty)::numeric qty_sold,sum(line_total)::numeric sales_value,sum(cost_total)::numeric actual_cost,(sum(line_total)-sum(cost_total))::numeric gross_profit,case when sum(line_total)<>0 then round((sum(line_total)-sum(cost_total))*100/sum(line_total),2) else 0 end::numeric margin_percent,case when sum(qty)<>0 then round(sum(line_total)/sum(qty),2) else 0 end::numeric avg_sale_rate from public.customer_item_history_report group by user_id,company_id,business_unit_id,operating_location_id,item_id,item_name,sku,size,unit;

create or replace view public.salesperson_profitability_report with (security_invoker=true) as
select user_id,company_id,business_unit_id,sales_person,count(distinct sales_order_id)::int invoices,sum(net_sales_amount)::numeric net_sales,sum(cost_amount)::numeric actual_cogs,sum(gross_profit)::numeric gross_profit,case when sum(net_sales_amount)<>0 then round(sum(gross_profit)*100/sum(net_sales_amount),2) else 0 end::numeric margin_percent from public.sales_margin_report group by user_id,company_id,business_unit_id,sales_person;

create or replace view public.purchase_price_variance_report with (security_invoker=true) as
select user_id,company_id,business_unit_id,operating_location_id,supplier_id,supplier_name,item_id,item_name,sku,size,unit,count(distinct purchase_order_id)::int purchases,sum(qty)::numeric qty_purchased,sum(line_total)::numeric purchase_value,case when sum(qty)<>0 then round(sum(line_total)/sum(qty),2) else 0 end::numeric avg_purchase_rate,min(rate)::numeric min_rate,max(rate)::numeric max_rate,(max(rate)-min(rate))::numeric rate_spread from public.supplier_item_history_report group by user_id,company_id,business_unit_id,operating_location_id,supplier_id,supplier_name,item_id,item_name,sku,size,unit;

create or replace view public.customer_collection_performance_report with (security_invoker=true) as
select user_id,company_id,business_unit_id,operating_location_id,customer_id,customer_name,count(*)::int invoices,sum(invoice_amount)::numeric invoiced,sum(paid_amount)::numeric received,sum(outstanding_amount)::numeric outstanding,sum(case when overdue_days>0 then outstanding_amount else 0 end)::numeric overdue_amount,round(avg(days_outstanding)::numeric,1) avg_days_outstanding,case when sum(outstanding_amount)<>0 then round(sum(case when overdue_days>0 then outstanding_amount else 0 end)*100/sum(outstanding_amount),2) else 0 end::numeric overdue_percent from public.customer_invoice_aging group by user_id,company_id,business_unit_id,operating_location_id,customer_id,customer_name;

create or replace view public.supplier_performance_report with (security_invoker=true) as
select h.user_id,h.company_id,h.business_unit_id,h.operating_location_id,h.supplier_id,h.supplier_name,count(distinct h.purchase_order_id)::int purchase_invoices,sum(h.qty)::numeric qty_purchased,sum(h.line_total)::numeric purchase_value,case when sum(h.qty)<>0 then round(sum(h.line_total)/sum(h.qty),2) else 0 end::numeric avg_rate,coalesce(max(a.outstanding),0)::numeric outstanding,coalesce(max(a.overdue),0)::numeric overdue from public.supplier_item_history_report h left join (select user_id,company_id,business_unit_id,supplier_id,sum(outstanding_amount) outstanding,sum(case when overdue_days>0 then outstanding_amount else 0 end) overdue from public.supplier_invoice_aging group by user_id,company_id,business_unit_id,supplier_id) a on a.user_id=h.user_id and a.company_id is not distinct from h.company_id and a.business_unit_id is not distinct from h.business_unit_id and a.supplier_id=h.supplier_id group by h.user_id,h.company_id,h.business_unit_id,h.operating_location_id,h.supplier_id,h.supplier_name;

create or replace view public.inventory_aging_report with (security_invoker=true) as
select s.*,lm.last_movement_date,case when lm.last_movement_date is null then null else (current_date-lm.last_movement_date)::int end days_since_movement,case when lm.last_movement_date is null then 'No Movement' when current_date-lm.last_movement_date<=30 then '0-30' when current_date-lm.last_movement_date<=60 then '31-60' when current_date-lm.last_movement_date<=90 then '61-90' when current_date-lm.last_movement_date<=180 then '91-180' else '180+' end::text aging_bucket from public.stock_godown_report s left join (select company_id,business_unit_id,operating_location_id,item_id,godown_id,max(created_at::date) last_movement_date from public.stock_movements group by company_id,business_unit_id,operating_location_id,item_id,godown_id) lm on lm.company_id is not distinct from s.company_id and lm.business_unit_id is not distinct from s.business_unit_id and lm.operating_location_id is not distinct from s.operating_location_id and lm.item_id=s.item_id and lm.godown_id is not distinct from s.godown_id;

create or replace view public.inventory_turnover_report with (security_invoker=true) as
select s.user_id,s.company_id,s.business_unit_id,s.operating_location_id,s.item_id,s.item_name,s.size,s.unit,sum(s.quantity)::numeric current_qty,sum(s.stock_value)::numeric current_stock_value,coalesce(x.qty_sold,0)::numeric qty_sold,coalesce(x.cogs,0)::numeric cogs,case when sum(s.stock_value)<>0 then round(coalesce(x.cogs,0)/sum(s.stock_value),2) else 0 end::numeric turnover_ratio from public.stock_godown_report s left join (select user_id,company_id,business_unit_id,operating_location_id,item_id,sum(qty) qty_sold,sum(cost_total) cogs from public.customer_item_history_report group by user_id,company_id,business_unit_id,operating_location_id,item_id) x on x.user_id=s.user_id and x.company_id is not distinct from s.company_id and x.business_unit_id is not distinct from s.business_unit_id and x.operating_location_id is not distinct from s.operating_location_id and x.item_id=s.item_id group by s.user_id,s.company_id,s.business_unit_id,s.operating_location_id,s.item_id,s.item_name,s.size,s.unit,x.qty_sold,x.cogs;

create or replace view public.stock_exception_report with (security_invoker=true) as select user_id,company_id,business_unit_id,operating_location_id,item_id,item_name,grade,size,unit,godown,quantity,avg_cost,stock_value,case when quantity<0 then 'Negative Stock' when quantity=0 then 'Zero Stock' else 'Review' end::text exception_type from public.stock_godown_report where quantity<=0;

create or replace view public.business_unit_performance_report with (security_invoker=true) as
select coalesce(s.user_id,p.user_id) user_id,coalesce(s.company_id,p.company_id) company_id,coalesce(s.business_unit_id,p.business_unit_id) business_unit_id,coalesce(s.net_sales,0)::numeric net_sales,coalesce(s.gross_profit,0)::numeric gross_profit,coalesce(p.purchases,0)::numeric purchases,coalesce(ar.receivables,0)::numeric receivables,coalesce(ap.payables,0)::numeric payables,coalesce(st.inventory_value,0)::numeric inventory_value from (select user_id,company_id,business_unit_id,sum(net_sales_amount) net_sales,sum(gross_profit) gross_profit from public.sales_margin_report group by user_id,company_id,business_unit_id) s full join (select user_id,company_id,business_unit_id,sum(total) purchases from public.purchase_register_report group by user_id,company_id,business_unit_id) p on p.user_id=s.user_id and p.company_id is not distinct from s.company_id and p.business_unit_id is not distinct from s.business_unit_id left join (select user_id,company_id,business_unit_id,sum(outstanding_amount) receivables from public.customer_invoice_aging group by user_id,company_id,business_unit_id) ar on ar.user_id=coalesce(s.user_id,p.user_id) and ar.company_id is not distinct from coalesce(s.company_id,p.company_id) and ar.business_unit_id is not distinct from coalesce(s.business_unit_id,p.business_unit_id) left join (select user_id,company_id,business_unit_id,sum(outstanding_amount) payables from public.supplier_invoice_aging group by user_id,company_id,business_unit_id) ap on ap.user_id=coalesce(s.user_id,p.user_id) and ap.company_id is not distinct from coalesce(s.company_id,p.company_id) and ap.business_unit_id is not distinct from coalesce(s.business_unit_id,p.business_unit_id) left join (select user_id,company_id,business_unit_id,sum(stock_value) inventory_value from public.stock_godown_report group by user_id,company_id,business_unit_id) st on st.user_id=coalesce(s.user_id,p.user_id) and st.company_id is not distinct from coalesce(s.company_id,p.company_id) and st.business_unit_id is not distinct from coalesce(s.business_unit_id,p.business_unit_id);

create or replace view public.monthly_business_performance_report with (security_invoker=true) as
select coalesce(s.user_id,p.user_id) user_id,coalesce(s.company_id,p.company_id) company_id,coalesce(s.business_unit_id,p.business_unit_id) business_unit_id,coalesce(s.month_start,p.month_start) month_start,coalesce(s.net_sales,0)::numeric net_sales,coalesce(s.gross_profit,0)::numeric gross_profit,coalesce(p.purchases,0)::numeric purchases from (select user_id,company_id,business_unit_id,date_trunc('month',invoice_date)::date month_start,sum(net_sales_amount) net_sales,sum(gross_profit) gross_profit from public.sales_margin_report group by user_id,company_id,business_unit_id,date_trunc('month',invoice_date)::date) s full join (select user_id,company_id,business_unit_id,date_trunc('month',order_date)::date month_start,sum(total) purchases from public.purchase_register_report group by user_id,company_id,business_unit_id,date_trunc('month',order_date)::date) p on p.user_id=s.user_id and p.company_id is not distinct from s.company_id and p.business_unit_id is not distinct from s.business_unit_id and p.month_start=s.month_start;

grant select on public.customer_profitability_report,public.item_profitability_report,public.salesperson_profitability_report,public.purchase_price_variance_report,public.customer_collection_performance_report,public.supplier_performance_report,public.inventory_aging_report,public.inventory_turnover_report,public.stock_exception_report,public.business_unit_performance_report,public.monthly_business_performance_report to authenticated;