create or replace function public.import_opening_party_balances(p_opening_date date,p_rows jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_company_id uuid;v_user_id uuid;v_ar_account_id uuid;v_ap_account_id uuid;v_opening_equity_id uuid;v_entry_id uuid;v_entry_no text;v_row jsonb;v_party_type text;v_name text;v_name_urdu text;v_email text;v_phone text;v_address text;v_side text;v_amount numeric;v_party_id uuid;v_party_name text;v_debit numeric;v_credit numeric;v_total_debit numeric:=0;v_total_credit numeric:=0;v_created_customers integer:=0;v_created_suppliers integer:=0;v_existing_customers integer:=0;v_existing_suppliers integer:=0;v_line_count integer:=0;v_post_result jsonb;
begin
if not public.is_platform_owner() then raise exception 'Only the software platform owner can import opening party balances.';end if;
v_company_id:=public.current_company_id();v_user_id:=public.legacy_data_user_id();
if v_company_id is null then raise exception 'Select a company before importing opening balances.';end if;if v_user_id is null then raise exception 'No company data owner is available for the selected company.';end if;if p_opening_date is null then raise exception 'Opening date is required.';end if;if p_rows is null or jsonb_typeof(p_rows)<>'array' or jsonb_array_length(p_rows)=0 then raise exception 'Opening balance rows are required.';end if;
select am.account_id into v_ar_account_id from public.account_mappings am where am.company_id=v_company_id and am.user_id=v_user_id and am.mapping_key='accounts_receivable' limit 1;select am.account_id into v_ap_account_id from public.account_mappings am where am.company_id=v_company_id and am.user_id=v_user_id and am.mapping_key='accounts_payable' limit 1;
if v_ar_account_id is null then raise exception 'Accounts Receivable mapping is missing for the selected company.';end if;if v_ap_account_id is null then raise exception 'Accounts Payable mapping is missing for the selected company.';end if;
select am.account_id into v_opening_equity_id from public.account_mappings am where am.company_id=v_company_id and am.user_id=v_user_id and am.mapping_key='opening_balance_equity' limit 1;
if v_opening_equity_id is null then select coa.id into v_opening_equity_id from public.chart_of_accounts coa where coa.company_id=v_company_id and coa.user_id=v_user_id and (coa.code='3300' or lower(trim(coa.name))='opening balance equity') and coa.is_active=true and coa.is_group=false order by case when coa.code='3300' then 0 else 1 end limit 1;end if;
if v_opening_equity_id is null then insert into public.chart_of_accounts(user_id,company_id,code,name,type,account_role,is_group,normal_balance,allow_manual_entries,is_system_account,is_active,description) values(v_user_id,v_company_id,'3300','Opening Balance Equity','equity','general',false,'credit',true,false,true,'System balancing account used only for opening balance migration.') returning id into v_opening_equity_id;end if;
insert into public.account_mappings(user_id,company_id,mapping_key,account_id) values(v_user_id,v_company_id,'opening_balance_equity',v_opening_equity_id) on conflict do nothing;
v_entry_no:='OB-'||to_char(p_opening_date,'YYYYMMDD')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8));insert into public.journal_entries(user_id,company_id,entry_no,entry_date,description,status,trans_type) values(v_user_id,v_company_id,v_entry_no,p_opening_date,'Opening party balances imported by platform owner','draft','opening_balance') returning id into v_entry_id;
for v_row in select value from jsonb_array_elements(p_rows) loop
v_party_type:=lower(trim(coalesce(v_row->>'party_type','')));v_name:=trim(coalesce(v_row->>'name',''));v_name_urdu:=nullif(trim(coalesce(v_row->>'name_urdu','')),'');v_email:=nullif(trim(coalesce(v_row->>'email','')),'');v_phone:=nullif(trim(coalesce(v_row->>'phone','')),'');v_address:=nullif(trim(coalesce(v_row->>'address','')),'');v_side:=lower(trim(coalesce(v_row->>'side','')));begin v_amount:=round((v_row->>'amount')::numeric,2);exception when others then raise exception 'Invalid opening amount for party "%".',v_name;end;
if v_party_type not in('customer','supplier') then raise exception 'Party Type must be Customer or Supplier for "%".',coalesce(nullif(v_name,''),'unnamed row');end if;if v_name='' then raise exception 'English party name is required.';end if;if v_side not in('debit','credit') then raise exception 'Balance Side must be Debit or Credit for "%".',v_name;end if;if v_amount is null or v_amount<=0 then raise exception 'Opening amount must be greater than zero for "%".',v_name;end if;
if v_party_type='customer' then select c.id,c.name into v_party_id,v_party_name from public.customers c where c.company_id=v_company_id and c.user_id=v_user_id and lower(trim(c.name))=lower(v_name) order by c.created_at asc limit 1;if v_party_id is null then insert into public.customers(user_id,company_id,name,name_urdu,email,phone,address,account_id,is_active) values(v_user_id,v_company_id,v_name,coalesce(v_name_urdu,public.english_to_urdu_name(v_name)),v_email,v_phone,v_address,v_ar_account_id,true) returning id,name into v_party_id,v_party_name;v_created_customers:=v_created_customers+1;else update public.customers set name_urdu=coalesce(nullif(name_urdu,''),coalesce(v_name_urdu,public.english_to_urdu_name(v_name))),email=coalesce(email,v_email),phone=coalesce(phone,v_phone),address=coalesce(address,v_address),account_id=v_ar_account_id where id=v_party_id;v_existing_customers:=v_existing_customers+1;end if;
else select s.id,s.name into v_party_id,v_party_name from public.suppliers s where s.company_id=v_company_id and s.user_id=v_user_id and lower(trim(s.name))=lower(v_name) order by s.created_at asc limit 1;if v_party_id is null then insert into public.suppliers(user_id,company_id,name,name_urdu,email,phone,address,account_id,is_active) values(v_user_id,v_company_id,v_name,coalesce(v_name_urdu,public.english_to_urdu_name(v_name)),v_email,v_phone,v_address,v_ap_account_id,true) returning id,name into v_party_id,v_party_name;v_created_suppliers:=v_created_suppliers+1;else update public.suppliers set name_urdu=coalesce(nullif(name_urdu,''),coalesce(v_name_urdu,public.english_to_urdu_name(v_name))),email=coalesce(email,v_email),phone=coalesce(phone,v_phone),address=coalesce(address,v_address),account_id=v_ap_account_id where id=v_party_id;v_existing_suppliers:=v_existing_suppliers+1;end if;end if;
v_debit:=case when v_side='debit' then v_amount else 0 end;v_credit:=case when v_side='credit' then v_amount else 0 end;insert into public.journal_lines(user_id,company_id,entry_id,account_id,account,debit,credit,party_type,party_id,party_name) values(v_user_id,v_company_id,v_entry_id,case when v_party_type='customer' then v_ar_account_id else v_ap_account_id end,case when v_party_type='customer' then 'Accounts Receivable' else 'Accounts Payable' end,v_debit,v_credit,v_party_type,v_party_id,v_party_name);v_total_debit:=v_total_debit+v_debit;v_total_credit:=v_total_credit+v_credit;v_line_count:=v_line_count+1;v_party_id:=null;v_party_name:=null;end loop;
if v_total_debit>v_total_credit then insert into public.journal_lines(user_id,company_id,entry_id,account_id,account,debit,credit) values(v_user_id,v_company_id,v_entry_id,v_opening_equity_id,'Opening Balance Equity',0,round(v_total_debit-v_total_credit,2));elsif v_total_credit>v_total_debit then insert into public.journal_lines(user_id,company_id,entry_id,account_id,account,debit,credit) values(v_user_id,v_company_id,v_entry_id,v_opening_equity_id,'Opening Balance Equity',round(v_total_credit-v_total_debit,2),0);end if;
v_post_result:=public.post_journal_entry(v_entry_id);return jsonb_build_object('success',true,'entry_id',v_entry_id,'entry_no',v_entry_no,'opening_date',p_opening_date,'rows_imported',v_line_count,'created_customers',v_created_customers,'existing_customers',v_existing_customers,'created_suppliers',v_created_suppliers,'existing_suppliers',v_existing_suppliers,'party_debit_total',round(v_total_debit,2),'party_credit_total',round(v_total_credit,2),'post_result',v_post_result);end;$$;
revoke all on function public.import_opening_party_balances(date,jsonb) from public,anon;grant execute on function public.import_opening_party_balances(date,jsonb) to authenticated;