revoke execute on function public.apply_document_discount_total() from authenticated;
revoke execute on function public.bootstrap_default_business_unit() from authenticated;
revoke execute on function public.capture_consolidated_order_fulfillment() from authenticated;
revoke execute on function public.enforce_active_business_unit_write_scope() from authenticated;
revoke execute on function public.enforce_consolidated_sales_charge_master() from authenticated;
revoke execute on function public.enforce_journal_core_rules() from authenticated;
revoke execute on function public.ensure_company_core_defaults() from authenticated;
revoke execute on function public.guard_journal_line_accounting_rules() from authenticated;
revoke execute on function public.guard_journal_line_delete() from authenticated;
revoke execute on function public.guard_posted_journal_immutability() from authenticated;
revoke execute on function public.guard_purchase_consolidated_link_match() from authenticated;
revoke execute on function public.guard_sales_consolidated_link_match() from authenticated;
revoke execute on function public.post_purchase_discount_adjustment() from public, anon, authenticated;
revoke execute on function public.post_sales_discount_adjustment() from public, anon, authenticated;
revoke execute on function public.propagate_business_unit_from_parent() from authenticated;
revoke execute on function public.stamp_stock_movement_audit_context() from authenticated;
revoke execute on function public.sync_consolidated_purchase_inventory_cost() from authenticated;
revoke execute on function public.sync_default_business_unit_membership() from authenticated;
revoke execute on function public.sync_return_line_inventory_cost() from authenticated;
