revoke all on function public.add_draft_sales_invoice_charge(text,uuid,text) from public, anon;
grant execute on function public.add_draft_sales_invoice_charge(text,uuid,text) to authenticated;
revoke all on function public.add_purchase_invoice_line(uuid,uuid,uuid,numeric,numeric,text) from public, anon;
grant execute on function public.add_purchase_invoice_line(uuid,uuid,uuid,numeric,numeric,text) to authenticated;
revoke all on function public.adjust_order_book_quantity(uuid,text,numeric,text) from public, anon;
grant execute on function public.adjust_order_book_quantity(uuid,text,numeric,text) to authenticated;
revoke all on function public.cancel_order_book_order(uuid,text) from public, anon;
grant execute on function public.cancel_order_book_order(uuid,text) to authenticated;
revoke all on function public.create_consolidated_invoice_from_order_commitment(uuid,numeric,uuid,text) from public, anon;
grant execute on function public.create_consolidated_invoice_from_order_commitment(uuid,numeric,uuid,text) to authenticated;
revoke all on function public.delete_consolidated_purchase_draft(uuid) from public, anon;
grant execute on function public.delete_consolidated_purchase_draft(uuid) to authenticated;
revoke all on function public.delete_draft_invoice_line(text,uuid) from public, anon;
grant execute on function public.delete_draft_invoice_line(text,uuid) to authenticated;
revoke all on function public.delete_purchase_invoice_line(uuid) from public, anon;
grant execute on function public.delete_purchase_invoice_line(uuid) to authenticated;
revoke all on function public.get_available_consolidated_purchase_invoices(uuid,uuid) from public, anon;
grant execute on function public.get_available_consolidated_purchase_invoices(uuid,uuid) to authenticated;
revoke all on function public.get_available_consolidated_purchase_invoices_v2(uuid,uuid) from public, anon;
grant execute on function public.get_available_consolidated_purchase_invoices_v2(uuid,uuid) to authenticated;
revoke all on function public.replace_consolidated_purchase_invoice_charges(uuid,jsonb) from public, anon;
grant execute on function public.replace_consolidated_purchase_invoice_charges(uuid,jsonb) to authenticated;
revoke all on function public.replace_purchase_order_charges(uuid,jsonb) from public, anon;
grant execute on function public.replace_purchase_order_charges(uuid,jsonb) to authenticated;
revoke all on function public.restore_order_book_draft_links(text,uuid,jsonb) from public, anon;
grant execute on function public.restore_order_book_draft_links(text,uuid,jsonb) to authenticated;
revoke all on function public.reverse_payment_voucher(uuid,date,text) from public, anon;
grant execute on function public.reverse_payment_voucher(uuid,date,text) to authenticated;
revoke all on function public.revise_order_book_rate(uuid,numeric,date,text) from public, anon;
grant execute on function public.revise_order_book_rate(uuid,numeric,date,text) to authenticated;
revoke all on function public.update_order_book_linked_line(uuid,numeric,uuid,text) from public, anon;
grant execute on function public.update_order_book_linked_line(uuid,numeric,uuid,text) to authenticated;
revoke all on function public.upsert_commercial_invoice_discount(text,text,text,numeric,numeric) from public, anon;
grant execute on function public.upsert_commercial_invoice_discount(text,text,text,numeric,numeric) to authenticated;
revoke all on function public.post_sales_discount_adjustment() from public, anon;
revoke all on function public.post_purchase_discount_adjustment() from public, anon;
