-- Commercial SaaS controls and production-scale database hardening.
create table if not exists public.subscription_plans(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,billing_cycle text not null check(billing_cycle in('monthly','yearly','custom')),price numeric(14,2) not null default 0 check(price>=0),max_users integer not null default 10 check(max_users>0),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.company_subscriptions(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,plan_id uuid references public.subscription_plans(id) on delete set null,billing_cycle text not null check(billing_cycle in('monthly','yearly','custom')),status text not null default 'active' check(status in('trial','active','past_due','suspended','expired','cancelled')),starts_at timestamptz not null default now(),expires_at timestamptz,amount numeric(14,2) not null default 0 check(amount>=0),notes text,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index if not exists company_subscriptions_one_current_idx on public.company_subscriptions(company_id) where status in('trial','active','past_due','suspended');
create index if not exists company_subscriptions_company_idx on public.company_subscriptions(company_id);create index if not exists company_subscriptions_plan_idx on public.company_subscriptions(plan_id);create index if not exists company_subscriptions_expiry_idx on public.company_subscriptions(expires_at);
create table if not exists public.company_modules(company_id uuid not null references public.companies(id) on delete cascade,module_key text not null check(module_key in('dashboard','master','sales','purchase','inventory','production','accounting','reports','settings')),enabled boolean not null default true,updated_by uuid references auth.users(id) on delete set null,updated_at timestamptz not null default now(),primary key(company_id,module_key));
insert into public.subscription_plans(code,name,billing_cycle,price,max_users) values('MONTHLY','Monthly','monthly',0,10),('YEARLY','Yearly','yearly',0,25) on conflict(code) do nothing;
insert into public.company_modules(company_id,module_key,enabled) select c.id,m.k,true from public.companies c cross join(values('dashboard'),('master'),('sales'),('purchase'),('inventory'),('production'),('accounting'),('reports'),('settings'))m(k) on conflict(company_id,module_key) do nothing;
alter table public.subscription_plans enable row level security;alter table public.company_subscriptions enable row level security;alter table public.company_modules enable row level security;
drop policy if exists subscription_plans_read on public.subscription_plans;create policy subscription_plans_read on public.subscription_plans for select to authenticated using(true);
drop policy if exists subscription_plans_owner_write on public.subscription_plans;create policy subscription_plans_owner_write on public.subscription_plans for all to authenticated using(public.is_platform_owner()) with check(public.is_platform_owner());
drop policy if exists company_subscriptions_access on public.company_subscriptions;create policy company_subscriptions_access on public.company_subscriptions for select to authenticated using(public.is_platform_owner() or public.has_company_access(company_id));
drop policy if exists company_subscriptions_owner_write on public.company_subscriptions;create policy company_subscriptions_owner_write on public.company_subscriptions for all to authenticated using(public.is_platform_owner()) with check(public.is_platform_owner());
drop policy if exists company_modules_access on public.company_modules;create policy company_modules_access on public.company_modules for select to authenticated using(public.is_platform_owner() or public.has_company_access(company_id));
drop policy if exists company_modules_owner_write on public.company_modules;create policy company_modules_owner_write on public.company_modules for all to authenticated using(public.is_platform_owner()) with check(public.is_platform_owner());
revoke all on public.subscription_plans,public.company_subscriptions,public.company_modules from anon;grant select on public.subscription_plans,public.company_subscriptions,public.company_modules to authenticated;grant insert,update,delete on public.subscription_plans,public.company_subscriptions,public.company_modules to authenticated;
create or replace function public.company_module_enabled(p_company_id uuid,p_module text) returns boolean language sql stable security definer set search_path=public,pg_temp as $$select coalesce((select enabled from public.company_modules where company_id=p_company_id and module_key=p_module),true)$$;revoke all on function public.company_module_enabled(uuid,text) from public,anon;grant execute on function public.company_module_enabled(uuid,text) to authenticated;
create or replace function public.has_module_permission(p_company_id uuid,p_module text,p_action text) returns boolean language plpgsql stable security definer set search_path=public,pg_temp as $$declare v_role text;v_permissions jsonb;v_override jsonb;begin if p_company_id is null or p_company_id<>public.current_company_id() then return false;end if;if not public.company_module_enabled(p_company_id,p_module) and p_module<>'dashboard' then return false;end if;if public.is_platform_owner() then return true;end if;if not public.has_company_access(p_company_id) then return false;end if;select role,permissions into v_role,v_permissions from public.company_memberships where company_id=p_company_id and user_id=auth.uid() and is_active=true limit 1;v_override:=v_permissions#>array[p_module,p_action];if v_override is not null then return(v_override#>>'{}')::boolean;end if;if v_role in('company_owner','admin') then return true;end if;if p_action in('view','print') then return case v_role when 'accounts' then p_module in('accounting','reports','master') when 'sales' then p_module in('sales','reports','master','inventory') when 'purchase' then p_module in('purchase','reports','master','inventory') when 'store' then p_module in('inventory','reports','master') when 'production' then p_module in('production','inventory','reports','master') when 'viewer' then p_module='reports' else false end;end if;if p_action='delete' then return false;end if;if p_action in('create','edit','post') then return case v_role when 'accounts' then p_module='accounting' when 'sales' then p_module='sales' when 'purchase' then p_module='purchase' when 'store' then p_module='inventory' when 'production' then p_module='production' else false end;end if;return false;end$$;
create or replace function public.get_my_access_context() returns jsonb language sql stable security definer set search_path=public,pg_temp as $$select jsonb_build_object('user_id',auth.uid(),'profile_active',coalesce(p.is_active,false),'platform_role',coalesce(p.platform_role,'user'),'is_platform_owner',coalesce(p.platform_role='super_admin' and p.is_active,false),'current_company_id',public.current_company_id(),'companies',coalesce((select jsonb_agg(x.obj order by x.company_name) from(select c.name company_name,jsonb_build_object('company_id',c.id,'company_name',c.name,'company_code',c.code,'company_status',c.status,'subscription_expires_at',c.subscription_expires_at,'membership_role',coalesce(m.role,case when p.platform_role='super_admin' then 'company_owner' end),'membership_active',coalesce(m.is_active,p.platform_role='super_admin'),'permissions',coalesce(m.permissions,'{}'::jsonb),'enabled_modules',coalesce((select jsonb_agg(cm.module_key order by cm.module_key) from public.company_modules cm where cm.company_id=c.id and cm.enabled),'[]'::jsonb),'access_allowed',(p.is_active and c.status in('trial','active') and(c.subscription_expires_at is null or c.subscription_expires_at>now())and(p.platform_role='super_admin' or coalesce(m.is_active,false))))obj from public.companies c left join public.company_memberships m on m.company_id=c.id and m.user_id=auth.uid() where p.platform_role='super_admin' or m.user_id is not null)x),'[]'::jsonb)) from public.user_profiles p where p.id=auth.uid()$$;
-- Internal maintenance RPC is owner-only; ordinary users never need it.
revoke execute on function public.backfill_company_urdu_names() from authenticated,anon,public;
-- Add covering indexes for every public foreign key that currently lacks one. Safe to rerun.
do $$declare r record;cols text;idx text;begin for r in select c.oid,c.conrelid,c.conname,c.conkey,n.nspname,t.relname from pg_constraint c join pg_class t on t.oid=c.conrelid join pg_namespace n on n.oid=t.relnamespace where c.contype='f' and n.nspname='public' loop if not exists(select 1 from pg_index i where i.indrelid=r.conrelid and(i.indkey::smallint[])[0:cardinality(r.conkey)-1]=r.conkey) then select string_agg(quote_ident(a.attname),',' order by u.ord) into cols from unnest(r.conkey) with ordinality u(attnum,ord) join pg_attribute a on a.attrelid=r.conrelid and a.attnum=u.attnum;idx:=left('idx_fk_'||r.relname||'_'||r.conname,60);execute format('create index if not exists %I on %I.%I (%s)',idx,r.nspname,r.relname,cols);end if;end loop;end$$;
